import Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Basic
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.Probability.Independence.Process.HasIndepIncrements
import Mathlib.Probability.Process.Adapted
import Mathlib.Probability.Process.Kolmogorov

/-!
# S1-M-218 / THM-M-1027: Existence of Wiener process

This Stage1 file records a conservative Lean boundary for the existence of a
Wiener process, also known as standard Brownian motion.  The pinned mathlib
snapshot has Gaussian-process, independent-increment, filtration/adaptedness,
Gaussian-real-law, Ionescu-Tulcea, and Kolmogorov-process infrastructure, but no
terminal theorem constructing a continuous Wiener process was found in the local
dependency closure.

The declarations below therefore normalize the theorem statement around a
nonnegative-real time index.  The proved content is limited to low-risk wrappers
around existing mathlib APIs.  No construction of Brownian motion is claimed in
this file.  An external Lean 4 project, `RemyDegenne/brownian-motion`, contains
the terminal Brownian construction names; this file does not import or pin that
project.
-/

noncomputable section

open MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal

universe u

namespace AwesomeTheorems
namespace Stage1
namespace S1_M_218

/-- The canonical time axis for standard Brownian motion in this Stage1 boundary. -/
abbrev BrownianTime := ℝ≥0

/-- Real-valued stochastic process on a measurable probability space. -/
abbrev RealProcess (Ω : Type u) := BrownianTime → Ω → ℝ

/-- Variance parameter of the increment from `s` to `t`, assuming `s ≤ t`. -/
def incrementVariance (s t : BrownianTime) (hst : s ≤ t) : ℝ≥0 :=
  ⟨(t : ℝ) - (s : ℝ), sub_nonneg.mpr (by exact_mod_cast hst)⟩

/--
Standard Brownian/Wiener process properties over a fixed probability space.

The fields are deliberately statement-level:
* measurability of each coordinate random variable,
* standard Gaussian law for each ordered increment,
* Gaussian finite-dimensional distributions,
* independent increments,
* continuous sample paths,
* start at zero almost surely,
* adaptedness to the natural filtration generated by the process.
-/
structure WienerProcess (Ω : Type u) [MeasurableSpace Ω]
    (P : Measure Ω) (W : RealProcess Ω) : Prop where
  measurable : ∀ t : BrownianTime, Measurable (W t)
  increment_hasLaw :
    ∀ ⦃s t : BrownianTime⦄, (hst : s ≤ t) →
      HasLaw (fun ω ↦ W t ω - W s ω)
        (gaussianReal 0 (incrementVariance s t hst)) P
  gaussianProcess : IsGaussianProcess W P
  indepIncrements : HasIndepIncrements W P
  continuous_paths : ∀ᵐ ω ∂P, Continuous fun t : BrownianTime ↦ W t ω
  starts_at_zero : ∀ᵐ ω ∂P, W 0 ω = 0
  adapted_natural :
    Adapted (Filtration.natural W fun t ↦ (measurable t).stronglyMeasurable) W

/--
Normalized Stage1 statement-shape candidate for the existence of standard
Brownian motion.

This is a `Prop` boundary only: it states that some probability space carries a
process satisfying the usual Wiener-process axioms.  It is not marked as a
completed proof of existence in this repository.
-/
def StatementShape : Prop :=
  ∃ (Ω : Type u) (_ : MeasurableSpace Ω) (P : Measure Ω) (W : RealProcess Ω),
    IsProbabilityMeasure P ∧ WienerProcess Ω P W

/-- The statement shape exposes an explicitly probability-measured process. -/
theorem statementShape_intro
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hP : IsProbabilityMeasure P) (hW : WienerProcess Ω P W) :
    StatementShape.{u} :=
  ⟨Ω, inferInstance, P, W, hP, hW⟩

/-- The ordered-increment variance agrees with truncated subtraction on `ℝ≥0`. -/
theorem incrementVariance_eq_tsub {s t : BrownianTime} (hst : s ≤ t) :
    incrementVariance s t hst = t - s := by
  apply NNReal.eq
  rw [NNReal.coe_sub hst]
  simp [incrementVariance]

/--
For ordered times, the local variance convention matches the symmetric variance
used by the external Brownian construction's subtraction-law theorem.
-/
theorem incrementVariance_eq_max_tsub {s t : BrownianTime} (hst : s ≤ t) :
    incrementVariance s t hst = max (t - s) (s - t) := by
  rw [max_eq_left]
  · exact incrementVariance_eq_tsub hst
  · rw [tsub_eq_zero_of_le hst]
    exact zero_le _

/-- A real random variable with law `gaussianReal 0 0` is zero almost surely. -/
theorem hasLaw_gaussianReal_zero_ae_eq_zero
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {X : Ω → ℝ}
    (hX : HasLaw X (gaussianReal 0 0) P) :
    ∀ᵐ ω ∂P, X ω = 0 := by
  refine (hX.ae_iff (p := fun x ↦ x = 0) (by fun_prop)).2 ?_
  rw [gaussianReal_zero_var]
  simp

/--
Bridge shape for the external `brownian-motion` component theorems.

Once `BrownianMotion.Gaussian.BrownianMotion` is available in the local Lake
closure, the external theorem `hasLaw_brownian_sub` has the symmetric
variance `max (s - t) (t - s)`.  This wrapper normalizes that convention to
the ordered increment law required by `WienerProcess`.
-/
theorem WienerProcess.of_externalBrownianComponents
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (h_meas : ∀ t : BrownianTime, Measurable (W t))
    (h_increment_abs :
      ∀ s t : BrownianTime,
        HasLaw (fun ω ↦ W s ω - W t ω)
          (gaussianReal 0 (max (s - t) (t - s))) P)
    (h_law_zero : HasLaw (W 0) (gaussianReal 0 0) P)
    (h_gaussian : IsGaussianProcess W P)
    (h_indep : HasIndepIncrements W P)
    (h_continuous_all : ∀ ω : Ω, Continuous fun t : BrownianTime ↦ W t ω) :
    WienerProcess Ω P W where
  measurable := h_meas
  increment_hasLaw := by
    intro s t hst
    simpa [incrementVariance_eq_max_tsub hst] using h_increment_abs t s
  gaussianProcess := h_gaussian
  indepIncrements := h_indep
  continuous_paths := Filter.Eventually.of_forall h_continuous_all
  starts_at_zero := hasLaw_gaussianReal_zero_ae_eq_zero h_law_zero
  adapted_natural :=
    (Filtration.stronglyAdapted_natural (u := W)
      (fun t ↦ (h_meas t).stronglyMeasurable)).adapted

/--
Statement-shape wrapper for the same external-component bridge.

This is not the terminal Brownian existence proof: it still requires the
external Brownian package to be pinned/imported and the component facts to be
instantiated with `ProbabilityTheory.brownian` and its canonical measure.
-/
theorem statementShape_of_externalBrownianComponents
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hP : IsProbabilityMeasure P)
    (h_meas : ∀ t : BrownianTime, Measurable (W t))
    (h_increment_abs :
      ∀ s t : BrownianTime,
        HasLaw (fun ω ↦ W s ω - W t ω)
          (gaussianReal 0 (max (s - t) (t - s))) P)
    (h_law_zero : HasLaw (W 0) (gaussianReal 0 0) P)
    (h_gaussian : IsGaussianProcess W P)
    (h_indep : HasIndepIncrements W P)
    (h_continuous_all : ∀ ω : Ω, Continuous fun t : BrownianTime ↦ W t ω) :
    StatementShape.{u} :=
  statementShape_intro hP
    (WienerProcess.of_externalBrownianComponents
      h_meas h_increment_abs h_law_zero h_gaussian h_indep h_continuous_all)

/--
Checked mathlib anchor: a Gaussian process lives over a probability measure.
-/
theorem gaussianProcess_isProbabilityMeasure
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hW : IsGaussianProcess W P) :
    IsProbabilityMeasure P :=
  hW.isProbabilityMeasure

/--
Checked mathlib anchor: each coordinate of a Gaussian process is a.e.
measurable.
-/
theorem gaussianProcess_aemeasurable_eval
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hW : IsGaussianProcess W P) (t : BrownianTime) :
    AEMeasurable (W t) P :=
  hW.aemeasurable t

/--
Checked mathlib anchor: each coordinate of a real Gaussian process has a
Gaussian law.
-/
theorem gaussianProcess_hasGaussianLaw_eval
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hW : IsGaussianProcess W P) (t : BrownianTime) :
    HasGaussianLaw (W t) P :=
  hW.hasGaussianLaw_eval t

/--
Checked mathlib anchor: finite ordered increments of a real Gaussian process
have a Gaussian law.
-/
theorem gaussianProcess_hasGaussianLaw_increments
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hW : IsGaussianProcess W P) {n : ℕ} {t : Fin (n + 1) → BrownianTime} :
    HasGaussianLaw (fun ω (i : Fin n) ↦ W (t i.succ) ω - W (t i.castSucc) ω) P :=
  hW.hasGaussianLaw_increments

/--
Checked mathlib anchor: the general independent-increment predicate gives
independence of two adjacent increments.
-/
theorem indepIncrements_indepFun_sub_sub
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    (hW : HasIndepIncrements W P) {r s t : BrownianTime}
    (hrs : r ≤ s) (hst : s ≤ t) :
    (W s - W r) ⟂ᵢ[P] (W t - W s) :=
  hW.indepFun_sub_sub hrs hst

/--
Checked mathlib anchor: the finite-dimensional formulation of independent
increments is equivalent to the monotone-sequence formulation.
-/
theorem hasIndepIncrements_iff_nat_wrapper
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω} :
    HasIndepIncrements W P ↔
      ∀ t : ℕ → BrownianTime, Monotone t →
        iIndepFun (fun i ω ↦ W (t (i + 1)) ω - W (t i) ω) P :=
  hasIndepIncrements_iff_nat

/--
Checked mathlib anchor: coordinate measurability plus the Kolmogorov moment
bound builds a `IsKolmogorovProcess` hypothesis object.
-/
theorem kolmogorovProcess_mk_of_secondCountableTopology
    {Ω : Type u} [MeasurableSpace Ω] {P : Measure Ω} {W : RealProcess Ω}
    {p q : ℝ} {M : ℝ≥0}
    (h_meas : ∀ s : BrownianTime, Measurable (W s))
    (h_kol :
      ∀ s t : BrownianTime,
        ∫⁻ ω, edist (W s ω) (W t ω) ^ p ∂P ≤ M * edist s t ^ q)
    (hp : 0 < p) (hq : 0 < q) :
    IsKolmogorovProcess W P p q M :=
  IsKolmogorovProcess.mk_of_secondCountableTopology h_meas h_kol hp hq

/-! ## Audit probes retained in the checked file. -/

#check WienerProcess
#check StatementShape
#check incrementVariance_eq_tsub
#check incrementVariance_eq_max_tsub
#check hasLaw_gaussianReal_zero_ae_eq_zero
#check WienerProcess.of_externalBrownianComponents
#check statementShape_of_externalBrownianComponents
#check ProbabilityTheory.IsGaussianProcess
#check ProbabilityTheory.IsGaussianProcess.isProbabilityMeasure
#check ProbabilityTheory.IsGaussianProcess.aemeasurable
#check ProbabilityTheory.IsGaussianProcess.hasGaussianLaw_eval
#check ProbabilityTheory.IsGaussianProcess.hasGaussianLaw_increments
#check ProbabilityTheory.HasIndepIncrements
#check ProbabilityTheory.hasIndepIncrements_iff_nat
#check ProbabilityTheory.HasIndepIncrements.indepFun_sub_sub
#check ProbabilityTheory.IsKolmogorovProcess
#check ProbabilityTheory.IsKolmogorovProcess.mk_of_secondCountableTopology
#check ProbabilityTheory.gaussianReal
#check MeasureTheory.Filtration
#check MeasureTheory.Filtration.natural
#check MeasureTheory.Adapted
#check ProbabilityTheory.HasLaw

/-- mathlib modules checked while locating repo-local anchors for this slot. -/
def mathlibAnchorModules : List String := [
  "Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Def",
  "Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Basic",
  "Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Independence",
  "Mathlib.Probability.Distributions.Gaussian.Real",
  "Mathlib.Probability.HasLaw",
  "Mathlib.Probability.HasLawExists",
  "Mathlib.Probability.Independence.Process.HasIndepIncrements",
  "Mathlib.Probability.Process.Filtration",
  "Mathlib.Probability.Process.Adapted",
  "Mathlib.Probability.Process.Kolmogorov",
  "Mathlib.Probability.Kernel.IonescuTulcea.Traj"
]

/-- Nearby checked names used or audited for the Stage1 statement boundary. -/
def mathlibAnchorNames : List String := [
  "ProbabilityTheory.IsGaussianProcess",
  "ProbabilityTheory.IsGaussianProcess.isProbabilityMeasure",
  "ProbabilityTheory.IsGaussianProcess.aemeasurable",
  "ProbabilityTheory.IsGaussianProcess.hasGaussianLaw_eval",
  "ProbabilityTheory.IsGaussianProcess.hasGaussianLaw_increments",
  "ProbabilityTheory.HasIndepIncrements",
  "ProbabilityTheory.hasIndepIncrements_iff_nat",
  "ProbabilityTheory.HasIndepIncrements.indepFun_sub_sub",
  "ProbabilityTheory.IsKolmogorovProcess",
  "ProbabilityTheory.IsKolmogorovProcess.mk_of_secondCountableTopology",
  "ProbabilityTheory.gaussianReal",
  "ProbabilityTheory.HasLaw",
  "MeasureTheory.Filtration.natural",
  "MeasureTheory.Adapted",
  "ProbabilityTheory.Kernel.traj"
]

/--
Search terms that did not locate a terminal Brownian/Wiener existence theorem
in the pinned local mathlib tree.
-/
def absentTerminalSearchTerms : List String := [
  "Brownian",
  "Wiener process",
  "standard Brownian motion",
  "Brownian motion exists",
  "continuous Gaussian process independent increments",
  "Kolmogorov Chentsov",
  "Wiener measure"
]

/-- External Lean 4 anchors found but not integrated into this repository. -/
def externalLeanAnchorNames : List String := [
  "BrownianMotion.Gaussian.BrownianMotion",
  "ProbabilityTheory.IsPreBrownian",
  "ProbabilityTheory.IsBrownian",
  "ProbabilityTheory.brownian",
  "ProbabilityTheory.IsBrownian_brownian",
  "ProbabilityTheory.isGaussianProcess_brownian",
  "ProbabilityTheory.hasLaw_brownian",
  "ProbabilityTheory.hasLaw_brownian_eval",
  "ProbabilityTheory.hasLaw_brownian_sub",
  "ProbabilityTheory.continuous_brownian",
  "ProbabilityTheory.hasIndepIncrements_brownian",
  "ProbabilityTheory.wienerMeasure"
]

/--
Exact external candidate identified for a future serial Lake integration pass.

The `v4.29.0` tag is the compatibility candidate because its `lean-toolchain`
and inherited mathlib revision match this repository's current Lean project.
This declaration is audit data only: the dependency is not yet in this
repository's `lakefile.lean` or `lake-manifest.json`.
-/
def externalBrownianCompatiblePinAudit : List String := [
  "project: https://github.com/RemyDegenne/brownian-motion",
  "candidate tag: v4.29.0",
  "module: BrownianMotion.Gaussian.BrownianMotion",
  "external lean-toolchain: leanprover/lean4:v4.29.0",
  "external inherited mathlib: 8a178386ffc0f5fef0b77738bb5449d50efeea95",
  "external kolmogorov_extension4 dependency: v4.29.0 / e8d02e83550f893bbf48f0b651f782eccf6760e8",
  "local lean-toolchain: leanprover/lean4:v4.29.0",
  "local mathlib: 8a178386ffc0f5fef0b77738bb5449d50efeea95",
  "status: compatible candidate found, not yet recorded in the shared Lean project"
]

/--
Repo-local import-check evidence for the external Brownian module.

This records the strongest check available inside this child pass without
editing shared Lake configuration.  A literal top-level import is intentionally
not added here because it would make this Stage1 artifact fail until the serial
dependency integration pass adds the external package to the Lean project.
-/
def externalBrownianRepoLocalImportCheck : List String := [
  "date: 2026-05-01",
  "command: cd Formalizations/Lean && printf 'import BrownianMotion.Gaussian.BrownianMotion\\n#check ProbabilityTheory.IsBrownian\\n' | lake env lean /dev/stdin",
  "result: failed",
  "diagnostic: unknown module prefix 'BrownianMotion'",
  "search path includes mathlib and flt-regular but no BrownianMotion package",
  "classification: repo_local_integration_debt, not completed"
]

/--
Checked repo-local bridge contract for the future external import pass.

The theorem `WienerProcess.of_externalBrownianComponents` is already checked in
this file.  These strings record how the external names are expected to feed it
after `BrownianMotion.Gaussian.BrownianMotion` is available.
-/
def externalBrownianBridgeContract : List String := [
  "ProbabilityTheory.brownian instantiates the local process W",
  "ProbabilityTheory.measurable_brownian supplies the coordinate measurability field",
  "ProbabilityTheory.hasLaw_brownian_sub supplies the symmetric increment law; the checked local theorem incrementVariance_eq_max_tsub normalizes it for ordered increments",
  "ProbabilityTheory.hasLaw_brownian_eval at t = 0 supplies the zero-start field through hasLaw_gaussianReal_zero_ae_eq_zero",
  "ProbabilityTheory.isGaussianProcess_brownian supplies the Gaussian-process field",
  "ProbabilityTheory.hasIndepIncrements_brownian supplies the independent-increments field",
  "ProbabilityTheory.continuous_brownian supplies all-sample-path continuity and therefore the local almost-sure continuity field",
  "ProbabilityTheory.IsBrownian_brownian packages the external Brownian predicate for the canonical process",
  "the zero-start field should be discharged from the external zero-time Gaussian law, for example via the external/project HasLaw gaussianReal zero-start API",
  "the checked local wrapper statementShape_of_externalBrownianComponents derives StatementShape only after all component facts are instantiated in the pinned external environment"
]

/--
Integration blockers that prevent this child pass from claiming
`external_upstream_pinned`.
-/
def externalBrownianIntegrationBlockers : List String := [
  "owned write scope excludes Formalizations/Lean/lakefile.lean",
  "owned write scope excludes Formalizations/Lean/lake-manifest.json",
  "import BrownianMotion.Gaussian.BrownianMotion is not available until the Lake dependency is added",
  "the repo-local component wrapper is checked, but no wrapper instantiated with imported external Brownian declarations has been checked"
]

end S1_M_218
end Stage1
end AwesomeTheorems
