import Mathlib.NumberTheory.NumberField.AdeleRing
import Mathlib.NumberTheory.NumberField.ClassNumber
import Mathlib.FieldTheory.Galois.Abelian
import Mathlib.GroupTheory.Index
import Mathlib.Topology.Algebra.Group.Quotient

/-!
# S1-M-077 / THM-M-0422

Stage1 statement-shape artifact for global class field theory over number fields.

mathlib currently supplies number fields, rings of integers, class groups, adeles,
abelian Galois extensions, and enough quotient-group infrastructure to define a
concrete multiplicative-ideles object as the unit group of the adele ring.  This
file records those checked anchors and keeps the terminal class-field-theory
correspondence as an explicit abstract boundary: finite abelian extensions of a
number field should correspond to open finite-index subgroups of the idele class
group, via a reciprocity map.
-/

open scoped NumberField

noncomputable section

namespace AwesomeTheorems.Stage1.S1_M_077

universe uK uL uC uE

/--
A finite abelian extension package over a base field `K`.

This uses mathlib's `IsAbelianGalois` class as the checked algebraic side of the
class-field-theory statement, while leaving the classification by idele-class
data to `ClassFieldReciprocityData` below.
-/
structure FiniteAbelianExtension (K : Type uK) [Field K] where
  L : Type uL
  [field : Field L]
  [algebra : Algebra K L]
  [finiteDimensional : FiniteDimensional K L]
  [isAbelianGalois : IsAbelianGalois K L]

attribute [instance] FiniteAbelianExtension.field
attribute [instance] FiniteAbelianExtension.algebra
attribute [instance] FiniteAbelianExtension.finiteDimensional
attribute [instance] FiniteAbelianExtension.isAbelianGalois

/-- The number-field adele ring currently supplied by mathlib. -/
abbrev NumberFieldAdeleRing (K : Type uK) [Field K] [NumberField K] :=
  NumberField.AdeleRing (𝓞 K) K

/--
Concrete multiplicative ideles available from pinned mathlib infrastructure.

This is the group of units of mathlib's number-field adele ring.  It is not a
global reciprocity map, but it removes the previous abstract `IdeleClassGroup`
field from the Stage1 object model.
-/
abbrev MultiplicativeIdeles (K : Type uK) [Field K] [NumberField K] :=
  Units (NumberFieldAdeleRing K)

/-- The diagonal homomorphism from `Kˣ` into the multiplicative ideles. -/
def principalIdeleHom
    (K : Type uK) [Field K] [NumberField K] :
    Kˣ →* MultiplicativeIdeles K :=
  Units.map (algebraMap K (NumberFieldAdeleRing K))

/-- The diagonal homomorphism into ideles is injective. -/
theorem principalIdeleHom_injective
    (K : Type uK) [Field K] [NumberField K] :
    Function.Injective (principalIdeleHom K) := by
  intro x y hxy
  apply Units.ext
  exact NumberField.AdeleRing.algebraMap_injective (𝓞 K) K (congrArg Units.val hxy)

/-- Principal ideles, as the subgroup generated by the diagonal image of `Kˣ`. -/
abbrev PrincipalIdeles (K : Type uK) [Field K] [NumberField K] :
    Subgroup (MultiplicativeIdeles K) :=
  MonoidHom.range (principalIdeleHom K)

/--
Concrete idele class group from pinned mathlib primitives: multiplicative
ideles modulo principal ideles.
-/
abbrev IdeleClassGroup (K : Type uK) [Field K] [NumberField K] :=
  MultiplicativeIdeles K ⧸ PrincipalIdeles K

/-- The quotient homomorphism from ideles to the idele class group. -/
def ideleClassQuotientHom
    (K : Type uK) [Field K] [NumberField K] :
    MultiplicativeIdeles K →* IdeleClassGroup K :=
  QuotientGroup.mk' (PrincipalIdeles K)

/-- The quotient homomorphism from ideles to the idele class group is surjective. -/
theorem ideleClassQuotientHom_surjective
    (K : Type uK) [Field K] [NumberField K] :
    Function.Surjective (ideleClassQuotientHom K) := by
  simpa [ideleClassQuotientHom] using
    (QuotientGroup.mk'_surjective (PrincipalIdeles K))

/-- The quotient homomorphism has kernel exactly the subgroup of principal ideles. -/
theorem ideleClassQuotientHom_ker
    (K : Type uK) [Field K] [NumberField K] :
    MonoidHom.ker (ideleClassQuotientHom K) = PrincipalIdeles K := by
  exact QuotientGroup.ker_mk' (PrincipalIdeles K)

/--
Open finite-index subgroups of the concrete idele class group.

The topology is mathlib's quotient topology on quotient groups.  The finite-index
condition uses mathlib's `Subgroup.FiniteIndex` class.
-/
structure OpenFiniteIndexIdeleClassSubgroup
    (K : Type uK) [Field K] [NumberField K] where
  carrier : Subgroup (IdeleClassGroup K)
  isOpen_carrier : IsOpen (carrier : Set (IdeleClassGroup K))
  finiteIndex_carrier : carrier.FiniteIndex

instance
    (K : Type uK) [Field K] [NumberField K] :
    Group (IdeleClassGroup K) := by
  infer_instance

instance
    (K : Type uK) [Field K] [NumberField K] :
    TopologicalSpace (IdeleClassGroup K) := by
  infer_instance

/--
Abstract data needed to state the global class field theory correspondence.

The idele class group itself is now concrete in this file.  The remaining
abstract boundary is the global Artin/reciprocity construction and the finite
abelian extension object classified by open finite-index subgroups.
-/
structure ClassFieldReciprocityData
    (K : Type uK) [Field K] [NumberField K] :
    Type (max (uK + 1) (max (uL + 1) (uE + 1))) where
  Extension : Type uE
  toFiniteAbelianExtension : Extension → FiniteAbelianExtension.{uK, uL} K
  reciprocityKernel : Extension → OpenFiniteIndexIdeleClassSubgroup K

/--
Statement-shape candidate for global class field theory.

For a number field `K`, finite abelian extensions are represented by
`data.Extension`, open finite-index subgroups use the concrete idele class group
`IdeleClassGroup K`, and `data.reciprocityKernel` is the kernel map coming from
global reciprocity.  The terminal theorem would replace `data.Extension` and
`data.reciprocityKernel` with a pinned Artin/global reciprocity construction and
prove the bijection.
-/
def StatementShape
    (K : Type uK) [Field K] [NumberField K]
    (data : ClassFieldReciprocityData.{uK, uL, uE} K) : Prop :=
  Function.Bijective data.reciprocityKernel

/-- Checked mathlib anchor: the class number is positive for every number field. -/
theorem numberFieldClassNumber_pos
    (K : Type uK) [Field K] [NumberField K] :
    0 < NumberField.classNumber K :=
  NumberField.classNumber_pos K

/--
Checked mathlib anchor: class number one is equivalent to the ring of integers
being a principal ideal ring.
-/
theorem numberFieldClassNumber_eq_one_iff_pid
    (K : Type uK) [Field K] [NumberField K] :
    NumberField.classNumber K = 1 ↔ IsPrincipalIdealRing (𝓞 K) :=
  NumberField.classNumber_eq_one_iff

/-- Checked mathlib anchor: the diagonal map from a number field into its adele ring is injective. -/
theorem adeleRing_algebraMap_injective
    (R : Type uC) (K : Type uK) [CommRing R] [IsDedekindDomain R]
    [Field K] [Algebra R K] [IsFractionRing R K] [NumberField K] :
    Function.Injective (algebraMap K (NumberField.AdeleRing R K)) :=
  NumberField.AdeleRing.algebraMap_injective R K

/-- Checked mathlib anchor: principal adeles are the additive range of the diagonal embedding. -/
theorem adeleRing_principalSubgroup_def
    (R : Type uC) (K : Type uK) [CommRing R] [IsDedekindDomain R]
    [Field K] [Algebra R K] [IsFractionRing R K] :
    NumberField.AdeleRing.principalSubgroup R K =
      (algebraMap K (NumberField.AdeleRing R K)).range.toAddSubgroup :=
  rfl

/-- Checked mathlib anchor: cyclic Galois extensions are abelian Galois extensions. -/
theorem isAbelianGalois_of_cyclic_galois
    (K : Type uK) (L : Type uL) [Field K] [Field L] [Algebra K L]
    [IsGalois K L] [IsCyclic Gal(L/K)] :
    IsAbelianGalois K L :=
  IsAbelianGalois.of_isCyclic K L

/-- mathlib modules checked while locating repo-local anchors for this slot. -/
def mathlibAnchorModules : List String := [
  "Mathlib.NumberTheory.NumberField.AdeleRing",
  "Mathlib.NumberTheory.NumberField.ClassNumber",
  "Mathlib.FieldTheory.Galois.Abelian",
  "Mathlib.GroupTheory.Index",
  "Mathlib.Topology.Algebra.Group.Quotient",
  "Mathlib.NumberTheory.RamificationInertia.Galois",
  "Mathlib.RingTheory.ClassGroup"
]

/-- Search terms that did not locate a terminal global class field theory theorem in local mathlib. -/
def absentTerminalSearchTerms : List String := [
  "ClassField",
  "class field",
  "Artin",
  "Reciprocity",
  "ray class",
  "global reciprocity",
  "Artin reciprocity",
  "Abelian extension"
]

/--
External audit target for the `kbuzzard/ClassFieldTheory` repository.

This is metadata only: the external repository is not imported into this Lake
closure by this Stage1 artifact.
-/
def externalClassFieldTheoryAuditCommit : String :=
  "11f0a7f3874b6891e8e8290d1e645d61ed06e1aa"

/-- Source surfaces inspected for the external `kbuzzard/ClassFieldTheory` audit. -/
def externalClassFieldTheoryAuditSurfaces : List String := [
  "ClassFieldTheory.lean root imports",
  "ClassFieldTheory/**/*.lean declarations",
  "blueprint/lean_decls",
  "blueprint/src/_2_cohomology.tex",
  "blueprint/src/_3_local.tex",
  "blueprint/src/_4_global.tex",
  "lake-manifest.json",
  "README.md"
]

/--
Exact Lean declarations found in `kbuzzard/ClassFieldTheory` that are related to
class formations or reciprocity, but are not terminal global Artin reciprocity or
global CFT theorem names.
-/
def externalClassFieldTheoryNonterminalAnchors : List String := [
  "localInv",
  "localInvIso",
  "localInv_symm_apply",
  "Rep.split.FiniteClassFormation",
  "Rep.split.tateCohomologyIso",
  "Rep.split.reciprocityIso"
]

/--
Global-CFT blueprint labels seen in `kbuzzard/ClassFieldTheory`.

These are LaTeX blueprint labels rather than Lean declarations, so they are not
repo-local machine-checkable terminal theorem names.
-/
def externalClassFieldTheoryGlobalBlueprintLabels : List String := [
  "lem:idele class invariants",
  "lem:semi-local iso coind",
  "lem:cohomology S-ideles decomp",
  "lem:herbrand S-ideles",
  "lem:herbrand idele class group",
  "lem:H0 idele class group finite",
  "cor:H1 H2 cyclic idele class",
  "thm:first inequality",
  "thm:global cohomology bound"
]

/--
Exact terminal Lean theorem names found for global Artin reciprocity or global
class field theory in the audited external repository.

The empty list records the audit result at `externalClassFieldTheoryAuditCommit`:
no such terminal Lean declaration was located, and the external repository is
not pinned into this repository's Lake closure.
-/
def externalClassFieldTheoryTerminalGlobalTheoremNames : List String := []

/--
Local Lake mathlib revision recorded in this repository's manifest while
auditing whether `kbuzzard/ClassFieldTheory` can be added as a dependency.
-/
def localLakeMathlibRevision : String :=
  "8a178386ffc0f5fef0b77738bb5449d50efeea95"

/--
External `kbuzzard/ClassFieldTheory` mathlib revision recorded in
`lake-manifest.json` at `externalClassFieldTheoryAuditCommit`.
-/
def externalClassFieldTheoryMathlibRevision : String :=
  "3bd2603b817feffa4cc0ce9f5d6bad4094ca746e"

/--
Checked metadata fact for the dependency-integration child task: the external
project's recorded mathlib revision is not this repository's recorded mathlib
revision.
-/
theorem externalClassFieldTheory_mathlibRevision_mismatch :
    externalClassFieldTheoryMathlibRevision ≠ localLakeMathlibRevision := by
  native_decide

/--
External `kbuzzard/ClassFieldTheory` uses the same Lean toolchain as this
repository at the audited commit, so the known blocker is the Lake/mathlib
closure rather than an immediate Lean-version mismatch.
-/
def externalClassFieldTheoryLeanToolchain : String :=
  "leanprover/lean4:v4.29.0"

/--
Repo-local pin decision for the audited external project.

`integration_blocked_pending_port_or_dry_run` means this file found a concrete
Lake-closure blocker and did not add the external package to the shared
`lakefile.lean` or `lake-manifest.json`.  A future serial integrator must either
port the external source to `localLakeMathlibRevision` and validate an import, or
prove in a disposable integration branch that Lake resolves the package against
this repository's pinned mathlib and the relevant imports compile.
-/
def externalClassFieldTheoryLakeClosureDecision : String :=
  "integration_blocked_pending_port_or_dry_run"

/-- Concrete blockers for pinning the audited external project as completed work. -/
def externalClassFieldTheoryPinBlockers : List String := [
  "external manifest mathlib revision differs from the local direct mathlib pin",
  "shared lakefile.lean and lake-manifest.json were outside this child write scope",
  "no repo-local import of ClassFieldTheory was added to this Lake closure",
  "no disposable Lake integration dry-run result is recorded in this child"
]

/-- Status labels for the C004 idele-class-group API design note. -/
inductive C004ApiStatus where
  /-- The row is backed by concrete declarations in this repository's Lean artifact. -/
  | checkedRepoLocal
  /-- The row is represented by a checked boundary object, but its deeper API is not proved. -/
  | checkedBoundary
  /-- The row remains future formalization work and is not a completed theorem claim. -/
  | formalizationDebt
  deriving DecidableEq, Repr

/-- One row of the C004 idele-class-group API design note. -/
structure C004IdeleClassApiDesignRow where
  component : String
  repoLocalSurface : String
  status : C004ApiStatus
  nextIntegrationBoundary : String
  deriving Repr

/--
Integration-ready design note for the idele class group API requested by
`S1-M-077-C004`.

The checked rows deliberately separate the concrete repo-local object model from
future norm-map work.  In particular, additive principal adeles from
`NumberField.AdeleRing.principalSubgroup` are not identified with the
multiplicative principal idele subgroup `PrincipalIdeles K`.
-/
def c004IdeleClassApiDesignRows : List C004IdeleClassApiDesignRow := [
  {
    component := "multiplicative ideles",
    repoLocalSurface := "MultiplicativeIdeles K := Units (NumberFieldAdeleRing K)",
    status := C004ApiStatus.checkedRepoLocal,
    nextIntegrationBoundary :=
      "audit whether adele-ring units supply the intended restricted-product topology"
  },
  {
    component := "principal ideles",
    repoLocalSurface :=
      "principalIdeleHom K : Kˣ →* MultiplicativeIdeles K; PrincipalIdeles K",
    status := C004ApiStatus.checkedRepoLocal,
    nextIntegrationBoundary :=
      "keep separate from additive NumberField.AdeleRing.principalSubgroup"
  },
  {
    component := "idele class quotient topology",
    repoLocalSurface :=
      "IdeleClassGroup K; ideleClassQuotientHom K; quotient-group topology instance",
    status := C004ApiStatus.checkedRepoLocal,
    nextIntegrationBoundary :=
      "prove the quotient map has the exact continuity/open-map properties needed by reciprocity"
  },
  {
    component := "open finite-index subgroups",
    repoLocalSurface := "OpenFiniteIndexIdeleClassSubgroup K",
    status := C004ApiStatus.checkedBoundary,
    nextIntegrationBoundary :=
      "connect these subgroups to finite abelian extensions via the Artin map kernel theorem"
  },
  {
    component := "norm maps",
    repoLocalSurface := "no repo-local idele-class norm map yet",
    status := C004ApiStatus.formalizationDebt,
    nextIntegrationBoundary :=
      "define or import norm maps C_L -> C_K for finite extensions L/K and prove principal-idele compatibility"
  }
]

/-- The C004 API design note has exactly the five requested components. -/
theorem c004IdeleClassApiDesignRows_length :
    c004IdeleClassApiDesignRows.length = 5 := by
  native_decide

/--
The C004 design note intentionally leaves norm maps as formalization debt rather
than completed repo-local API.
-/
def c004NormMapsGate : C004ApiStatus := C004ApiStatus.formalizationDebt

/-- Status labels for the C005 adele-to-idele bridge task. -/
inductive C005BridgeStatus where
  /-- The item is backed by a concrete declaration or theorem in this file. -/
  | checkedRepoLocal
  /-- The item is a checked boundary statement, not a completed CFT theorem. -/
  | checkedBoundary
  /-- The item remains future formalization work. -/
  | formalizationDebt
  deriving DecidableEq, Repr

/-- One row of the C005 bridge plan from additive adeles to multiplicative ideles. -/
structure C005AdeleIdeleBridgeRow where
  component : String
  additiveAdeleSurface : String
  multiplicativeIdeleSurface : String
  status : C005BridgeStatus
  guardrail : String
  deriving Repr

/--
The diagonal map into multiplicative ideles is induced by the diagonal algebra
map into mathlib's adele ring.

This is the checked bridge from `NumberField.AdeleRing` to the repo-local
`MultiplicativeIdeles` object.  It does not identify the additive principal
adele subgroup with a multiplicative quotient.
-/
theorem principalIdeleHom_val
    (K : Type uK) [Field K] [NumberField K] (x : Kˣ) :
    ((principalIdeleHom K x : MultiplicativeIdeles K) : NumberFieldAdeleRing K) =
      algebraMap K (NumberFieldAdeleRing K) (x : K) := by
  rfl

/-- Membership in `PrincipalIdeles` is exactly membership in the diagonal image of `Kˣ`. -/
theorem mem_principalIdeles_iff
    (K : Type uK) [Field K] [NumberField K] (x : MultiplicativeIdeles K) :
    x ∈ PrincipalIdeles K ↔ ∃ y : Kˣ, principalIdeleHom K y = x := by
  rfl

/--
Integration-ready C005 bridge table.

The table separates mathlib's additive adele subgroup
`NumberField.AdeleRing.principalSubgroup` from this file's multiplicative
principal idele subgroup `PrincipalIdeles K`.  Any future public task should
preserve this distinction when replacing the current unit-group model by a
full restricted-product idele API.
-/
def c005AdeleIdeleBridgeRows : List C005AdeleIdeleBridgeRow := [
  {
    component := "adele substrate",
    additiveAdeleSurface := "NumberFieldAdeleRing K := NumberField.AdeleRing (O K) K",
    multiplicativeIdeleSurface := "MultiplicativeIdeles K := Units (NumberFieldAdeleRing K)",
    status := C005BridgeStatus.checkedRepoLocal,
    guardrail :=
      "the unit group supplies a multiplicative object over the adele ring, not a global reciprocity map"
  },
  {
    component := "diagonal embedding",
    additiveAdeleSurface := "algebraMap K (NumberFieldAdeleRing K)",
    multiplicativeIdeleSurface := "principalIdeleHom K : K^x ->* MultiplicativeIdeles K",
    status := C005BridgeStatus.checkedRepoLocal,
    guardrail :=
      "principalIdeleHom_val records that the multiplicative map is induced by the additive-ring diagonal map"
  },
  {
    component := "principal additive adeles",
    additiveAdeleSurface :=
      "NumberField.AdeleRing.principalSubgroup R K = (algebraMap K _).range.toAddSubgroup",
    multiplicativeIdeleSurface := "no identification with PrincipalIdeles K",
    status := C005BridgeStatus.checkedBoundary,
    guardrail :=
      "do not use an AddSubgroup of the adele ring as the subgroup in the idele-class quotient"
  },
  {
    component := "principal multiplicative ideles",
    additiveAdeleSurface := "uses the same diagonal algebra map only after passing to K^x and Units",
    multiplicativeIdeleSurface :=
      "PrincipalIdeles K := MonoidHom.range (principalIdeleHom K)",
    status := C005BridgeStatus.checkedRepoLocal,
    guardrail :=
      "mem_principalIdeles_iff keeps the quotient subgroup multiplicative"
  },
  {
    component := "idele class quotient",
    additiveAdeleSurface := "no additive adele quotient claimed",
    multiplicativeIdeleSurface := "IdeleClassGroup K := MultiplicativeIdeles K / PrincipalIdeles K",
    status := C005BridgeStatus.checkedRepoLocal,
    guardrail :=
      "the quotient is multiplicative ideles modulo principal ideles"
  },
  {
    component := "restricted-product topology",
    additiveAdeleSurface := "mathlib NumberField.AdeleRing topology",
    multiplicativeIdeleSurface := "future idele topology audit for Units (NumberFieldAdeleRing K)",
    status := C005BridgeStatus.formalizationDebt,
    guardrail :=
      "prove or import the intended restricted-product topology before using topological CFT terminal statements"
  }
]

/-- The C005 bridge table has the six requested additive/multiplicative boundary rows. -/
theorem c005AdeleIdeleBridgeRows_length :
    c005AdeleIdeleBridgeRows.length = 6 := by
  native_decide

/--
The C005 bridge intentionally leaves the restricted-product topology audit as
formalization debt; it is not a completed global CFT theorem.
-/
def c005RestrictedProductTopologyGate : C005BridgeStatus :=
  C005BridgeStatus.formalizationDebt

/-- Status labels for the C006 global-CFT package split task. -/
inductive C006PackageStatus where
  /-- The row is a checked planning boundary backed by declarations in this file. -/
  | checkedBoundary
  /-- The row remains future formalization work, not a completed theorem claim. -/
  | formalizationDebt
  deriving DecidableEq, Repr

/-- One top-level proof package for splitting global class field theory. -/
structure C006GlobalCftPackageRow where
  packageId : String
  packageName : String
  responsibility : String
  upstreamInputs : String
  downstreamInterface : String
  status : C006PackageStatus
  independentLeafLedger : String
  deriving Repr

/--
C006 package split for global class field theory.

The four rows are an integration-ready theorem-tree boundary only.  They do not
claim global Artin reciprocity or the global CFT correspondence has been proved
in this repository.
-/
def c006GlobalCftPackageSplit : List C006GlobalCftPackageRow := [
  {
    packageId := "CFT-P01-local-reciprocity",
    packageName := "local reciprocity",
    responsibility :=
      "construct or import local Artin reciprocity for each completion K_v",
    upstreamInputs :=
      "local field objects, finite abelian local extensions, multiplicative local groups",
    downstreamInterface :=
      "local reciprocity maps with norm-kernel, continuity, and functoriality facts",
    status := C006PackageStatus.formalizationDebt,
    independentLeafLedger := "CFT-L001 through CFT-L005, each budgeted <=100"
  },
  {
    packageId := "CFT-P02-local-global-product",
    packageName := "local-global product compatibility",
    responsibility :=
      "compare the product of local reciprocity maps with the global idele-class quotient",
    upstreamInputs :=
      "MultiplicativeIdeles K, PrincipalIdeles K, local reciprocity maps",
    downstreamInterface :=
      "global Artin map boundary and product-formula compatibility for principal ideles",
    status := C006PackageStatus.formalizationDebt,
    independentLeafLedger := "CFT-L006 through CFT-L010, each budgeted <=100"
  },
  {
    packageId := "CFT-P03-existence-theorem",
    packageName := "existence theorem",
    responsibility :=
      "construct the finite abelian extension associated to an open finite-index subgroup",
    upstreamInputs :=
      "OpenFiniteIndexIdeleClassSubgroup K and the global Artin map boundary",
    downstreamInterface :=
      "extension-existence map whose reciprocity kernel is the requested subgroup",
    status := C006PackageStatus.formalizationDebt,
    independentLeafLedger := "CFT-L011 through CFT-L015, each budgeted <=100"
  },
  {
    packageId := "CFT-P04-uniqueness-functoriality",
    packageName := "uniqueness and functoriality",
    responsibility :=
      "prove uniqueness of the classified extension and compatibility under restriction and norm",
    upstreamInputs :=
      "local-global product compatibility and existence-theorem output",
    downstreamInterface :=
      "bijectivity of ClassFieldReciprocityData.reciprocityKernel",
    status := C006PackageStatus.formalizationDebt,
    independentLeafLedger := "CFT-L016 through CFT-L020, each budgeted <=100"
  }
]

/-- The C006 split has exactly the four requested packages. -/
theorem c006GlobalCftPackageSplit_length :
    c006GlobalCftPackageSplit.length = 4 := by
  native_decide

/-- One unchecked future leaf in the C006 local `<=100` ledger. -/
structure C006GlobalCftLeafRow where
  leafId : String
  packageId : String
  statementTarget : String
  machineAnchorBoundary : String
  budgetLimit : Nat
  status : C006PackageStatus
  deriving Repr

/--
C006 independent future leaf ledger.

Each row is intentionally `formalizationDebt`: these are the leaf slots a serial
public-doc integrator can merge into the Stage1 blueprint/todo, not completed
repo-local proofs of global class field theory.
-/
def c006GlobalCftLeafLedger : List C006GlobalCftLeafRow := [
  {
    leafId := "CFT-L001",
    packageId := "CFT-P01-local-reciprocity",
    statementTarget := "select the local field and completion API for every place v of K",
    machineAnchorBoundary := "no terminal local reciprocity theorem imported for all completions",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L002",
    packageId := "CFT-P01-local-reciprocity",
    statementTarget := "define the local multiplicative group and local Artin map target",
    machineAnchorBoundary := "future local reciprocity map, not present in this file",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L003",
    packageId := "CFT-P01-local-reciprocity",
    statementTarget := "prove the local norm-subgroup kernel statement",
    machineAnchorBoundary := "requires imported or newly formalized local CFT",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L004",
    packageId := "CFT-P01-local-reciprocity",
    statementTarget := "prove functoriality of local reciprocity in finite abelian local extensions",
    machineAnchorBoundary := "requires local extension and Galois functoriality API",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L005",
    packageId := "CFT-P01-local-reciprocity",
    statementTarget := "record continuity and open-subgroup compatibility of local reciprocity",
    machineAnchorBoundary := "requires topological local-field reciprocity API",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L006",
    packageId := "CFT-P02-local-global-product",
    statementTarget := "compare the place-indexed product of local multiplicative groups with ideles",
    machineAnchorBoundary := "requires a full restricted-product idele API beyond Units (A_K)",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L007",
    packageId := "CFT-P02-local-global-product",
    statementTarget := "prove principal ideles map trivially under the product of local Artin maps",
    machineAnchorBoundary := "depends on product formula plus local reciprocity normalization",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L008",
    packageId := "CFT-P02-local-global-product",
    statementTarget := "prove finite-support or restricted-product compatibility for local symbols",
    machineAnchorBoundary := "requires restricted-product topology and support lemmas",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L009",
    packageId := "CFT-P02-local-global-product",
    statementTarget := "prove local norm maps assemble to the global idele norm map",
    machineAnchorBoundary := "global idele-class norm maps are still future API",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L010",
    packageId := "CFT-P02-local-global-product",
    statementTarget := "factor the product of local Artin maps through IdeleClassGroup K",
    machineAnchorBoundary := "requires CFT-L007 and quotient-map compatibility",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L011",
    packageId := "CFT-P03-existence-theorem",
    statementTarget := "state the extension existence target for each open finite-index subgroup",
    machineAnchorBoundary := "OpenFiniteIndexIdeleClassSubgroup K is present, construction is not",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L012",
    packageId := "CFT-P03-existence-theorem",
    statementTarget := "construct or import the finite abelian extension attached to a subgroup",
    machineAnchorBoundary := "requires global CFT existence theorem proof or pinned dependency",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L013",
    packageId := "CFT-P03-existence-theorem",
    statementTarget := "prove the constructed extension has the requested reciprocity kernel",
    machineAnchorBoundary := "requires global Artin map and kernel theorem",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L014",
    packageId := "CFT-P03-existence-theorem",
    statementTarget := "connect the construction with conductor or ray-class approximations",
    machineAnchorBoundary := "ray-class and conductor infrastructure not integrated here",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L015",
    packageId := "CFT-P03-existence-theorem",
    statementTarget := "verify open and finite-index conditions are preserved by the construction",
    machineAnchorBoundary := "requires topology and index lemmas for the constructed kernel",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L016",
    packageId := "CFT-P04-uniqueness-functoriality",
    statementTarget := "prove equality of classified extensions from equality of reciprocity kernels",
    machineAnchorBoundary := "requires a concrete extension equivalence notion and CFT uniqueness",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L017",
    packageId := "CFT-P04-uniqueness-functoriality",
    statementTarget := "prove restriction compatibility for towers of finite abelian extensions",
    machineAnchorBoundary := "requires tower functoriality for Artin maps",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L018",
    packageId := "CFT-P04-uniqueness-functoriality",
    statementTarget := "prove norm-subgroup compatibility under finite extensions",
    machineAnchorBoundary := "requires global idele-class norm maps",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L019",
    packageId := "CFT-P04-uniqueness-functoriality",
    statementTarget := "prove naturality of global Artin maps against local reciprocity",
    machineAnchorBoundary := "requires CFT-P01 and CFT-P02 closures",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  },
  {
    leafId := "CFT-L020",
    packageId := "CFT-P04-uniqueness-functoriality",
    statementTarget := "assemble bijectivity of the reciprocity-kernel correspondence",
    machineAnchorBoundary := "terminal wrapper waits on all four packages",
    budgetLimit := 100,
    status := C006PackageStatus.formalizationDebt
  }
]

/-- The C006 split records twenty independent future leaves. -/
theorem c006GlobalCftLeafLedger_length :
    c006GlobalCftLeafLedger.length = 20 := by
  native_decide

/-- Every C006 future leaf is budgeted at most 100 local proof steps. -/
theorem c006GlobalCftLeafLedger_budget_le_100 :
    (c006GlobalCftLeafLedger.map (fun row => row.budgetLimit)).all
      (fun n => decide (n <= 100)) = true := by
  native_decide

/-- The local-reciprocity package has its own five-leaf ledger. -/
theorem c006LocalReciprocityLeafCount :
    (c006GlobalCftLeafLedger.filter
      (fun row => row.packageId == "CFT-P01-local-reciprocity")).length = 5 := by
  native_decide

/-- The local-global product package has its own five-leaf ledger. -/
theorem c006LocalGlobalProductLeafCount :
    (c006GlobalCftLeafLedger.filter
      (fun row => row.packageId == "CFT-P02-local-global-product")).length = 5 := by
  native_decide

/-- The existence-theorem package has its own five-leaf ledger. -/
theorem c006ExistenceTheoremLeafCount :
    (c006GlobalCftLeafLedger.filter
      (fun row => row.packageId == "CFT-P03-existence-theorem")).length = 5 := by
  native_decide

/-- The uniqueness/functoriality package has its own five-leaf ledger. -/
theorem c006UniquenessFunctorialityLeafCount :
    (c006GlobalCftLeafLedger.filter
      (fun row => row.packageId == "CFT-P04-uniqueness-functoriality")).length = 5 := by
  native_decide

/--
C006 completion gate.

This is deliberately false: the child task creates a checked split/ledger
surface, but no terminal global class field theory theorem or pinned external
proof closure has been integrated.
-/
def c006RepoLocalCompletionGate : Bool := false

/-- C006 must not be treated as a completed global CFT proof. -/
theorem c006RepoLocalCompletionGate_eq_false :
    c006RepoLocalCompletionGate = false := rfl

/-- Status labels for the C007 terminal-wrapper gate. -/
inductive C007TerminalWrapperGateStatus where
  /-- The row is a checked boundary condition in this repository's Lean artifact. -/
  | checkedBoundary
  /-- The row remains future formalization work before any terminal wrapper can exist. -/
  | formalizationDebt
  /-- The row is blocked until an external dependency is pinned/imported/checked. -/
  | integrationBlocked
  deriving DecidableEq, Repr

/-- One C007 gate row for deciding when a terminal global-CFT wrapper may be added. -/
structure C007TerminalWrapperGateRow where
  gate : String
  currentRepoLocalEvidence : String
  requiredBeforeWrapper : String
  status : C007TerminalWrapperGateStatus
  deriving Repr

/--
C007 terminal-wrapper gate for global class field theory.

This table is intentionally a blocker surface, not a wrapper theorem.  It
records that the current repository has checked statement-shape and idele-class
objects, but no terminal global Artin reciprocity theorem from mathlib and no
pinned external dependency providing such a theorem.
-/
def c007TerminalWrapperGateRows : List C007TerminalWrapperGateRow := [
  {
    gate := "statement shape",
    currentRepoLocalEvidence :=
      "StatementShape K data := Function.Bijective data.reciprocityKernel",
    requiredBeforeWrapper :=
      "replace ClassFieldReciprocityData with a concrete global Artin map and extension classifier",
    status := C007TerminalWrapperGateStatus.checkedBoundary
  },
  {
    gate := "mathlib terminal theorem",
    currentRepoLocalEvidence :=
      "absentTerminalSearchTerms records no local mathlib terminal global CFT theorem",
    requiredBeforeWrapper :=
      "import a mathlib theorem proving global Artin reciprocity or the finite-abelian-extension correspondence",
    status := C007TerminalWrapperGateStatus.formalizationDebt
  },
  {
    gate := "external terminal theorem",
    currentRepoLocalEvidence :=
      "externalClassFieldTheoryTerminalGlobalTheoremNames = []",
    requiredBeforeWrapper :=
      "find an exact external Lean declaration for global Artin reciprocity or global CFT",
    status := C007TerminalWrapperGateStatus.formalizationDebt
  },
  {
    gate := "pinned dependency closure",
    currentRepoLocalEvidence :=
      "externalClassFieldTheoryLakeClosureDecision = integration_blocked_pending_port_or_dry_run",
    requiredBeforeWrapper :=
      "pin/import/check the external dependency, or record a concrete blocker before any completion claim",
    status := C007TerminalWrapperGateStatus.integrationBlocked
  },
  {
    gate := "repo-local validation",
    currentRepoLocalEvidence :=
      "this file can be checked as a Stage1 boundary artifact",
    requiredBeforeWrapper :=
      "run lake env lean on the wrapper file after the terminal dependency or mathlib theorem is present",
    status := C007TerminalWrapperGateStatus.checkedBoundary
  }
]

/-- The C007 terminal-wrapper gate table has the five required decision rows. -/
theorem c007TerminalWrapperGateRows_length :
    c007TerminalWrapperGateRows.length = 5 := by
  native_decide

/-- No terminal global-CFT theorem name is currently available from the audited external project. -/
theorem c007ExternalTerminalGlobalTheoremNames_empty :
    externalClassFieldTheoryTerminalGlobalTheoremNames = [] := rfl

/--
C007 terminal-wrapper permission.

This is deliberately false in the current repository state.  A future patch may
turn this into a real wrapper theorem only after a mathlib terminal theorem or a
pinned external dependency has been imported and `lake env lean` validates the
owned Lean file.
-/
def c007TerminalWrapperAllowed : Bool := false

/-- C007 must not be treated as a completed terminal global CFT wrapper. -/
theorem c007TerminalWrapperAllowed_eq_false :
    c007TerminalWrapperAllowed = false := rfl

end AwesomeTheorems.Stage1.S1_M_077
