import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.Calculus.LocalExtr.Basic
import Mathlib.Analysis.InnerProductSpace.l2Space

/-!
# S1-M-165 / THM-M-1272: Fountain theorem

This Stage1 artifact records a conservative Lean 4 statement-shape boundary for
the variational Fountain theorem, a multiplicity theorem for even `C^1`
functionals on an infinite-dimensional Hilbert/Banach-type space.

The pinned mathlib snapshot has Frechet derivatives, `ContDiff`, local extremum
critical-point wrappers, Hilbert bases, orthogonal decompositions, and Hilbert
sum infrastructure.  This audit did not find a terminal Fountain theorem,
Palais-Smale compactness package, or minimax critical-point theorem in the local
dependency closure.

The declarations below therefore avoid proof placeholders and false completion
claims.  They normalize the expected critical-point conclusion and keep the hard
compactness/minimax geometry as explicit data.
-/

noncomputable section

open Filter
open scoped Topology

namespace AwesomeTheorems.Stage1.S1_M_165

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- A point is critical for a real functional when its Frechet derivative vanishes. -/
def CriticalPoint (Phi : E -> ℝ) (x : E) : Prop :=
  fderiv ℝ Phi x = 0

/-- A real number is a critical value of a functional. -/
def CriticalValue (Phi : E -> ℝ) (c : ℝ) : Prop :=
  ∃ x : E, CriticalPoint Phi x ∧ Phi x = c

/-- The critical values are unbounded above. -/
def CriticalValuesUnboundedAbove (Phi : E -> ℝ) : Prop :=
  ∀ A : ℝ, ∃ c : ℝ, CriticalValue Phi c ∧ A ≤ c

/-- Frechet-derivative residual measured by the continuous-linear-map norm. -/
def FrechetResidual
    {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
    (Phi : X -> ℝ) (x : X) : ℝ :=
  ‖fderiv ℝ Phi x‖

/-- Concrete topological compactness target: a sequence has a convergent subsequence. -/
def HasConvergentSubsequence
    {X : Type u} [TopologicalSpace X] (u : ℕ -> X) : Prop :=
  ∃ x : X, ∃ phi : ℕ -> ℕ,
    StrictMono phi ∧ Tendsto (fun n : ℕ => u (phi n)) atTop (𝓝 x)

/--
A Palais-Smale sequence at level `c`.

This is the standard `PS_c` sequence shape: functional values converge to the
selected level and Frechet derivative norms converge to zero.
-/
structure PalaisSmaleSequence
    {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
    (Phi : X -> ℝ) (c : ℝ) (u : ℕ -> X) : Prop where
  values_tendsto : Tendsto (fun n : ℕ => Phi (u n)) atTop (𝓝 c)
  derivative_norm_tendsto :
    Tendsto (fun n : ℕ => FrechetResidual Phi (u n)) atTop (𝓝 (0 : ℝ))

/-- Palais-Smale compactness at one fixed critical/minimax level. -/
def PalaisSmaleCompactnessAt
    {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
    (Phi : X -> ℝ) (c : ℝ) : Prop :=
  ∀ u : ℕ -> X, PalaisSmaleSequence Phi c u -> HasConvergentSubsequence u

/-- Full Palais-Smale compactness, quantified over every real level. -/
def FullPalaisSmaleCompactness
    {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
    (Phi : X -> ℝ) : Prop :=
  ∀ c : ℝ, PalaisSmaleCompactnessAt Phi c

/-- Bounded functional values along a sequence, expressed without extra APIs. -/
def FunctionalValuesBounded
    {X : Type u} [NormedAddCommGroup X] (Phi : X -> ℝ) (u : ℕ -> X) : Prop :=
  ∃ R : ℝ, ∀ n : ℕ, ‖Phi (u n)‖ ≤ R

/--
A Cerami sequence with bounded functional values.

The derivative condition is the usual `(1 + ‖u_n‖) * ‖Phi'(u_n)‖ -> 0`
variant, stated with the Frechet derivative norm.
-/
structure CeramiSequence
    {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
    (Phi : X -> ℝ) (u : ℕ -> X) : Prop where
  values_bounded : FunctionalValuesBounded Phi u
  weighted_derivative_norm_tendsto :
    Tendsto
      (fun n : ℕ => (1 + ‖u n‖) * FrechetResidual Phi (u n))
      atTop (𝓝 (0 : ℝ))

/-- Cerami compactness for all bounded-energy Cerami sequences. -/
def CeramiCompactness
    {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
    (Phi : X -> ℝ) : Prop :=
  ∀ u : ℕ -> X, CeramiSequence Phi u -> HasConvergentSubsequence u

/-- Compactness variants relevant to public Fountain-theorem statement selection. -/
inductive CompactnessRequirement where
  | palaisSmaleAtLevels
  | fullPalaisSmale
  | cerami
deriving DecidableEq, Repr

/--
Compactness input selected for the classical Fountain theorem target.

The public parent target needs `PS_c` at the minimax levels generated by the
Fountain construction.  Full global `PS` is stronger than this target requires,
and Cerami compactness belongs to a generalized/Cerami branch rather than the
selected parent statement.
-/
structure ClassicalFountainCompactness (Phi : E -> ℝ) : Type u where
  minimaxLevel : ℕ -> ℝ
  palaisSmaleAt_minimaxLevel :
    ∀ n : ℕ, PalaisSmaleCompactnessAt Phi (minimaxLevel n)

/-- Machine-checkable compactness decision for `S1-M-165-C004`. -/
def selectedCompactnessRequirement : CompactnessRequirement :=
  .palaisSmaleAtLevels

/-- The selected compactness requirement is `PS_c` at the minimax levels. -/
theorem selectedCompactnessRequirement_eq_psAtLevels :
    selectedCompactnessRequirement = CompactnessRequirement.palaisSmaleAtLevels :=
  rfl

/-- Public-backfill rationale for the compactness decision. -/
def selectedCompactnessRequirementRationale : String :=
  "For the selected classical Bartsch-Willem Fountain theorem target, use " ++
  "Palais-Smale compactness at the minimax levels (`PS_c`).  Do not require " ++
  "full global `PS` for every level in the parent statement, and do not switch " ++
  "the parent to Cerami compactness; Cerami belongs to a generalized/Cerami " ++
  "branch unless a later primary-source audit changes the selected variant."

/--
Abstract Fountain-theorem geometry for an even variational functional.

The usual theorem uses a decomposition by finite-dimensional subspaces and their
closed complements, together with lower barriers on large spheres and escape to
negative values on finite-dimensional parts.  These fields are proposition-valued
because no terminal mathlib minimax/Palais-Smale proof package was found.
-/
structure FountainGeometry (Phi : E -> ℝ) : Type u where
  finiteCore : ℕ -> Submodule ℝ E
  finiteCore_finiteDimensional : ∀ n : ℕ, FiniteDimensional ℝ (finiteCore n)
  complement : ℕ -> Submodule ℝ E
  highSphereRadius : ℕ -> ℝ
  lowBallRadius : ℕ -> ℝ
  highSphereBarrier : Prop
  highSphereBarrier_holds : highSphereBarrier
  finiteDimensionalEscape : Prop
  finiteDimensionalEscape_holds : finiteDimensionalEscape
  splittingCompatibility : Prop
  splittingCompatibility_holds : splittingCompatibility

/--
Hypothesis package for a Fountain theorem statement.

The hard formalization boundary is explicit: the Palais-Smale compactness and
minimax construction are inputs here, not proved by this Stage1 artifact.
-/
structure FountainHypotheses (Phi : E -> ℝ) : Type u where
  c1 : ContDiff ℝ 1 Phi
  even : ∀ x : E, Phi (-x) = Phi x
  geometry : FountainGeometry Phi
  palaisSmaleCompactness : Prop
  palaisSmaleCompactness_holds : palaisSmaleCompactness
  minimaxConstruction : Prop
  minimaxConstruction_holds : minimaxConstruction

/--
Conclusion package for the Fountain theorem: a sequence of critical points whose
critical values tend upward without a finite upper bound.
-/
structure FountainConclusion (Phi : E -> ℝ) : Type u where
  criticalPoint : ℕ -> E
  critical : ∀ n : ℕ, CriticalPoint Phi (criticalPoint n)
  criticalValuesUnbounded : CriticalValuesUnboundedAbove Phi

/--
Normalized Stage1 statement shape for the Fountain theorem over a fixed Hilbert
space and functional.

If the Fountain geometry, Palais-Smale compactness, and minimax package have
been supplied, then the functional has unboundedly many critical values.  This
is a statement boundary, not a terminal proof of the Fountain theorem.
-/
def StatementShape
    (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (Phi : E -> ℝ) : Prop :=
  FountainHypotheses Phi -> Nonempty (FountainConclusion Phi)

/-- The statement shape unfolds to the normalized hypothesis/conclusion package. -/
theorem statementShape_iff
    (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (Phi : E -> ℝ) :
    StatementShape E Phi ↔
      (FountainHypotheses Phi -> Nonempty (FountainConclusion Phi)) :=
  Iff.rfl

/-- Low-risk introduction wrapper for the normalized statement shape. -/
theorem statementShape_intro
    (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (Phi : E -> ℝ)
    (h : FountainHypotheses Phi -> Nonempty (FountainConclusion Phi)) :
    StatementShape E Phi :=
  h

/-- A conclusion package exposes a concrete critical point at every index. -/
theorem FountainConclusion.critical_at
    {Phi : E -> ℝ} (C : FountainConclusion Phi) (n : ℕ) :
    CriticalPoint Phi (C.criticalPoint n) :=
  C.critical n

/-- A conclusion package exposes the indexed critical value. -/
theorem FountainConclusion.critical_value_at
    {Phi : E -> ℝ} (C : FountainConclusion Phi) (n : ℕ) :
    CriticalValue Phi (Phi (C.criticalPoint n)) :=
  ⟨C.criticalPoint n, C.critical n, rfl⟩

/-- A conclusion package exposes the unboundedness of critical values. -/
theorem FountainConclusion.unbounded_critical_values
    {Phi : E -> ℝ} (C : FountainConclusion Phi) :
    CriticalValuesUnboundedAbove Phi :=
  C.criticalValuesUnbounded

/-- Checked mathlib anchor: a local minimum of a real functional is critical. -/
theorem localMin_criticalPoint_anchor
    {Phi : E -> ℝ} {x : E} (h : IsLocalMin Phi x) :
    CriticalPoint Phi x :=
  h.fderiv_eq_zero

/-- Checked mathlib anchor: `C^1` implies continuity. -/
theorem contDiff_one_continuous_anchor
    {Phi : E -> ℝ} (h : ContDiff ℝ 1 Phi) :
    Continuous Phi :=
  h.continuous

/-- Checked mathlib anchor: `C^1` implies Frechet differentiability. -/
theorem contDiff_one_differentiable_anchor
    {Phi : E -> ℝ} (h : ContDiff ℝ 1 Phi) :
    Differentiable ℝ Phi :=
  h.differentiable_one

/-- Checked mathlib anchor: every real Hilbert space admits a Hilbert basis. -/
theorem exists_hilbertBasis_anchor
    (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] :
    ∃ (w : Set E) (b : HilbertBasis w ℝ E), ⇑b = ((↑) : w -> E) :=
  exists_hilbertBasis ℝ E

/-- mathlib modules checked while locating repo-local anchors for this slot. -/
def mathlibAnchorModules : List String := [
  "Mathlib.Analysis.Calculus.ContDiff.Basic",
  "Mathlib.Analysis.Calculus.LocalExtr.Basic",
  "Mathlib.Analysis.InnerProductSpace.l2Space",
  "Mathlib.Analysis.InnerProductSpace.Projection",
  "Mathlib.Topology.Algebra.Module.FiniteDimension",
  "Mathlib.Analysis.FunctionalSpaces.SobolevInequality",
  "Mathlib.Analysis.Distribution.Distribution",
  "Mathlib.Analysis.Distribution.TemperedDistribution"
]

/-- Checked local names used as anchors for the statement-shape boundary. -/
def mathlibAnchorNames : List String := [
  "fderiv",
  "ContDiff",
  "ContDiff.continuous",
  "ContDiff.differentiable_one",
  "IsLocalMin.fderiv_eq_zero",
  "HilbertBasis",
  "exists_hilbertBasis",
  "IsHilbertSum",
  "Orthonormal.isHilbertSum",
  "Submodule.isHilbertSumOrthogonal",
  "FiniteDimensional"
]

/--
Integration-ready public mathlib anchor table for the `S1-M-165` blueprint row.

Each row is an anchor already available in the repo-local Lean dependency
closure.  These anchors support the statement-shape boundary only; none is a
terminal Fountain theorem, Palais-Smale compactness theorem, or minimax theorem.
-/
structure PublicMathlibAnchorRow where
  name : String
  module : String
  role : String
  repoLocalStatus : String
deriving Repr

/-- Requested public anchor table for the Fountain theorem Stage1 backfill. -/
def publicMathlibAnchorTable : List PublicMathlibAnchorRow := [
  {
    name := "ContDiff",
    module := "Mathlib.Analysis.Calculus.ContDiff.Basic",
    role := "C^1 smoothness hypothesis for the even variational functional",
    repoLocalStatus := "imported and #check-backed"
  },
  {
    name := "fderiv",
    module := "Mathlib.Analysis.Calculus.FDeriv.Basic",
    role := "Frechet derivative used to define critical points by vanishing derivative",
    repoLocalStatus := "available through current imports and #check-backed"
  },
  {
    name := "IsLocalMin.fderiv_eq_zero",
    module := "Mathlib.Analysis.Calculus.LocalExtr.Basic",
    role := "local-minimum-to-critical-point calculus anchor",
    repoLocalStatus := "imported and wrapped by localMin_criticalPoint_anchor"
  },
  {
    name := "HilbertBasis",
    module := "Mathlib.Analysis.InnerProductSpace.l2Space",
    role := "Hilbert-space basis anchor for countable/orthogonal decomposition models",
    repoLocalStatus := "imported and #check-backed"
  },
  {
    name := "exists_hilbertBasis",
    module := "Mathlib.Analysis.InnerProductSpace.l2Space",
    role := "existence anchor for choosing a Hilbert basis in complete real Hilbert spaces",
    repoLocalStatus := "imported and wrapped by exists_hilbertBasis_anchor"
  },
  {
    name := "IsHilbertSum",
    module := "Mathlib.Analysis.InnerProductSpace.l2Space",
    role := "orthogonal Hilbert-sum decomposition anchor for splitting models",
    repoLocalStatus := "imported and #check-backed"
  },
  {
    name := "FiniteDimensional",
    module := "Mathlib.Topology.Algebra.Module.FiniteDimension",
    role := "finite-dimensional core subspace hypothesis in the Fountain geometry package",
    repoLocalStatus := "available through current imports and used in FountainGeometry"
  }
]

/--
Search terms that did not locate a terminal Fountain theorem or Palais-Smale
critical-point theorem in pinned mathlib.
-/
def absentTerminalSearchTerms : List String := [
  "Fountain",
  "fountain theorem",
  "Palais",
  "Smale",
  "Palais-Smale",
  "CriticalPoint",
  "critical point theorem",
  "MountainPass",
  "mountain pass",
  "minimax"
]

/-! ## Variant decision for child task S1-M-165-C003 -/

/--
Candidate variants named by the public Stage1 backfill task.

This is a decision record only.  Selecting one constructor does not prove that
variant of the Fountain theorem.
-/
inductive FountainVariant where
  | classical
  | dual
  | generalized
  | pdeInstantiated
deriving DecidableEq, Repr

/--
Selected public blueprint target: the classical Bartsch-Willem Fountain theorem.

The existing statement shape already matches this choice: an even `C^1`
functional on a real Hilbert-space model, Fountain geometry, Palais-Smale-style
compactness, and a conclusion by critical values unbounded above.
-/
def selectedFountainVariant : FountainVariant :=
  .classical

/-- The selected Fountain variant is the classical variant. -/
theorem selectedFountainVariant_eq_classical :
    selectedFountainVariant = FountainVariant.classical :=
  rfl

/--
Human-readable rationale for the variant decision that should be merged into
the public blueprint by an integrator.
-/
def selectedFountainVariantRationale : String :=
  "Choose the classical Bartsch-Willem Fountain theorem as the public S1-M-165 " ++
  "target: even C^1 functional, Hilbert/Banach decomposition into finite cores " ++
  "and tails, PS_c-style compactness at the minimax levels, and critical values " ++
  "unbounded above.  Do not use the dual Fountain theorem, a generalized/Cerami " ++
  "variant, or a PDE-instantiated theorem as the parent statement; those may be " ++
  "kept as later branch tasks only."

/-- Non-selected variants and the repo-local reason each remains out of scope. -/
def nonSelectedFountainVariantNotes : List String := [
  "dual: not selected because it targets the dual geometry and typically negative critical levels accumulating at zero, unlike the current unbounded-above conclusion package",
  "generalized: not selected until a concrete generalized or Cerami compactness source statement is pinned and checked",
  "pdeInstantiated: not selected for the parent theorem because PDE energies, weak formulations, boundary conditions, and regularity bridges are application branches"
]

/-! ## Decomposition-model decision for child task S1-M-165-C005 -/

/--
Candidate decomposition models named by the public Stage1 backfill task.

This is a decision record only.  Selecting one constructor does not construct
the full Fountain minimax decomposition.
-/
inductive FountainDecompositionModel where
  | hilbertBasisFiniteSpans
  | orthogonalSubmodules
  | quotientTails
  | abstractClosedComplements
deriving DecidableEq, Repr

/--
Selected public blueprint model: finite-dimensional cores with orthogonal tail
submodules.

This matches the current `FountainGeometry` fields (`finiteCore`,
`complement`) and the available mathlib anchors `FiniteDimensional`,
`IsHilbertSum`, and `Submodule.isHilbertSumOrthogonal`.
-/
def selectedFountainDecompositionModel : FountainDecompositionModel :=
  .orthogonalSubmodules

/-- The selected Fountain decomposition model is orthogonal submodules. -/
theorem selectedFountainDecompositionModel_eq_orthogonalSubmodules :
    selectedFountainDecompositionModel =
      FountainDecompositionModel.orthogonalSubmodules :=
  rfl

/--
Concrete mathlib-backed anchor for the selected two-piece orthogonal split.

For a complete submodule `K` of a complete Hilbert space, mathlib supplies the
Hilbert-sum decomposition of `K` and its orthogonal complement `Kᗮ`.
-/
def OrthogonalPairHilbertSum
    (K : Submodule ℝ E) [CompleteSpace E] [CompleteSpace K] : Prop :=
  IsHilbertSum ℝ (fun b : Bool => ↥(cond b K Kᗮ))
    fun b => (cond b K Kᗮ).subtypeₗᵢ

/-- Checked anchor: a complete submodule and its orthogonal complement form a Hilbert sum. -/
theorem orthogonalPairHilbertSum_anchor
    (K : Submodule ℝ E) [CompleteSpace E] [CompleteSpace K] :
    OrthogonalPairHilbertSum K :=
  Submodule.isHilbertSumOrthogonal K

/-- Public-backfill rationale for the decomposition-model decision. -/
def selectedFountainDecompositionModelRationale : String :=
  "Choose the orthogonal-submodules model for the public Fountain proof tree: " ++
  "finite-dimensional core submodules Y_n with orthogonal tail submodules Z_n. " ++
  "This is the strongest safe repo-local choice because the current Lean " ++
  "artifact already uses submodules and finite-dimensional cores, while " ++
  "mathlib provides `IsHilbertSum` and `Submodule.isHilbertSumOrthogonal` as " ++
  "checked anchors.  Hilbert-basis finite spans can later implement the cores " ++
  "after an enumeration/countability choice is fixed, but should not be the " ++
  "public root model yet.  Quotient tails and abstract closed complements are " ++
  "less aligned with the available Hilbert-space projection/splitting APIs and " ++
  "would add avoidable quotient or complement-selection debt."

/-- Non-selected decomposition models and the repo-local reason each stays out of scope. -/
def nonSelectedFountainDecompositionModelNotes : List String := [
  "hilbertBasisFiniteSpans: useful as a later implementation of Y_n once a basis enumeration is fixed, but too concrete for the public root model in this pass",
  "quotientTails: not selected because quotient topology and quotient-norm plumbing would be extra formalization debt for the Fountain geometry",
  "abstractClosedComplements: not selected because it is weaker than the Hilbert-space orthogonal projection and Hilbert-sum APIs already available in mathlib"
]

/-! ## Minimax/genus proof-leaf split for child task S1-M-165-C006 -/

/--
Proof packages needed by the classical Fountain minimax/genus construction.

These package names are budgeting markers only. They do not assert that the
corresponding minimax or genus lemmas are already formalized.
-/
inductive MinimaxGenusPackage where
  | admissibleSymmetry
  | genusInfrastructure
  | minimaxLevels
  | deformationAndCompactness
  | criticalExtraction
  | unboundedMultiplicity
deriving DecidableEq, Repr

/--
A machine-checkable budget row for a future minimax/genus proof leaf.

The `withinBudget` field enforces the M0387 local requirement that each future
leaf have an explicit proof-step budget bounded by `100`.
-/
structure MinimaxGenusLeafBudget where
  id : String
  package : MinimaxGenusPackage
  description : String
  budget : Nat
  withinBudget : budget <= 100
  status : String

/-- Every budget row carries its own checked `<= 100` bound. -/
theorem MinimaxGenusLeafBudget.budget_le_100
    (leaf : MinimaxGenusLeafBudget) : leaf.budget <= 100 :=
  leaf.withinBudget

/--
Integration-ready minimax/genus leaf ledger.

Every row is intentionally marked `unchecked_formalization_debt`: this Stage1
artifact has split the construction into bounded leaves, but it has not proved
the genus theory, deformation lemma, minimax critical-value theorem, or
unboundedness result.
-/
def minimaxGenusLeafBudgetLedger : List MinimaxGenusLeafBudget := [
  {
    id := "MG001_even_symmetric_action",
    package := .admissibleSymmetry,
    description := "Encode the Z2 symmetry from evenness of Phi and define symmetric subsets/maps for admissible classes.",
    budget := 40,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG002_admissible_class_boundary",
    package := .admissibleSymmetry,
    description := "Define the admissible deformation class preserving the finite-dimensional boundary data used by the Fountain construction.",
    budget := 65,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG003_genus_definition",
    package := .genusInfrastructure,
    description := "Choose and formalize the Krasnoselskii-genus predicate for closed symmetric subsets, or pin a mathlib-compatible replacement.",
    budget := 75,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG004_genus_monotonicity",
    package := .genusInfrastructure,
    description := "Prove genus monotonicity under odd continuous maps and inclusions for the selected genus model.",
    budget := 80,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG005_genus_finite_core_lower_bound",
    package := .genusInfrastructure,
    description := "Prove the genus lower bound for finite-dimensional core spheres used to force the nth minimax class.",
    budget := 90,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG006_minimax_level_definition",
    package := .minimaxLevels,
    description := "Define the Fountain minimax levels over admissible symmetric classes and connect them to ClassicalFountainCompactness.minimaxLevel.",
    budget := 70,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG007_minimax_level_finite",
    package := .minimaxLevels,
    description := "Show each minimax level is a finite real number from finite-core escape and tail-sphere barrier hypotheses.",
    budget := 85,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG008_minimax_level_lower_barrier",
    package := .minimaxLevels,
    description := "Prove the nth minimax level is bounded below by the corresponding high-sphere tail barrier.",
    budget := 80,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG009_ps_sequence_at_level",
    package := .deformationAndCompactness,
    description := "Construct a Palais-Smale sequence at each minimax level, via the deformation alternative for noncritical levels.",
    budget := 95,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG010_deformation_lemma_noncritical",
    package := .deformationAndCompactness,
    description := "Formalize the odd deformation lemma excluding a noncritical minimax level while preserving admissibility.",
    budget := 100,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG011_ps_compactness_subsequence",
    package := .deformationAndCompactness,
    description := "Apply PS_c compactness at the minimax level to extract a convergent subsequence from the constructed PS sequence.",
    budget := 65,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG012_limit_is_critical_point",
    package := .criticalExtraction,
    description := "Pass derivative convergence through the subsequential limit to prove the limit point is critical.",
    budget := 85,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG013_limit_has_minimax_value",
    package := .criticalExtraction,
    description := "Pass functional-value convergence through the same subsequential limit to identify the critical value with the minimax level.",
    budget := 70,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG014_indexed_critical_point_choice",
    package := .criticalExtraction,
    description := "Choose an indexed critical point at each minimax level and package the result as FountainConclusion.criticalPoint.",
    budget := 60,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG015_barriers_tend_to_infinity",
    package := .unboundedMultiplicity,
    description := "Prove the selected tail-sphere lower barriers tend to infinity or are unbounded above.",
    budget := 85,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG016_minimax_levels_unbounded",
    package := .unboundedMultiplicity,
    description := "Transfer unboundedness from tail barriers to the minimax levels.",
    budget := 75,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG017_critical_values_unbounded",
    package := .unboundedMultiplicity,
    description := "Convert unbounded minimax levels into CriticalValuesUnboundedAbove Phi.",
    budget := 65,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  },
  {
    id := "MG018_distinctness_from_unbounded_values",
    package := .unboundedMultiplicity,
    description := "Record the multiplicity consequence: unbounded critical values imply infinitely many distinct critical points when needed by the public wording.",
    budget := 80,
    withinBudget := by decide,
    status := "unchecked_formalization_debt"
  }
]

/-- Public-backfill summary for the minimax/genus split. -/
def minimaxGenusLeafBudgetRationale : String :=
  "The minimax/genus construction is split into 18 future proof leaves " ++
  "MG001-MG018, each with an explicit budget <= 100. All rows remain " ++
  "`unchecked_formalization_debt`; the split is a planning gate only and " ++
  "does not complete the Fountain theorem."

/-!
The next declarations are intentionally data-only audit markers.  They make the
public backfill status machine-checkable in this owned artifact without claiming
a proof of any Fountain theorem variant.
-/

/-- Public Stage1 status marker for the current repo-local artifact. -/
def stage1PublicAuditStatus : String :=
  "not_completed"

/-- Repo-local artifact path that has been checked for this statement shape. -/
def stage1StatementShapeArtifact : String :=
  "Formalizations/Lean/AwesomeTheorems/Stage1/S1_M_165.lean"

/--
Backfill note to merge into the public Stage1 surface: the local Lean
statement-shape artifact exists and validates, but the Fountain theorem remains
open as formalization debt.
-/
def stage1PublicAuditNote : String :=
  "S1-M-165 has a repo-local Lean statement-shape artifact at " ++
  stage1StatementShapeArtifact ++
  "; this is not a proof of the Fountain theorem, and the theorem remains not completed."

/-! ## Public-surface backfill plan for child task S1-M-165-C008 -/

/--
Public surfaces that must be updated together by a serialized integrator patch
after any later machine closure.

This marker is intentionally data-only: this child worker does not edit shared
public docs and does not claim completion.
-/
structure PublicBackfillSurfaceUpdate where
  path : String
  action : String
  requiredStatusText : String
deriving Repr

/-- Public docs that should be synchronized by the later integrator patch. -/
def publicBackfillSurfaceUpdates : List PublicBackfillSurfaceUpdate := [
  {
    path := "Docs/Stage1_Blueprint.md",
    action := "merge S1-M-165 audit note, anchor table, selected variant, compactness choice, decomposition choice, and minimax leaf split",
    requiredStatusText := "not completed; local statement-shape artifact only; formalization_debt"
  },
  {
    path := "Docs/todos_20260430.md",
    action := "mirror the remaining unchecked S1-M-165 child leaves and keep machine closure gates open",
    requiredStatusText := "open until local proof body, mathlib wrapper, or pinned external dependency validates"
  },
  {
    path := "README.md",
    action := "avoid any summary wording that presents S1-M-165 as completed or repo-local closed",
    requiredStatusText := "statement-shape/anchor artifact exists; Fountain theorem not repo-local closed"
  }
]

/--
Repo-local integration-debt gate for the public backfill child.

No external Lean 4 Fountain theorem has been found, so this pass creates no
anchor-only completed state.  If a later pass finds such a proof, public docs
must either cite a pinned/imported/checked dependency or name a concrete
integration blocker, and must not mark completion from anchor-only evidence.
-/
def repoLocalIntegrationDebtGateForC008 : String :=
  "pass_for_non_completion: no repo_local_integration_debt is retained in a " ++
  "completed state; no public completion checkbox may change until a local " ++
  "proof body, mathlib wrapper, or pinned external dependency validates and " ++
  "Docs/Stage1_Blueprint.md, Docs/todos_20260430.md, and README.md are " ++
  "updated together by an integrator."

/-- Integration-ready public backfill text for the C008 child ledger. -/
def publicBackfillProposalForC008 : String :=
  "S1-M-165 / THM-M-1272 remains not completed.  The repo-local Lean artifact " ++
  "`Formalizations/Lean/AwesomeTheorems/Stage1/S1_M_165.lean` validates as a " ++
  "statement-shape and anchor artifact only.  Public surfaces must keep the " ++
  "debt classification as `formalization_debt`, with no retained " ++
  "`repo_local_integration_debt` completion state.  If a later external Lean 4 " ++
  "Fountain theorem is found, an integrator must pin/import/check it in Lake or " ++
  "record a concrete integration blocker before changing any completion state."

/-! ## External Lean 4 Fountain-theorem audit for child task S1-M-165-C007 -/

/--
Possible outcomes for the external Lean 4 Fountain-theorem audit gate.

Only `externalProofPinnedAndChecked` can support a repo-local completion claim,
and even then only after the pinned dependency or wrapper has passed the local
Lake validation command.
-/
inductive ExternalFountainLeanAuditResult where
  | noTerminalLean4ProofFound
  | externalProofFoundIntegrationBlocked
  | externalProofPinnedAndChecked
deriving DecidableEq, Repr

/-- Date of this child-task external audit pass. -/
def externalFountainLeanAuditDate : String :=
  "2026-05-01"

/-- Local and public-source search terms used for this child-task audit pass. -/
def externalFountainLeanAuditSearchTerms : List String := [
  "Fountain",
  "Fountain theorem",
  "Palais-Smale",
  "PalaisSmale",
  "critical point theorem",
  "minimax critical point",
  "Lean4 Fountain theorem Palais-Smale",
  "Lean Palais-Smale ContDiff",
  "GitHub Lean Fountain theorem leanprover"
]

/--
Current external Lean 4 audit result for `S1-M-165-C007`.

The local pinned dependency closure and public web/source search did not identify
a terminal Lean 4 Fountain theorem, Palais-Smale theorem, or minimax
critical-point theorem.  `gh auth status` reported no authenticated GitHub
session, so authenticated GitHub code search remains a future integration audit
step rather than evidence for completion.
-/
def currentExternalFountainLeanAuditResult : ExternalFountainLeanAuditResult :=
  .noTerminalLean4ProofFound

/-- The current child audit found no external terminal Lean 4 proof to integrate. -/
theorem currentExternalFountainLeanAuditResult_eq_noTerminalProofFound :
    currentExternalFountainLeanAuditResult =
      ExternalFountainLeanAuditResult.noTerminalLean4ProofFound :=
  rfl

/--
Repo-local integration-debt gate result for this child pass.

There is no completed external-anchor state here: no external Lean 4 proof was
found, no anchor-only proof is being counted, and the parent theorem must remain
`not_completed` unless a later pass pins/imports/checks an external proof or
records a concrete integration blocker for a found proof.
-/
def repoLocalIntegrationDebtGateForC007 : String :=
  "pass_for_non_completion: no external Lean 4 Fountain theorem was found; no " ++
  "anchor-only evidence is counted as completed; future found proofs require " ++
  "pin/import/check or a concrete Lake integration blocker."

/-! ## Audit probes -/

#check CriticalPoint
#check CriticalValue
#check CriticalValuesUnboundedAbove
#check FrechetResidual
#check HasConvergentSubsequence
#check PalaisSmaleSequence
#check PalaisSmaleCompactnessAt
#check FullPalaisSmaleCompactness
#check FunctionalValuesBounded
#check CeramiSequence
#check CeramiCompactness
#check CompactnessRequirement
#check ClassicalFountainCompactness
#check selectedCompactnessRequirement
#check selectedCompactnessRequirement_eq_psAtLevels
#check selectedCompactnessRequirementRationale
#check FountainGeometry
#check FountainHypotheses
#check FountainConclusion
#check StatementShape
#check localMin_criticalPoint_anchor
#check contDiff_one_continuous_anchor
#check contDiff_one_differentiable_anchor
#check exists_hilbertBasis_anchor
#check fderiv
#check ContDiff
#check IsLocalMin.fderiv_eq_zero
#check HilbertBasis
#check exists_hilbertBasis
#check IsHilbertSum
#check FiniteDimensional
#check PublicMathlibAnchorRow
#check publicMathlibAnchorTable
#check FountainVariant
#check selectedFountainVariant
#check selectedFountainVariant_eq_classical
#check selectedFountainVariantRationale
#check nonSelectedFountainVariantNotes
#check FountainDecompositionModel
#check selectedFountainDecompositionModel
#check selectedFountainDecompositionModel_eq_orthogonalSubmodules
#check OrthogonalPairHilbertSum
#check orthogonalPairHilbertSum_anchor
#check selectedFountainDecompositionModelRationale
#check nonSelectedFountainDecompositionModelNotes
#check MinimaxGenusPackage
#check MinimaxGenusLeafBudget
#check MinimaxGenusLeafBudget.budget_le_100
#check minimaxGenusLeafBudgetLedger
#check minimaxGenusLeafBudgetRationale
#check stage1PublicAuditStatus
#check stage1StatementShapeArtifact
#check stage1PublicAuditNote
#check PublicBackfillSurfaceUpdate
#check publicBackfillSurfaceUpdates
#check repoLocalIntegrationDebtGateForC008
#check publicBackfillProposalForC008
#check ExternalFountainLeanAuditResult
#check externalFountainLeanAuditDate
#check externalFountainLeanAuditSearchTerms
#check currentExternalFountainLeanAuditResult
#check currentExternalFountainLeanAuditResult_eq_noTerminalProofFound
#check repoLocalIntegrationDebtGateForC007

end AwesomeTheorems.Stage1.S1_M_165
