import Mathlib.Analysis.CStarAlgebra.Spectrum
import Mathlib.Analysis.InnerProductSpace.Laplacian
import Mathlib.Analysis.InnerProductSpace.Symmetric
import Mathlib.Analysis.ODE.Basic
import Mathlib.Analysis.ODE.PicardLindelof

/-!
# S1-M-193 / THM-M-1525: Schrödinger equation

This Stage1 artifact records a conservative Lean 4 statement boundary for the
Schrodinger equation as a mathematical-physics theorem.

The pinned mathlib snapshot has useful Hilbert-space, bounded linear-operator,
C-star spectrum, unitary, Laplacian, and ODE interfaces.  It does not expose a
terminal theorem for self-adjoint unbounded Hamiltonians, Stone's theorem,
unitary propagators generated by such Hamiltonians, spectral resolution of the
Hamiltonian, or PDE well-posedness for the Schrodinger equation.

Accordingly this file keeps the physics/PDE theorem as an explicit
proposition-level contract and adds only low-risk checked wrappers around the
available substrate.  It does not claim a proof of the full Schrodinger
equation.
-/

noncomputable section

open Set

universe uH uA

namespace AwesomeTheorems
namespace Stage1
namespace S1_M_193

/--
Concrete time-derivative interface for candidate wavefunctions.

The chosen derivative is still an interface field, because this Stage1 artifact
does not build the terminal unbounded Hamiltonian / Stone-theorem development.
The Schrodinger equation below now ties the field to Lean's `HasDerivAt`
predicate and to a domain-invariance obligation instead of using an unconstrained
abstract derivative operation.
-/
structure SchrodingerDerivativeDomainInterface
    (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H] where
  derivative : (ℝ → H) → ℝ → H

/-- A wavefunction stays inside the Hamiltonian domain for all real times. -/
def DomainInvariant
    {H : Type uH} (domain : Set H) (ψ : ℝ → H) : Prop :=
  ∀ t : ℝ, ψ t ∈ domain

/-- The selected derivative agrees with Lean's real Fréchet derivative API. -/
def HasConcreteTimeDerivative
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    (T : SchrodingerDerivativeDomainInterface H) (ψ : ℝ → H) : Prop :=
  ∀ t : ℝ, HasDerivAt ψ (T.derivative ψ t) t

/--
Abstract Hamiltonian system for a normalized Schrodinger-equation statement.

The Hamiltonian is represented as a bounded complex-linear operator here because
that is the safest operator interface available in the current local mathlib
closure.  A terminal quantum-mechanics formalization should replace this with
an unbounded self-adjoint operator together with its dense domain, spectral
calculus, and unitary group generated by Stone's theorem.
-/
structure SchrodingerSystem
    (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H] where
  hamiltonian : H →L[ℂ] H
  derivativeDomain : SchrodingerDerivativeDomainInterface H
  domain : Set H
  initialState : H
  potentialEnergy : H → ℝ
  hamiltonianSelfAdjoint : Prop
  denseInvariantDomain : Prop
  unitaryEvolutionGeneratedByHamiltonian : Prop
  spectralCalculusCompatible : Prop

/--
Formula-level Schrodinger equation for a wavefunction.

The derivative is supplied by `derivativeDomain.derivative`, but the equation
now requires both concrete real differentiability (`HasDerivAt`) and explicit
domain invariance for the wavefunction.
-/
def SchrodingerEquation
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    (D : SchrodingerSystem H) (ψ : ℝ → H) : Prop :=
  DomainInvariant D.domain ψ ∧
    HasConcreteTimeDerivative D.derivativeDomain ψ ∧
      ∀ t : ℝ,
        Complex.I • D.derivativeDomain.derivative ψ t = D.hamiltonian (ψ t)

/-- A candidate solution package for the normalized Schrodinger system. -/
structure SchrodingerSolution
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    (D : SchrodingerSystem H) where
  wavefunction : ℝ → H
  initialCondition : wavefunction 0 = D.initialState
  equation : SchrodingerEquation D wavefunction
  normPreserved : Prop
  energyConserved : Prop
  spectralResolutionCompatible : Prop

/--
Public statement-normalization note for THM-M-1525:
`AwesomeTheorems.Stage1.S1_M_193.StatementShape` is the current Lean 4
boundary for the normalized Schrodinger-equation statement.  It is a
proposition-level boundary and not a terminal proof of the Schrodinger
equation.

For every complex Hilbert-space model with an explicitly specified Hamiltonian,
domain, derivative interface, spectral-calculus boundary, and unitary-evolution
boundary, there should be a wavefunction solving the equation with the stated
initial condition and conservation contracts.  This is a statement shape, not a
terminal proof.
-/
def StatementShape : Prop :=
  ∀ (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H]
    [InnerProductSpace ℂ H] [CompleteSpace H],
      ∀ D : SchrodingerSystem H,
        D.hamiltonianSelfAdjoint →
          D.denseInvariantDomain →
            D.unitaryEvolutionGeneratedByHamiltonian →
              D.spectralCalculusCompatible →
                Nonempty (SchrodingerSolution D)

/-- Low-risk introduction wrapper for the normalized statement shape. -/
theorem StatementShape.intro
    (h : ∀ (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H]
      [InnerProductSpace ℂ H] [CompleteSpace H],
        ∀ D : SchrodingerSystem H,
          D.hamiltonianSelfAdjoint →
            D.denseInvariantDomain →
              D.unitaryEvolutionGeneratedByHamiltonian →
                D.spectralCalculusCompatible →
                  Nonempty (SchrodingerSolution D)) :
    StatementShape.{uH} :=
  h

/-- Checked bounded-operator substrate: the identity Hamiltonian is continuous linear. -/
def identityHamiltonian
    (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H] : H →L[ℂ] H :=
  ContinuousLinearMap.id ℂ H

/-- The checked identity Hamiltonian acts as the identity. -/
theorem identityHamiltonian_apply
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H] (ψ : H) :
    identityHamiltonian H ψ = ψ :=
  ContinuousLinearMap.id_apply ψ

/--
Projection wrapper: every packaged solution exposes the Schrodinger equation.
-/
theorem SchrodingerSolution.equation_at
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    {D : SchrodingerSystem H} (S : SchrodingerSolution D) (t : ℝ) :
    S.wavefunction t ∈ D.domain ∧
      HasDerivAt S.wavefunction (D.derivativeDomain.derivative S.wavefunction t) t ∧
        Complex.I • D.derivativeDomain.derivative S.wavefunction t =
          D.hamiltonian (S.wavefunction t) :=
  ⟨S.equation.1 t, S.equation.2.1 t, S.equation.2.2 t⟩

/--
Projection wrapper: every packaged solution exposes the concrete
domain-invariance obligation.
-/
theorem SchrodingerSolution.domain_invariant
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    {D : SchrodingerSystem H} (S : SchrodingerSolution D) :
    DomainInvariant D.domain S.wavefunction :=
  S.equation.1

/--
Projection wrapper: every packaged solution exposes the concrete real
derivative obligation.
-/
theorem SchrodingerSolution.has_time_derivative
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    {D : SchrodingerSystem H} (S : SchrodingerSolution D) :
    HasConcreteTimeDerivative D.derivativeDomain S.wavefunction :=
  S.equation.2.1

/--
Projection wrapper: every packaged solution exposes its initial condition.
-/
theorem SchrodingerSolution.initial_value
    {H : Type uH} [NormedAddCommGroup H] [NormedSpace ℂ H]
    {D : SchrodingerSystem H} (S : SchrodingerSolution D) :
    S.wavefunction 0 = D.initialState :=
  S.initialCondition

/--
Checked algebraic zero-Hamiltonian toy package.

This is not a physical theorem.  It is a small sanity check that the normalized
equation contract can be inhabited for a degenerate bounded Hamiltonian and a
zero derivative interface.
-/
def zeroHamiltonianSystem
    (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H] :
    SchrodingerSystem H where
  hamiltonian := 0
  derivativeDomain := {
    derivative := fun _ _ => 0
  }
  domain := Set.univ
  initialState := 0
  potentialEnergy := fun _ => 0
  hamiltonianSelfAdjoint := True
  denseInvariantDomain := True
  unitaryEvolutionGeneratedByHamiltonian := True
  spectralCalculusCompatible := True

/-- The constant zero wavefunction solves the checked zero-Hamiltonian toy system. -/
theorem zeroWavefunction_solves_zeroHamiltonian
    (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H] :
    SchrodingerEquation (zeroHamiltonianSystem H) (fun _ : ℝ => (0 : H)) := by
  refine ⟨?_, ?_, ?_⟩
  · intro t
    simp [zeroHamiltonianSystem]
  · intro t
    simpa [zeroHamiltonianSystem, HasConcreteTimeDerivative] using
      (hasDerivAt_const (x := t) (c := (0 : H)))
  · intro t
    simp [zeroHamiltonianSystem]

/-- The checked zero-Hamiltonian toy system has a packaged solution. -/
theorem zeroHamiltonianSystem_has_solution
    (H : Type uH) [NormedAddCommGroup H] [NormedSpace ℂ H] :
    Nonempty (SchrodingerSolution (zeroHamiltonianSystem H)) :=
  ⟨{
    wavefunction := fun _ : ℝ => (0 : H)
    initialCondition := rfl
    equation := zeroWavefunction_solves_zeroHamiltonian H
    normPreserved := True
    energyConserved := True
    spectralResolutionCompatible := True
  }⟩

/--
Checked C-star spectral anchor: the spectrum of a unitary element lies on the
unit circle.  This is relevant substrate for unitary quantum evolution, not a
Schrodinger-equation theorem.
-/
theorem unitary_spectrum_subset_circle
    {A : Type uA} [NormedRing A] [StarRing A] [CStarRing A] [NormedAlgebra ℂ A]
    [CompleteSpace A] (U : unitary A) :
    spectrum ℂ (U : A) ⊆ Metric.sphere 0 1 :=
  Unitary.spectrum_subset_circle U

/--
Checked Laplacian anchor: the Laplacian of a constant scalar field is zero.
This is only spatial-differential substrate for later PDE special cases.
-/
theorem laplacian_const_scalar
    {ι : Type uH} [Fintype ι] [DecidableEq ι] (c : ℂ) :
    Laplacian.laplacian (fun _ : EuclideanSpace ℝ ι => c) = 0 := by
  simp

/-- mathlib modules checked while locating repo-local Schrodinger-equation anchors. -/
def mathlibAnchorModules : List String := [
  "Mathlib.Analysis.InnerProductSpace.Basic",
  "Mathlib.Analysis.InnerProductSpace.Laplacian",
  "Mathlib.Analysis.InnerProductSpace.Spectrum",
  "Mathlib.Analysis.InnerProductSpace.Symmetric",
  "Mathlib.Analysis.Normed.Operator.Basic",
  "Mathlib.Analysis.CStarAlgebra.Spectrum",
  "Mathlib.Analysis.CStarAlgebra.Exponential",
  "Mathlib.Analysis.CStarAlgebra.Unitary.Connected",
  "Mathlib.Analysis.ODE.Basic",
  "Mathlib.Analysis.ODE.PicardLindelof"
]

/-- Pinned mathlib revision used for the C002 mathlib audit. -/
def c002MathlibAuditRevision : String :=
  "8a178386ffc0f5fef0b77738bb5449d50efeea95"

/--
Exact modules requested by `THM-M-1525.mathlib-audit`.

These are audit anchors only.  They provide substrate APIs around Laplacians,
symmetric operators, C-star spectra, and ODE existence interfaces; they are not
a terminal Schrodinger-equation theorem.
-/
def c002RequestedMathlibAuditModules : List String := [
  "InnerProductSpace.Laplacian",
  "InnerProductSpace.Symmetric",
  "CStarAlgebra.Spectrum",
  "ODE.Basic",
  "ODE.PicardLindelof"
]

/-- Full mathlib import paths corresponding to the C002 requested audit modules. -/
def c002RequestedMathlibAuditModulePaths : List String := [
  "Mathlib.Analysis.InnerProductSpace.Laplacian",
  "Mathlib.Analysis.InnerProductSpace.Symmetric",
  "Mathlib.Analysis.CStarAlgebra.Spectrum",
  "Mathlib.Analysis.ODE.Basic",
  "Mathlib.Analysis.ODE.PicardLindelof"
]

/-- Checked record that the C002 audit uses the requested pinned mathlib revision. -/
theorem c002MathlibAuditRevision_eq :
    c002MathlibAuditRevision =
      "8a178386ffc0f5fef0b77738bb5449d50efeea95" :=
  rfl

/-- Checked record that the C002 audit names exactly the requested modules. -/
theorem c002RequestedMathlibAuditModules_eq :
    c002RequestedMathlibAuditModules = [
      "InnerProductSpace.Laplacian",
      "InnerProductSpace.Symmetric",
      "CStarAlgebra.Spectrum",
      "ODE.Basic",
      "ODE.PicardLindelof"
    ] :=
  rfl

/--
Checked wrappers requested by `THM-M-1525.wrapper`.

These four names are substrate wrappers only.  They certify small bounded
operator, degenerate-solution, unitary-spectrum, and constant-Laplacian facts
available in the local Lean/mathlib closure; they are not a terminal proof of
the Schrodinger equation, Stone's theorem, self-adjoint Hamiltonian dynamics,
or PDE well-posedness.
-/
def c003SubstrateWrapperNames : List String := [
  "identityHamiltonian_apply",
  "zeroHamiltonianSystem_has_solution",
  "unitary_spectrum_subset_circle",
  "laplacian_const_scalar"
]

/-- Checked record that C003 cites exactly the requested substrate wrappers. -/
theorem c003SubstrateWrapperNames_eq :
    c003SubstrateWrapperNames = [
      "identityHamiltonian_apply",
      "zeroHamiltonianSystem_has_solution",
      "unitary_spectrum_subset_circle",
      "laplacian_const_scalar"
    ] :=
  rfl

/--
Hamiltonian API choices audited for `THM-M-1525.operator-model`.

The current checked substrate in this file uses the bounded-special-case
interface.  The terminal Schrodinger-equation theorem should instead use the
densely-defined self-adjoint operator interface, unless a future worker pins and
checks an external Lean 4 operator-theory dependency providing that interface.
-/
inductive HamiltonianAPIChoice where
  | boundedSpecialCase
  | denselyDefinedSelfAdjoint
  | pinnedExternalOperatorTheoryDependency
  deriving DecidableEq, Repr

/--
C004 terminal decision: the full theorem should target a densely-defined
self-adjoint Hamiltonian with domain, spectral-calculus, and Stone-theorem
interfaces.  This is a decision record, not a proof that such an API is already
available in the repo-local Lean closure.
-/
def c004TerminalHamiltonianAPIChoice : HamiltonianAPIChoice :=
  HamiltonianAPIChoice.denselyDefinedSelfAdjoint

/--
C004 current substrate record: the existing `SchrodingerSystem.hamiltonian`
field is only a bounded-operator special case.
-/
def c004CurrentRepoLocalHamiltonianAPIChoice : HamiltonianAPIChoice :=
  HamiltonianAPIChoice.boundedSpecialCase

/-- Checked record of the C004 terminal Hamiltonian API decision. -/
theorem c004TerminalHamiltonianAPIChoice_eq :
    c004TerminalHamiltonianAPIChoice =
      HamiltonianAPIChoice.denselyDefinedSelfAdjoint :=
  rfl

/-- Checked record that the present repo-local API is still bounded substrate. -/
theorem c004CurrentRepoLocalHamiltonianAPIChoice_eq :
    c004CurrentRepoLocalHamiltonianAPIChoice =
      HamiltonianAPIChoice.boundedSpecialCase :=
  rfl

/-- C004 child-scope status for the terminal operator model. -/
def c004OperatorModelMachineStatus : String :=
  "not_repo_local_closed"

/-- C004 child-scope debt classification for the terminal operator model. -/
def c004OperatorModelDebtClass : String :=
  "formalization_debt"

/--
C004 integration-debt gate.

No external terminal operator-theory dependency is claimed as integrated here;
therefore this child does not leave an anchor-only external proof as a completed
`repo_local_integration_debt` state.
-/
def c004RepoLocalIntegrationDebtGate : String :=
  "not_completed; no completed-state repo_local_integration_debt retained"

/--
Concrete leaves that remain after selecting the terminal Hamiltonian API.

Each leaf is intentionally a string-level audit record rather than a placeholder
theorem: the missing work is the actual unbounded-operator/domain formalization.
-/
def c004TerminalHamiltonianAPILeaves : List String := [
  "replace bounded hamiltonian field with a densely-defined self-adjoint operator interface",
  "formalize dense domain, domain invariance, and action of the Hamiltonian on the domain",
  "connect spectral calculus and Stone-theorem unitary evolution to the Hamiltonian",
  "keep bounded special cases as substrate wrappers, not as the terminal theorem API"
]

/--
C005 derivative/domain interface status.

The abstract `timeDerivative` field has been replaced by the checked
`SchrodingerDerivativeDomainInterface`, and `SchrodingerEquation` now includes
`DomainInvariant` plus `HasConcreteTimeDerivative`, whose local proof obligation
is Lean's `HasDerivAt`.
-/
def c005DerivativeDomainMachineStatus : String :=
  "local_statement_interface"

/-- C005 child-scope debt classification for the terminal PDE/operator theorem. -/
def c005DerivativeDomainDebtClass : String :=
  "formalization_debt"

/--
C005 integration-debt gate.

No external completed Schrodinger-equation proof is claimed or left as an
anchor-only completion in this child artifact.
-/
def c005RepoLocalIntegrationDebtGate : String :=
  "not_completed; no completed-state repo_local_integration_debt retained"

/--
Concrete remaining C005 leaves after replacing the derivative field.

These are intentionally scoped to the derivative/domain layer and do not claim
completion of the separate unbounded Hamiltonian or Stone-theorem integration.
-/
def c005DerivativeDomainLeaves : List String := [
  "upgrade the bounded Hamiltonian action to an unbounded operator action defined on the invariant domain",
  "prove dense-domain invariance for the intended propagator rather than requiring it in the solution contract",
  "connect HasDerivAt wavefunction differentiability to the terminal self-adjoint Hamiltonian generator equation"
]

/--
C006 exact external-audit search terms requested by `THM-M-1525.external-audit`.

The authenticated GitHub code-search pass is an environment blocker in the
current worker run: no `gh` login or token is available, and unauthenticated
GitHub API code search is rate-limited.  The records below therefore keep the
repo-local completion gate open and record only primary-source anchors that
were directly inspected.
-/
def c006ExternalAuditSearchTerms : List String := [
  "Schrodinger",
  "Schrödinger",
  "Schroedinger",
  "self-adjoint Hamiltonian",
  "Stone theorem",
  "unitary propagator",
  "wavefunction"
]

/-- C006 authentication status for external GitHub code search. -/
def c006ExternalAuditAuthenticationStatus : String :=
  "blocked: gh auth status reports no logged-in GitHub hosts and no GH_TOKEN/GITHUB_TOKEN/GITHUB_PAT is exported"

/--
C006 primary-source Lean 4 anchors inspected outside the local mathlib closure.

Each record includes repository URL, commit, theorem name, placeholder status,
and Lake dependency feasibility.  These anchors are useful model-specific
time-independent Schrodinger-equation facts in PhysLean/physlib, but they do
not provide the terminal self-adjoint Hamiltonian, Stone theorem, unitary
propagator, or general wavefunction existence theorem required for THM-M-1525.
-/
def c006ExternalPrimarySourceRecords : List String := [
  "repo=https://github.com/leanprover-community/physlib; commit=df5ca60cadc7b915abab1d8122984f4e89d78216; module=PhysLean.QuantumMechanics.OneDimension.HarmonicOscillator.TISE; theorem=HarmonicOscillator.schrodingerOperator_eigenfunction; placeholder_status=placeholder-free in inspected raw file; lake_dependency_feasibility=blocked for immediate import because PhysLean at this commit requires Lean/mathlib v4.28.0 while this repo is pinned to Lean/mathlib v4.29.0 and shared lakefile edits are outside this child scope",
  "repo=https://github.com/leanprover-community/physlib; commit=df5ca60cadc7b915abab1d8122984f4e89d78216; module=PhysLean.CondensedMatter.TightBindingChain.Basic; theorem=TightBindingChain.hamiltonian_energyEigenstate; placeholder_status=placeholder-free in inspected raw file; lake_dependency_feasibility=blocked for immediate import because PhysLean at this commit requires Lean/mathlib v4.28.0 while this repo is pinned to Lean/mathlib v4.29.0 and shared lakefile edits are outside this child scope"
]

/-- C006 terminal-theorem result of the external audit. -/
def c006ExternalAuditTerminalResult : String :=
  "no terminal Lean 4 proof of the general Schrodinger equation, Stone-theorem unitary propagator construction, or self-adjoint Hamiltonian wavefunction existence theorem was integrated or claimed"

/-- C006 machine status after the external audit. -/
def c006MachineStatus : String :=
  "not_repo_local_closed"

/-- C006 machine-debt classification for the terminal theorem. -/
def c006MachineDebtClassification : String :=
  "formalization_debt"

/--
C006 integration-debt gate.

The inspected PhysLean/physlib anchors are not terminal THM-M-1525 proofs and
were not imported as repo-local dependencies.  Since no external terminal proof
is claimed as complete, this child does not leave completed-state
`repo_local_integration_debt`.
-/
def c006RepoLocalIntegrationDebtGate : String :=
  "pass for non-completion: no terminal external proof found; no anchor-only external proof counted as completed"

/-- Remaining C006 leaves for a future authenticated/integration pass. -/
def c006RemainingLeaves : List String := [
  "rerun authenticated GitHub code search once a GitHub token or gh login is available",
  "if PhysLean/physlib is selected as an upstream dependency, test a version-compatible pin or document the exact Lean/mathlib conflict",
  "continue searching specifically for Stone theorem, self-adjoint Hamiltonian, unitary propagator, and general wavefunction-existence APIs"
]

/--
C007 integration-gate scope for `THM-M-1525.integration-gate`.

This child consumes the C006 external-audit records.  It does not add a Lake
dependency, because the audited external anchors are not terminal proofs of the
general Schrodinger-equation theorem and immediate PhysLean/physlib integration
has a concrete Lean/mathlib-version blocker.
-/
def c007IntegrationGateScope : List String := [
  "consume C006 external-audit records",
  "do not mark model-specific PhysLean anchors as terminal THM-M-1525 closure",
  "keep completion blocked until a local proof body, pinned mathlib wrapper, or pinned external terminal proof validates"
]

/-- C007 integration decision for currently known external Lean 4 evidence. -/
def c007ExternalProofIntegrationDecision : String :=
  "no terminal external Lean 4 proof was found; inspected PhysLean anchors are model-specific and are not imported or counted as THM-M-1525 completion"

/--
C007 concrete blockers for the external anchors known from C006.

The version blocker is recorded here so anchor-only evidence cannot be promoted
to completed `repo_local_integration_debt` status.
-/
def c007ConcreteIntegrationBlockers : List String := [
  "PhysLean/physlib commit df5ca60cadc7b915abab1d8122984f4e89d78216 is pinned to Lean/mathlib v4.28.0 while this repository is pinned to Lean/mathlib v4.29.0",
  "the inspected PhysLean theorems are model-specific time-independent facts, not a terminal self-adjoint Hamiltonian, Stone theorem, unitary propagator, or general wavefunction-existence proof for THM-M-1525",
  "pin/import/check would require integrator-owned Lake changes outside this child write scope"
]

/-- C007 repo-local integration-debt gate result. -/
def c007RepoLocalIntegrationDebtGate : String :=
  "pass for non-completion: no terminal external proof is left anchor-only as completed; known external anchors have concrete non-terminal/version blockers"

/-- C007 machine status after applying the integration gate. -/
def c007MachineStatus : String :=
  "not_repo_local_closed"

/-- C007 debt classification for the terminal theorem. -/
def c007MachineDebtClassification : String :=
  "formalization_debt"

/-- C007 does not authorize a THM-M-1525 completion claim. -/
def c007CompletionClaimAllowed : Bool :=
  false

/-- Checked record that C007 leaves completion blocked. -/
theorem c007CompletionClaimAllowed_eq :
    c007CompletionClaimAllowed = false :=
  rfl

/-- Remaining C007 leaves for a future integrator or terminal-proof worker. -/
def c007RemainingLeaves : List String := [
  "if a terminal Lean 4 proof is later found, pin/import/check it under the local Lake closure or record the exact toolchain/license/dependency blocker",
  "rerun authenticated external code search before any future completion claim",
  "keep public completion unchecked until repo-local validation covers a terminal theorem or pinned external closure"
]

/--
C008 public-sync scope for `THM-M-1525.public-sync`.

This is a checked integration-ready record only.  Public blueprint/todo files
must be merged by a serial integrator; this worker does not edit shared public
planning documents and does not use private runtime ledgers as authoritative
completion anchors.
-/
def c008PublicSyncScope : List String := [
  "prepare public blueprint/todo backfill text from C001-C007 facts",
  "do not edit shared public planning documents from this child worker",
  "do not cite private .cron runtime ledgers as authoritative public completion anchors",
  "keep THM-M-1525 open until terminal repo-local validation exists"
]

/-- C008 public-sync status. -/
def c008PublicSyncStatus : String :=
  "integration_ready_patch_plan_only"

/-- C008 machine status after public-sync preparation. -/
def c008MachineStatus : String :=
  "not_repo_local_closed"

/-- C008 debt classification for the terminal theorem after public-sync preparation. -/
def c008MachineDebtClassification : String :=
  "formalization_debt"

/--
C008 repo-local integration-debt gate.

No terminal external Lean 4 proof is left as anchor-only completed evidence.
The known PhysLean/physlib anchors remain non-terminal and version-blocked, so
public sync may backfill facts but must not claim theorem completion.
-/
def c008RepoLocalIntegrationDebtGate : String :=
  "pass for non-completion: no completed-state repo_local_integration_debt retained"

/-- C008 does not authorize a THM-M-1525 completion claim. -/
def c008CompletionClaimAllowed : Bool :=
  false

/-- Checked record that C008 leaves completion blocked. -/
theorem c008CompletionClaimAllowed_eq :
    c008CompletionClaimAllowed = false :=
  rfl

/-- Public items that the serial integrator can merge without private ledger paths. -/
def c008PublicBackfillItems : List String := [
  "statement: cite StatementShape as the current proposition-level Lean boundary, not a terminal proof",
  "mathlib-audit: cite pinned mathlib revision 8a178386ffc0f5fef0b77738bb5449d50efeea95 and requested substrate modules",
  "wrapper: cite identityHamiltonian_apply, zeroHamiltonianSystem_has_solution, unitary_spectrum_subset_circle, and laplacian_const_scalar as substrate wrappers only",
  "operator-model: record densely-defined self-adjoint Hamiltonian as terminal API target while current repo-local substrate remains bounded",
  "derivative-domain: record the HasDerivAt/domain-invariance interface and remaining unbounded-domain work",
  "external-audit: record searched terms, PhysLean/physlib non-terminal anchors, authentication blocker, and version mismatch",
  "integration-gate: keep THM-M-1525 open as not_repo_local_closed / formalization_debt with no completion claim"
]

/-- Remaining C008 action belongs to the serial public-doc integrator. -/
def c008RemainingLeaves : List String := [
  "serial integrator merges the public backfill text into the authoritative blueprint/todo surface",
  "public surface keeps private .cron runtime paths out of completion anchors",
  "public checklist remains unchecked for terminal completion until repo-local validation closes the theorem"
]

/-- Nearby checked names used or audited for the Schrodinger boundary. -/
def mathlibAnchorNames : List String := [
  "NormedSpace",
  "InnerProductSpace",
  "CompleteSpace",
  "ContinuousLinearMap",
  "ContinuousLinearMap.id",
  "ContinuousLinearMap.id_apply",
  "Laplacian.laplacian",
  "Laplacian.laplacian_const",
  "LinearMap.IsSymmetric",
  "spectrum",
  "unitary",
  "Unitary.spectrum_subset_circle",
  "ODE.IsSolution",
  "IsPicardLindelof"
]

/--
Search terms that did not locate a terminal Schrodinger-equation theorem in the
pinned local mathlib tree.
-/
def absentTerminalSearchTerms : List String := [
  "Schrodinger",
  "Schrödinger",
  "Schroedinger",
  "Hamiltonian quantum",
  "self-adjoint Hamiltonian",
  "Stone theorem",
  "unitary group",
  "time dependent Schrodinger",
  "quantum mechanics",
  "wavefunction"
]

/-- Primary-source Lean 4 anchors audited for this Stage1 slot. -/
def primarySourceAnchors : List String := [
  "mathlib revision 8a178386ffc0f5fef0b77738bb5449d50efeea95",
  "https://raw.githubusercontent.com/leanprover-community/mathlib4/8a178386ffc0f5fef0b77738bb5449d50efeea95/Mathlib/Analysis/InnerProductSpace/Laplacian.lean",
  "https://raw.githubusercontent.com/leanprover-community/mathlib4/8a178386ffc0f5fef0b77738bb5449d50efeea95/Mathlib/Analysis/InnerProductSpace/Symmetric.lean",
  "https://raw.githubusercontent.com/leanprover-community/mathlib4/8a178386ffc0f5fef0b77738bb5449d50efeea95/Mathlib/Analysis/CStarAlgebra/Spectrum.lean",
  "https://raw.githubusercontent.com/leanprover-community/mathlib4/8a178386ffc0f5fef0b77738bb5449d50efeea95/Mathlib/Analysis/ODE/Basic.lean",
  "https://raw.githubusercontent.com/leanprover-community/mathlib4/8a178386ffc0f5fef0b77738bb5449d50efeea95/Mathlib/Analysis/ODE/PicardLindelof.lean"
]

/-! ## Audit probes retained in the checked file. -/

#check SchrodingerDerivativeDomainInterface
#check DomainInvariant
#check HasConcreteTimeDerivative
#check SchrodingerSystem
#check SchrodingerEquation
#check SchrodingerSolution
#check StatementShape
#check StatementShape.intro
#check identityHamiltonian
#check identityHamiltonian_apply
#check zeroHamiltonianSystem_has_solution
#check unitary_spectrum_subset_circle
#check laplacian_const_scalar
#check c002MathlibAuditRevision
#check c002RequestedMathlibAuditModules
#check c002RequestedMathlibAuditModulePaths
#check c002MathlibAuditRevision_eq
#check c002RequestedMathlibAuditModules_eq
#check c003SubstrateWrapperNames
#check c003SubstrateWrapperNames_eq
#check HamiltonianAPIChoice
#check c004TerminalHamiltonianAPIChoice
#check c004CurrentRepoLocalHamiltonianAPIChoice
#check c004TerminalHamiltonianAPIChoice_eq
#check c004CurrentRepoLocalHamiltonianAPIChoice_eq
#check c004OperatorModelMachineStatus
#check c004OperatorModelDebtClass
#check c004RepoLocalIntegrationDebtGate
#check c004TerminalHamiltonianAPILeaves
#check c005DerivativeDomainMachineStatus
#check c005DerivativeDomainDebtClass
#check c005RepoLocalIntegrationDebtGate
#check c005DerivativeDomainLeaves
#check c006ExternalAuditSearchTerms
#check c006ExternalAuditAuthenticationStatus
#check c006ExternalPrimarySourceRecords
#check c006ExternalAuditTerminalResult
#check c006MachineStatus
#check c006MachineDebtClassification
#check c006RepoLocalIntegrationDebtGate
#check c006RemainingLeaves
#check c007IntegrationGateScope
#check c007ExternalProofIntegrationDecision
#check c007ConcreteIntegrationBlockers
#check c007RepoLocalIntegrationDebtGate
#check c007MachineStatus
#check c007MachineDebtClassification
#check c007CompletionClaimAllowed
#check c007CompletionClaimAllowed_eq
#check c007RemainingLeaves
#check c008PublicSyncScope
#check c008PublicSyncStatus
#check c008MachineStatus
#check c008MachineDebtClassification
#check c008RepoLocalIntegrationDebtGate
#check c008CompletionClaimAllowed
#check c008CompletionClaimAllowed_eq
#check c008PublicBackfillItems
#check c008RemainingLeaves
#check Laplacian.laplacian
#check ContinuousLinearMap.id
#check Unitary.spectrum_subset_circle

end S1_M_193
end Stage1
end AwesomeTheorems
