import Mathlib.NumberTheory.Cyclotomic.Basic
import Mathlib.NumberTheory.Cyclotomic.CyclotomicCharacter
import Mathlib.NumberTheory.EulerProduct.DirichletLSeries
import Mathlib.NumberTheory.LSeries.DirichletContinuation
import Mathlib.NumberTheory.NumberField.Basic
import Mathlib.NumberTheory.Padics.PadicNumbers
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.RingTheory.ClassGroup
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.Topology.Algebra.Ring.Basic

/-!
# S1-M-257 / THM-M-0517: Iwasawa main conjecture

This Stage1 artifact records a Lean 4 statement-shape boundary for the
cyclotomic Iwasawa main conjecture relating a `p`-adic L-function to class-group
Iwasawa modules. It is not a proof of the main conjecture.

The pinned mathlib snapshot has useful adjacent infrastructure: `p`-adic
numbers, cyclotomic fields and the cyclotomic character, ideal class groups, and
complex Dirichlet L-functions. It does not provide a terminal object model for
Iwasawa algebras, inverse limits of class groups, characteristic ideals of
Iwasawa modules, or `p`-adic L-functions.
-/

noncomputable section

open Complex DirichletCharacter
open scoped LSeries.notation
open scoped nonZeroDivisors

namespace AwesomeTheorems
namespace Stage1
namespace S1_M_257

universe uΛ uM uχ

/-- The cyclotomic number-field layer available as a concrete mathlib object. -/
abbrev CyclotomicLayer (n : ℕ) :=
  CyclotomicField n ℚ

/-! ## Cyclotomic class-group tower API boundary -/

/--
The concrete cyclotomic `p`-power layer used for the class-group tower.

The index `n` corresponds to the field generated by `p ^ (n + 1)`-st roots of
unity. Starting at `n + 1` avoids the degenerate `0`-th cyclotomic layer while
keeping the tower indexed by natural numbers.
-/
abbrev CyclotomicTowerLayer (p n : ℕ) [Fact p.Prime] :=
  CyclotomicLayer (p ^ (n + 1))

/-- The ring of integers in the `n`-th cyclotomic `p`-power layer. -/
abbrev CyclotomicTowerRingOfIntegers (p n : ℕ) [Fact p.Prime] :=
  NumberField.RingOfIntegers (CyclotomicTowerLayer p n)

/-- The ideal class group of the ring of integers in the `n`-th tower layer. -/
abbrev CyclotomicTowerClassGroup (p n : ℕ) [Fact p.Prime] :=
  ClassGroup (CyclotomicTowerRingOfIntegers p n)

/--
Checked adjacent wrapper: each concrete `p`-power tower layer is cyclotomic over
`ℚ`.

This supplies a repo-local name for the field tower substrate. It does not
construct norm maps on class groups.
-/
theorem cyclotomicTowerLayer_isCyclotomicExtension_mathlib_wrapper
    (p n : ℕ) [Fact p.Prime] :
    letI : Algebra ℚ (CyclotomicTowerLayer p n) :=
      CyclotomicField.algebraBase (p ^ (n + 1)) ℚ ℚ
    IsCyclotomicExtension {p ^ (n + 1)} ℚ (CyclotomicTowerLayer p n) := by
  letI : Algebra ℚ (CyclotomicTowerLayer p n) :=
    CyclotomicField.algebraBase (p ^ (n + 1)) ℚ ℚ
  exact CyclotomicField.isCyclotomicExtension (p ^ (n + 1)) ℚ

/-- Checked wrapper: the class group object exists for every concrete tower layer. -/
theorem cyclotomicTowerClassGroup_nonempty_mathlib_wrapper
    (p n : ℕ) [Fact p.Prime] :
    Nonempty (CyclotomicTowerClassGroup p n) :=
  inferInstance

/--
API boundary for transition maps in the cyclotomic class-group tower.

The final formalization needs the algebraic norm/corestriction maps induced by
the finite extensions between consecutive `p`-power cyclotomic layers. Current
mathlib gives the class-group objects, but this file does not construct those
norm maps; an implementation must provide them together with their mathematical
specification.
-/
structure ClassGroupTowerAPI (p : ℕ) [Fact p.Prime] : Type where
  transitionNorm :
    (n : ℕ) →
      CyclotomicTowerClassGroup p (n + 1) →*
        CyclotomicTowerClassGroup p n
  transitionNormSpec : (n : ℕ) → Prop
  transitionNorm_spec : ∀ n, transitionNormSpec n

/--
The inverse limit of the supplied class groups along the supplied transition
norm maps.

This is a real Lean type once a `ClassGroupTowerAPI` is supplied. It remains an
API boundary because the transition maps themselves are not constructed here.
-/
def ClassGroupTowerInverseLimit {p : ℕ} [Fact p.Prime]
    (tower : ClassGroupTowerAPI p) : Type :=
  { x : (n : ℕ) → CyclotomicTowerClassGroup p n //
      ∀ n, tower.transitionNorm n (x (n + 1)) = x n }

/--
The child-task closure target for the class-group tower API.

This is intentionally stated as nonemptiness of the complete tower API, not as a
proved construction.
-/
def ClassGroupTowerAPITarget : Prop :=
  ∀ (p : ℕ) [Fact p.Prime], Nonempty (ClassGroupTowerAPI p)

/-- The class-group tower API target unfolds to nonemptiness of the concrete API. -/
theorem classGroupTowerAPITarget_iff :
    ClassGroupTowerAPITarget ↔
      ∀ (p : ℕ) [Fact p.Prime], Nonempty (ClassGroupTowerAPI p) :=
  Iff.rfl

/--
Checked interface for characteristic ideals of torsion modules over a candidate
Iwasawa algebra.

This is an API boundary, not a construction: an implementation must supply the
ideal-valued operation and its specification theorem for every torsion module.
-/
structure CharacteristicIdealTheory (Λ : Type uΛ) [CommRing Λ] :
    Type (max uΛ uM + 1) where
  characteristicIdealOfTorsionModule :
    (M : Type uM) → [AddCommGroup M] → [Module Λ M] →
      Module.IsTorsion Λ M → Ideal Λ
  characteristicIdealSpec :
    (M : Type uM) → [AddCommGroup M] → [Module Λ M] →
      Module.IsTorsion Λ M → Ideal Λ → Prop
  characteristicIdeal_spec :
    ∀ (M : Type uM) [AddCommGroup M] [Module Λ M]
      (hM : Module.IsTorsion Λ M),
        characteristicIdealSpec M hM
          (characteristicIdealOfTorsionModule M hM)

/--
Concrete API target for the Iwasawa algebra side over `ℤ_[p]`.

The package deliberately requires topology, a topological-ring structure,
`ℤ_[p]`-algebra structure, noetherian/domain instances, an augmentation ideal,
and characteristic ideals for torsion modules. No term of this structure is
constructed in this file; `S1-M-257.iwasawa-algebra-api` remains open until such
an object is imported or defined and locally validated.
-/
structure IwasawaAlgebraAPI (p : ℕ) [Fact p.Prime] :
    Type (max uΛ uM + 1) where
  Λ : Type uΛ
  [commRing : CommRing Λ]
  [algebraOverPadicIntegers : Algebra ℤ_[p] Λ]
  [topologicalSpace : TopologicalSpace Λ]
  [isTopologicalRing : IsTopologicalRing Λ]
  [noetherianRing : IsNoetherianRing Λ]
  [domain : IsDomain Λ]
  completedGroupAlgebraTopology : Prop
  completedGroupAlgebraTopology_proof : completedGroupAlgebraTopology
  augmentationIdeal : Ideal Λ
  characteristicIdealTheory : CharacteristicIdealTheory.{uΛ, uM} Λ

/--
The child-task closure target for the Iwasawa algebra API.

This proposition is named so later work can replace the current boundary with a
real imported or locally defined package. It is not proved here.
-/
def IwasawaAlgebraAPITarget : Prop :=
  ∀ (p : ℕ) [Fact p.Prime],
    Nonempty (IwasawaAlgebraAPI.{uΛ, uM} p)

/-- The Iwasawa algebra API target unfolds to nonemptiness of the concrete API. -/
theorem iwasawaAlgebraAPITarget_iff :
    IwasawaAlgebraAPITarget.{uΛ, uM} ↔
      ∀ (p : ℕ) [Fact p.Prime],
        Nonempty (IwasawaAlgebraAPI.{uΛ, uM} p) :=
  Iff.rfl

/--
Boundary for the Iwasawa algebra side of the main conjecture.

A terminal formalization should replace `AlgebraObject` by a concrete completed
group algebra, usually a completed `ℤ_[p]` group ring of a Galois group, and
prove the noetherian/characteristic-ideal API rather than keeping it as `Prop`
data.
-/
structure IwasawaAlgebraBoundary (p : ℕ) [Fact p.Prime] : Type (uΛ + 1) where
  AlgebraObject : Type uΛ
  isCompletedGroupAlgebra : Prop
  isNoetherianDomain : Prop
  hasCharacteristicIdealTheory : Prop

/--
Boundary for the inverse-limit class-group module used in the Iwasawa main
conjecture.

The field `characteristicIdeal` is deliberately typed in the abstract algebra
object supplied by `IwasawaAlgebraBoundary`; it is only a statement-shape
placeholder until mathlib or a pinned Lean 4 dependency supplies the completed
group algebra and its ideal theory.
-/
structure IwasawaModuleBoundary (p : ℕ) [Fact p.Prime]
    (Λ : IwasawaAlgebraBoundary.{uΛ} p) : Type (max uM uΛ + 1) where
  classGroupTower : ClassGroupTowerAPI p
  ModuleObject : Type uM
  inverseLimitComparison : ModuleObject → ClassGroupTowerInverseLimit classGroupTower
  isInverseLimitOfClassGroups : Prop
  isTorsionOverIwasawaAlgebra : Prop
  characteristicIdeal : Λ.AlgebraObject
  characteristicIdealCorrect : Prop

/-- A finitely additive `ℚ_[p]`-valued distribution on a measurable space. -/
structure PadicDistributionModel (p : ℕ) [Fact p.Prime]
    (CharacterSpace : Type uχ) [MeasurableSpace CharacterSpace] :
    Type uχ where
  mass : Set CharacterSpace → ℚ_[p]
  mass_empty : mass ∅ = 0
  mass_union_of_disjoint :
    ∀ {s t : Set CharacterSpace}, MeasurableSet s → MeasurableSet t →
      Disjoint s t → mass (s ∪ t) = mass s + mass t
  boundednessCondition : Prop
  boundedness_condition : boundednessCondition

/--
API boundary for the `p`-adic measure/distribution and interpolation theorem
needed to construct the cyclotomic `p`-adic L-function.

The `interpolationValue` field is the already-normalized `p`-adic value of the
complex critical L-value after all Euler factors, periods, embeddings, and
algebraicity results have been accounted for. A terminal formalization should
replace it by the explicit normalization theorem for Dirichlet characters.
-/
structure PadicLFunctionAPI (p : ℕ) [Fact p.Prime] : Type (uχ + 1) where
  CharacterSpace : Type uχ
  [characterMeasurableSpace : MeasurableSpace CharacterSpace]
  [characterTopologicalSpace : TopologicalSpace CharacterSpace]
  distribution : PadicDistributionModel p CharacterSpace
  pAdicLFunction : CharacterSpace → ℚ_[p]
  locallyAlgebraicCharacters : Set CharacterSpace
  interpolationValue : CharacterSpace → ℚ_[p]
  interpolationFormula :
    ∀ χ ∈ locallyAlgebraicCharacters,
      pAdicLFunction χ = interpolationValue χ
  measureConstructsLFunction : Prop
  measure_constructs_lfunction : measureConstructsLFunction
  cyclotomicCharacterCompatibility : Prop
  cyclotomic_character_compatibility : cyclotomicCharacterCompatibility

/--
The child-task closure target for the `p`-adic L-function API.

This proposition is intentionally nonemptiness of the complete API, not a
claimed construction. The current file defines the expected interface but does
not prove that such a package exists in the repo-local Lean environment.
-/
def PadicLFunctionAPITarget : Prop :=
  ∀ (p : ℕ) [Fact p.Prime], Nonempty (PadicLFunctionAPI.{uχ} p)

/-- The `p`-adic L-function API target unfolds to nonemptiness of the concrete API. -/
theorem padicLFunctionAPITarget_iff :
    PadicLFunctionAPITarget.{uχ} ↔
      ∀ (p : ℕ) [Fact p.Prime], Nonempty (PadicLFunctionAPI.{uχ} p) :=
  Iff.rfl

/--
Boundary for a `p`-adic L-function package.

The true formal object should be a measure/distribution on a `p`-adic Galois
group or character space, with interpolation formulas for critical complex
L-values. Current local mathlib exposes `ℚ_[p]` and cyclotomic-character
substrate, but not this terminal package.
-/
structure PadicLFunctionBoundary (p : ℕ) [Fact p.Prime] : Type (uχ + 1) where
  api : PadicLFunctionAPI.{uχ} p
  generatesIwasawaElement : Prop
  generates_iwasawa_element : generatesIwasawaElement

/--
Boundary package for the cyclotomic Iwasawa main conjecture.

The final equality is intentionally represented by a proposition, not asserted
as a proved theorem. Later work must replace the abstract algebra/module/L-
function fields by concrete mathlib or pinned upstream Lean 4 objects.
-/
structure IwasawaMainConjectureBoundary (p : ℕ) [Fact p.Prime] :
    Type (max (max uM uΛ) uχ + 1) where
  Λ : IwasawaAlgebraBoundary.{uΛ} p
  classGroupModule : IwasawaModuleBoundary.{uΛ, uM} p Λ
  pAdicLFunction : PadicLFunctionBoundary.{uχ} p
  pAdicLFunctionGeneratesCharacteristicIdeal : Prop

/--
Stage1 normalized statement shape for the source claim: the cyclotomic Iwasawa
main conjecture relates a `p`-adic L-function to the characteristic ideal of the
class-group Iwasawa module.

This is a formalization boundary only. It is not proved in this file.
-/
def StatementShape : Prop :=
  ∀ (p : ℕ) [Fact p.Prime],
    Nonempty (IwasawaMainConjectureBoundary.{uΛ, uM, uχ} p)

/-- The statement-shape definition unfolds to nonemptiness of the boundary package. -/
theorem statementShape_iff :
    StatementShape.{uΛ, uM, uχ} ↔
      ∀ (p : ℕ) [Fact p.Prime],
        Nonempty (IwasawaMainConjectureBoundary.{uΛ, uM, uχ} p) :=
  Iff.rfl

/--
Machine status for the current Stage1 artifact.

`statementBoundaryOnly` records that the local file has checked the Lean shape
of the intended statement boundary. It must not be read as a proof of the
cyclotomic Iwasawa main conjecture.
-/
inductive Stage1MachineStatus where
  | statementBoundaryOnly
  | terminalProofClosed
  deriving DecidableEq, Repr

/-- Current repo-local machine status for this Stage1 slot. -/
def currentStage1MachineStatus : Stage1MachineStatus :=
  .statementBoundaryOnly

/-- The current file is explicitly a statement-boundary artifact, not a proof closure. -/
theorem currentStage1MachineStatus_eq_statementBoundaryOnly :
    currentStage1MachineStatus = Stage1MachineStatus.statementBoundaryOnly :=
  rfl

/-!
The declarations above are intentionally weaker than a theorem proving
`StatementShape`. They give the public backfill a checked repo-local name for the
boundary/non-proof distinction while keeping `S1-M-257` open until a real
Iwasawa algebra API, class-group tower API, `p`-adic L-function API, and terminal
proof or pinned upstream dependency are integrated.
-/

/-- Checked mathlib wrapper: the `p`-adic norm of `p` in `ℚ_[p]`. -/
theorem padic_norm_p_mathlib_wrapper (p : ℕ) [Fact p.Prime] :
    ‖(p : ℚ_[p])‖ = (p : ℝ)⁻¹ :=
  Padic.norm_p

/-- Checked mathlib wrapper: the ultrametric inequality on `ℚ_[p]`. -/
theorem padic_nonarchimedean_mathlib_wrapper
    (p : ℕ) [Fact p.Prime] (x y : ℚ_[p]) :
    ‖x + y‖ ≤ max ‖x‖ ‖y‖ :=
  Padic.nonarchimedean x y

/-- Checked mathlib wrapper: nonzero cyclotomic fields are cyclotomic extensions. -/
theorem cyclotomicLayer_isCyclotomicExtension_mathlib_wrapper
    (n : ℕ) [NeZero n] :
    letI : Algebra ℚ (CyclotomicLayer n) := CyclotomicField.algebraBase n ℚ ℚ
    IsCyclotomicExtension {n} ℚ (CyclotomicLayer n) := by
  letI : Algebra ℚ (CyclotomicLayer n) := CyclotomicField.algebraBase n ℚ ℚ
  exact CyclotomicField.isCyclotomicExtension n ℚ

/-- Checked mathlib wrapper: nonzero cyclotomic fields over `ℚ` are abelian Galois. -/
theorem cyclotomicLayer_isAbelianGalois_mathlib_wrapper
    (n : ℕ) [NeZero n] :
    letI : Algebra ℚ (CyclotomicLayer n) := CyclotomicField.algebraBase n ℚ ℚ
    IsAbelianGalois ℚ (CyclotomicLayer n) := by
  letI : Algebra ℚ (CyclotomicLayer n) := CyclotomicField.algebraBase n ℚ ℚ
  letI : IsCyclotomicExtension {n} ℚ (CyclotomicLayer n) :=
    CyclotomicField.isCyclotomicExtension n ℚ
  exact IsCyclotomicExtension.isAbelianGalois {n} ℚ (CyclotomicLayer n)

/-- Checked mathlib wrapper: class groups of rings of integers are available as Lean objects. -/
theorem classGroup_nonempty_mathlib_wrapper
    (K : Type uM) [Field K] [NumberField K] :
    Nonempty (ClassGroup (NumberField.RingOfIntegers K)) :=
  inferInstance

/--
Checked adjacent wrapper: mathlib's complex Dirichlet-character completed
L-function functional equation.

This is an analytic-number-theory anchor adjacent to the Iwasawa main
conjecture. It is not a `p`-adic L-function interpolation theorem.
-/
theorem dirichlet_completed_functional_equation_mathlib_wrapper
    {N : ℕ} [NeZero N] {χ : DirichletCharacter ℂ N}
    (hχ : χ.IsPrimitive) (s : ℂ) :
    completedLFunction χ (1 - s) =
      (N : ℂ) ^ (s - 1 / 2) * rootNumber χ * completedLFunction χ⁻¹ s :=
  hχ.completedLFunction_one_sub s

/-- mathlib modules checked while locating repo-local anchors for this slot. -/
def mathlibAnchorModules : List String := [
  "Mathlib.NumberTheory.Padics.PadicNumbers",
  "Mathlib.NumberTheory.Padics.PadicIntegers",
  "Mathlib.NumberTheory.Cyclotomic.Basic",
  "Mathlib.NumberTheory.Cyclotomic.CyclotomicCharacter",
  "Mathlib.NumberTheory.Cyclotomic.Gal",
  "Mathlib.RingTheory.ClassGroup",
  "Mathlib.NumberTheory.LSeries.DirichletContinuation",
  "Mathlib.NumberTheory.EulerProduct.DirichletLSeries",
  "Mathlib.RingTheory.WittVector.Compare"
]

/-- Search terms that did not locate a terminal Iwasawa-main-conjecture theorem in mathlib. -/
def absentTerminalSearchTerms : List String := [
  "IwasawaMainConjecture",
  "Iwasawa main conjecture",
  "p-adic L-function",
  "padic L-function",
  "pAdicLFunction",
  "PadicLFunction",
  "IwasawaAlgebra",
  "IwasawaModule",
  "characteristic ideal class group"
]

/-! ## External Lean 4 audit boundary -/

/-- Exact external-audit search terms required for `S1-M-257.external-audit`. -/
def externalAuditSearchTerms : List String := [
  "IwasawaMainConjecture",
  "IwasawaAlgebra",
  "IwasawaModule",
  "PadicLFunction",
  "pAdicLFunction",
  "\"p-adic L-function\""
]

/--
Repo-local conclusion of the external-source audit.

The audit found adjacent external Lean work but no repo-local pinned/imported
terminal proof of the cyclotomic Iwasawa main conjecture.
-/
inductive ExternalAuditConclusion where
  | noRepoLocalPinnedTerminalClosure
  deriving DecidableEq, Repr

/-- Current external-audit conclusion for this Stage1 slot. -/
def currentExternalAuditConclusion : ExternalAuditConclusion :=
  .noRepoLocalPinnedTerminalClosure

/-- The external audit has not closed the terminal theorem in this repository. -/
theorem currentExternalAuditConclusion_eq_noRepoLocalPinnedTerminalClosure :
    currentExternalAuditConclusion =
      ExternalAuditConclusion.noRepoLocalPinnedTerminalClosure :=
  rfl

/-! ## Repo-local integration gate -/

/--
Repo-local integration status for any future external Lean 4 closure.

The current value records that no terminal external proof has been pinned,
imported, and validated in this repository. Future work may move through the
explicit pending-blocker state, but only the pinned-and-validated state can be
used as M0387-level completion evidence.
-/
inductive ExternalIntegrationGateStatus where
  | noTerminalClosureFound
  | externalClosurePendingLocalPinOrBlocker
  | externalClosurePinnedAndValidated
  deriving DecidableEq, Repr

/-- Current integration-gate status for this Stage1 slot. -/
def currentExternalIntegrationGateStatus : ExternalIntegrationGateStatus :=
  .noTerminalClosureFound

/--
The current integration gate is open: no external Lean 4 terminal closure has
entered the repo-local Lake validation closure.
-/
theorem currentExternalIntegrationGateStatus_eq_noTerminalClosureFound :
    currentExternalIntegrationGateStatus =
      ExternalIntegrationGateStatus.noTerminalClosureFound :=
  rfl

/-! ## Pinned mathlib audit -/

/-- Pinned mathlib revision audited for the adjacent anchors in this Stage1 slot. -/
def pinnedMathlibRevision : String :=
  "8a178386ffc0f5fef0b77738bb5449d50efeea95"

/-- Exact mathlib anchor names checked against the pinned revision. -/
def checkedMathlibAnchorNames : List String := [
  "Padic.norm_p",
  "Padic.nonarchimedean",
  "cyclotomicCharacter",
  "CyclotomicField.isCyclotomicExtension",
  "IsCyclotomicExtension.isAbelianGalois",
  "ClassGroup.mk0",
  "DirichletCharacter.IsPrimitive.completedLFunction_one_sub"
]

/-- Checked mathlib wrapper: the cyclotomic character exists as a monoid hom. -/
noncomputable def cyclotomicCharacter_mathlib_wrapper (E : Type uM)
    [Field E] (p : ℕ) [Fact p.Prime] :
    (E ≃+* E) →* ℤ_[p]ˣ :=
  cyclotomicCharacter E p

/-- Checked mathlib wrapper: nonzero ideals map to the ideal class group. -/
noncomputable def classGroup_mk0_mathlib_wrapper
    (R : Type uM) [CommRing R] [IsDomain R] [IsDedekindDomain R] :
    (Ideal R)⁰ →* ClassGroup R :=
  ClassGroup.mk0

/-! ## Audit probes -/

#check CyclotomicLayer
#check CyclotomicTowerLayer
#check CyclotomicTowerRingOfIntegers
#check CyclotomicTowerClassGroup
#check cyclotomicTowerLayer_isCyclotomicExtension_mathlib_wrapper
#check cyclotomicTowerClassGroup_nonempty_mathlib_wrapper
#check ClassGroupTowerAPI
#check ClassGroupTowerInverseLimit
#check ClassGroupTowerAPITarget
#check classGroupTowerAPITarget_iff
#check Padic.norm_p
#check Padic.nonarchimedean
#check cyclotomicCharacter
#check CyclotomicField
#check CyclotomicField.isCyclotomicExtension
#check IsCyclotomicExtension.isAbelianGalois
#check ClassGroup
#check ClassGroup.mk0
#check DirichletCharacter.completedLFunction
#check DirichletCharacter.IsPrimitive.completedLFunction_one_sub
#check CharacteristicIdealTheory
#check IwasawaAlgebraAPI
#check IwasawaAlgebraAPITarget
#check iwasawaAlgebraAPITarget_iff
#check IwasawaAlgebraBoundary
#check IwasawaModuleBoundary
#check PadicDistributionModel
#check PadicLFunctionAPI
#check PadicLFunctionAPITarget
#check padicLFunctionAPITarget_iff
#check PadicLFunctionBoundary
#check IwasawaMainConjectureBoundary
#check StatementShape
#check Stage1MachineStatus
#check currentStage1MachineStatus
#check currentStage1MachineStatus_eq_statementBoundaryOnly
#check externalAuditSearchTerms
#check ExternalAuditConclusion
#check currentExternalAuditConclusion
#check currentExternalAuditConclusion_eq_noRepoLocalPinnedTerminalClosure
#check ExternalIntegrationGateStatus
#check currentExternalIntegrationGateStatus
#check currentExternalIntegrationGateStatus_eq_noTerminalClosureFound
#check pinnedMathlibRevision
#check checkedMathlibAnchorNames
#check cyclotomicCharacter_mathlib_wrapper
#check classGroup_mk0_mathlib_wrapper

end S1_M_257
end Stage1
end AwesomeTheorems
