import Mathlib.Analysis.Calculus.VectorField
import Mathlib.Analysis.Distribution.Distribution
import Mathlib.Analysis.Distribution.DerivNotation
import Mathlib.Analysis.FunctionalSpaces.SobolevInequality
import Mathlib.MeasureTheory.Function.LpSpace.Basic

/-!
# S1-M-161 / THM-M-1259: Hörmander subelliptic regularity

This Stage1 artifact records a conservative Lean 4 statement-shape boundary for
the subelliptic regularity theorem associated to Hörmander's bracket condition.

The pinned mathlib snapshot provides vector-field Lie brackets, smoothness
transport for Lie brackets, distributions, line-derivative notation, `MemLp`,
`eLpNorm`, and Sobolev-inequality infrastructure.  It does not provide a
terminal theorem asserting the subelliptic estimate or hypoelliptic regularity
for sums of squares satisfying Hörmander's condition.

Accordingly, the declarations below avoid proof placeholders and completion
claims.  They normalize the object model and record checked wrappers around the
available vector-field and distribution anchors.
-/

noncomputable section

open MeasureTheory
open scoped BigOperators ENNReal NNReal Distributions

namespace AwesomeTheorems
namespace Stage1
namespace S1_M_161

universe u

variable {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- A real vector field on the ambient normed space. -/
abbrev RealVectorField (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E] : Type u :=
  E → E

/-- The mathlib Lie bracket specialized to real vector fields. -/
abbrev LieBracket (V W : RealVectorField E) : RealVectorField E :=
  VectorField.lieBracket ℝ V W

/-- The pointwise span of a family of vector fields at a point. -/
def PointwiseSpan (Γ : Set (RealVectorField E)) (x : E) : Submodule ℝ E :=
  Submodule.span ℝ ((fun V : RealVectorField E => V x) '' Γ)

/--
Hörmander's bracket-generating condition at one point, stated as pointwise
spanning of the tangent space by a selected family of iterated commutators.
-/
def BracketGeneratingAt (Γ : Set (RealVectorField E)) (x : E) : Prop :=
  PointwiseSpan Γ x = ⊤

/--
Syntactic iterated Lie brackets generated by a finite vector-field family.

The depth index records the number of bracket-construction nodes.  Depth `0`
contains the original fields; if `V` and `W` have depths `m` and `k`, their
mathlib Lie bracket has depth `m + k + 1`.
-/
inductive GeneratedLieBracket {n : ℕ} (X : Fin n → RealVectorField E) :
    ℕ → RealVectorField E → Prop where
  | base (i : Fin n) : GeneratedLieBracket X 0 (X i)
  | bracket {m k : ℕ} {V W : RealVectorField E} :
      GeneratedLieBracket X m V → GeneratedLieBracket X k W →
        GeneratedLieBracket X (m + k + 1) (LieBracket V W)

/-- The finite-depth family of iterated Lie brackets generated by `X`. -/
def LieBracketClosureUpToDepth {n : ℕ} (X : Fin n → RealVectorField E) (N : ℕ) :
    Set (RealVectorField E) :=
  { V | ∃ d, d ≤ N ∧ GeneratedLieBracket X d V }

/-- Every original vector field belongs to every finite-depth Lie closure. -/
theorem baseField_mem_lieBracketClosureUpToDepth
    {n : ℕ} (X : Fin n → RealVectorField E) (N : ℕ) (i : Fin n) :
    X i ∈ LieBracketClosureUpToDepth X N := by
  exact ⟨0, Nat.zero_le N, GeneratedLieBracket.base i⟩

/-- A checked Lie bracket of generated fields belongs at the corresponding bounded depth. -/
theorem lieBracket_mem_lieBracketClosureUpToDepth
    {n m k N : ℕ} {X : Fin n → RealVectorField E} {V W : RealVectorField E}
    (hV : GeneratedLieBracket X m V) (hW : GeneratedLieBracket X k W)
    (hN : m + k + 1 ≤ N) :
    LieBracket V W ∈ LieBracketClosureUpToDepth X N := by
  exact ⟨m + k + 1, hN, GeneratedLieBracket.bracket hV hW⟩

/-- The bounded Lie-closure family is monotone in the depth bound. -/
theorem lieBracketClosureUpToDepth_mono
    {n M N : ℕ} {X : Fin n → RealVectorField E}
    (hMN : M ≤ N) :
    LieBracketClosureUpToDepth X M ⊆ LieBracketClosureUpToDepth X N := by
  intro V hV
  rcases hV with ⟨d, hdM, hdV⟩
  exact ⟨d, le_trans hdM hMN, hdV⟩

/--
Finite system of smooth vector fields with its concrete finite-depth bracket
family.

The bracket family is no longer an abstract proposition: it is the checked
finite-depth syntactic closure built from `VectorField.lieBracket`.
-/
structure HormanderVectorFieldSystem (E : Type u)
    [NormedAddCommGroup E] [NormedSpace ℝ E] : Type u where
  fieldCount : ℕ
  fields : Fin fieldCount → RealVectorField E
  smooth : ∀ i, ContDiff ℝ ⊤ (fields i)
  bracketDepth : ℕ

namespace HormanderVectorFieldSystem

/-- The concrete bounded Lie-bracket family generated by the system fields. -/
def bracketFamily (H : HormanderVectorFieldSystem E) : Set (RealVectorField E) :=
  LieBracketClosureUpToDepth H.fields H.bracketDepth

/-- The original fields are contained in the concrete bounded Lie-bracket family. -/
theorem baseFields_subset_bracketFamily
    (H : HormanderVectorFieldSystem E) :
    Set.range H.fields ⊆ H.bracketFamily := by
  rintro V ⟨i, rfl⟩
  exact baseField_mem_lieBracketClosureUpToDepth H.fields H.bracketDepth i

/-- The concrete bracket family is definitionally the chosen finite-depth closure. -/
theorem bracketFamily_eq_lieBracketClosureUpToDepth
    (H : HormanderVectorFieldSystem E) :
    H.bracketFamily = LieBracketClosureUpToDepth H.fields H.bracketDepth :=
  rfl

end HormanderVectorFieldSystem

/-- Directional derivative of a scalar function along a vector field. -/
def DirectionalDerivative (V : RealVectorField E) (u : E → ℝ) : E → ℝ :=
  fun x => fderiv ℝ u x (V x)

/-- Sum-of-squares second-order operator associated to a finite vector-field system. -/
def SumOfSquaresOperator {n : ℕ} (X : Fin n → RealVectorField E) (u : E → ℝ) : E → ℝ :=
  fun x => ∑ i, DirectionalDerivative (X i) (DirectionalDerivative (X i) u) x

/-- Scalar distributions on an open domain, using mathlib's distribution object. -/
abbrev ScalarDistributionOn (Ω : TopologicalSpace.Opens E) (n : ℕ∞ := ⊤) : Type u :=
  Distribution Ω ℝ n

/--
The test-function side of a vector-field derivative on an open set.

For a smooth compactly supported test function `φ`, `testDerivative φ` is the
test function whose value is the classical derivative of `φ` along `V`.  The
existence of this bundled test function carries the compact-support and support
inside `Ω` obligations that are nontrivial for variable-coefficient vector
fields.
-/
structure TestFunctionVectorFieldDerivative
    (Ω : TopologicalSpace.Opens E) (V : RealVectorField E) : Type u where
  testDerivative : 𝓓(Ω, ℝ) → 𝓓(Ω, ℝ)
  testDerivative_apply :
    ∀ (φ : 𝓓(Ω, ℝ)) (x : E),
      testDerivative φ x = fderiv ℝ (φ : E → ℝ) x (V x)

/--
Distributional derivative along a vector field, defined by transposition on
test functions.

`dT` is the derivative of the scalar distribution `T` along `V` when it acts on
every test function by the negative transpose of the bundled vector-field
derivative on test functions.
-/
def DistributionalVectorFieldDerivative
    {Ω : TopologicalSpace.Opens E} {V : RealVectorField E}
    (testDerivative : TestFunctionVectorFieldDerivative Ω V)
    (T dT : ScalarDistributionOn Ω) : Prop :=
  ∀ φ : 𝓓(Ω, ℝ), dT φ = -T (testDerivative.testDerivative φ)

/--
Concrete distributional sum-of-squares weak equation for a finite vector-field
system.

The equation says that each first and second field derivative is represented by
the transposed test-function derivative, and that the finite sum of the second
field derivatives is the right-hand-side distribution.
-/
def DistributionalSumOfSquaresEquation
    {Ω : TopologicalSpace.Opens E} {n : ℕ}
    {X : Fin n → RealVectorField E}
    (testDerivative : ∀ i : Fin n, TestFunctionVectorFieldDerivative Ω (X i))
    (solutionDistribution rhsDistribution : ScalarDistributionOn Ω)
    (firstFieldDerivatives secondFieldDerivatives : Fin n → ScalarDistributionOn Ω) : Prop :=
  (∀ i, DistributionalVectorFieldDerivative (testDerivative i)
    solutionDistribution (firstFieldDerivatives i)) ∧
  (∀ i, DistributionalVectorFieldDerivative (testDerivative i)
    (firstFieldDerivatives i) (secondFieldDerivatives i)) ∧
  (∑ i, secondFieldDerivatives i) = rhsDistribution

/--
Concrete bridge from an ordinary scalar function to its scalar distribution on
an open domain, against all smooth compactly supported test functions.
-/
def RepresentsFunctionAsDistribution
    [MeasurableSpace E]
    (Ω : TopologicalSpace.Opens E) (μ : Measure E)
    (f : E → ℝ) (T : ScalarDistributionOn Ω) : Prop :=
  ∀ φ : 𝓓(Ω, ℝ), T φ = ∫ x, φ x * f x ∂μ

/-- Concrete distribution bridge for the solution and right-hand side functions. -/
def DistributionBridge
    [MeasurableSpace E]
    (Ω : TopologicalSpace.Opens E) (μ : Measure E)
    (solution rhs : E → ℝ)
    (solutionDistribution rhsDistribution : ScalarDistributionOn Ω) : Prop :=
  RepresentsFunctionAsDistribution Ω μ solution solutionDistribution ∧
  RepresentsFunctionAsDistribution Ω μ rhs rhsDistribution

/--
Positive subelliptic gain parameter.

For Hörmander's estimate this is the `ε` in a local `H^ε` gain.  The upper
bound by `1` records that the local gain is fractional/first-order at this
Stage1 boundary; the analytic theorem determining the optimal gain from the
bracket depth remains a later PDE proof leaf.
-/
structure SubellipticGainParameter : Type where
  epsilon : ℝ≥0
  epsilon_pos : 0 < epsilon
  epsilon_le_one : epsilon ≤ 1

/-- Cutoff localization of an ordinary scalar function. -/
def CutoffLocalizedFunction (cutoff u : E → ℝ) : E → ℝ :=
  fun x => cutoff x * u x

/-- Concrete localized `L^2` seminorm encoded with mathlib's `eLpNorm`. -/
def LocalL2Norm
    [MeasurableSpace E] (μ : Measure E) (cutoff : E → ℝ) (u : E → ℝ) :
    ℝ≥0∞ :=
  eLpNorm (CutoffLocalizedFunction cutoff u) 2 μ

/--
Finite-probe local Sobolev norm at a fixed subelliptic gain.

The probes are bundled operators on localized scalar functions.  This keeps the
norm concrete as a finite sum of `eLpNorm` terms while avoiding a false claim
that mathlib already supplies the full fractional Sobolev/Bessel-potential API
needed for the terminal Hörmander proof.
-/
structure LocalSobolevGainModel
    [MeasurableSpace E] (μ : Measure E) : Type u where
  gain : SubellipticGainParameter
  probeCount : ℕ
  probes : Fin probeCount → (E → ℝ) → E → ℝ
  probeOrder : Fin probeCount → ℝ≥0
  probeOrder_le_gain : ∀ j, probeOrder j ≤ gain.epsilon

/-- The concrete finite-probe localized Sobolev norm selected by a gain model. -/
def LocalSobolevGainNorm
    [MeasurableSpace E] {μ : Measure E}
    (M : LocalSobolevGainModel (E := E) μ)
    (cutoff : E → ℝ) (u : E → ℝ) : ℝ≥0∞ :=
  LocalL2Norm μ cutoff u +
    ∑ j : Fin M.probeCount,
      eLpNorm (M.probes j (CutoffLocalizedFunction cutoff u)) 2 μ

/--
Concrete horizontal first-order norm associated to the finite vector-field
system.  This is the right-side control norm used in the local subelliptic
estimate certificate.
-/
def LocalHorizontalSobolevNorm
    [MeasurableSpace E] {n : ℕ}
    (μ : Measure E) (cutoff : E → ℝ) (X : Fin n → RealVectorField E)
    (u : E → ℝ) : ℝ≥0∞ :=
  LocalL2Norm μ cutoff u +
    ∑ i : Fin n, LocalL2Norm μ cutoff (DirectionalDerivative (X i) u)

/--
Concrete local subelliptic estimate certificate.

The left side is the finite-probe localized Sobolev gain norm for the solution.
The right side is the localized `L^2` norm of the right-hand side plus the
horizontal first-order norm of the solution on a larger cutoff.  Supplying this
certificate is still an unchecked analytic PDE leaf; the type itself is checked
repo-locally and replaces the previous raw `Prop` estimate slot.
-/
structure LocalSubellipticEstimate
    [MeasurableSpace E] {n : ℕ}
    (μ : Measure E) (X : Fin n → RealVectorField E)
    (solution rhs : E → ℝ) : Type u where
  sobolevModel : LocalSobolevGainModel (E := E) μ
  innerCutoff : E → ℝ
  outerCutoff : E → ℝ
  constant : ℝ≥0∞

namespace LocalSubellipticEstimate

/-- The inequality proposition asserted by a concrete local estimate package. -/
def Holds
    [MeasurableSpace E] {n : ℕ}
    {μ : Measure E} {X : Fin n → RealVectorField E}
    {solution rhs : E → ℝ}
    (A : LocalSubellipticEstimate μ X solution rhs) : Prop :=
    LocalSobolevGainNorm A.sobolevModel A.innerCutoff solution ≤
      A.constant *
        (LocalL2Norm μ A.outerCutoff rhs +
          LocalHorizontalSobolevNorm μ A.outerCutoff X solution)

end LocalSubellipticEstimate

/--
Data needed to state a Hörmander subelliptic regularity theorem.

The weak equation and distribution-function bridge are no longer opaque
proposition fields: the data package stores the bundled test-function
vector-field derivatives, the first/second distributional field derivatives
needed to state the concrete distributional sum-of-squares equation over
`Distribution Ω ℝ ⊤`, and a concrete local subelliptic estimate certificate.
-/
structure SubellipticRegularityData (E : Type u)
    [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E] : Type u where
  domain : TopologicalSpace.Opens E
  measure : Measure E
  system : HormanderVectorFieldSystem E
  solution : E → ℝ
  rhs : E → ℝ
  solutionDistribution : ScalarDistributionOn domain
  rhsDistribution : ScalarDistributionOn domain
  testDerivative :
    ∀ i : Fin system.fieldCount,
      TestFunctionVectorFieldDerivative domain (system.fields i)
  firstFieldDerivatives : Fin system.fieldCount → ScalarDistributionOn domain
  secondFieldDerivatives : Fin system.fieldCount → ScalarDistributionOn domain
  bracketGeneratingOnDomain :
    ∀ x : E, x ∈ (domain : Set E) → BracketGeneratingAt system.bracketFamily x
  rhsSmooth : ContDiffOn ℝ ⊤ rhs (domain : Set E)
  subellipticEstimateCertificate : LocalSubellipticEstimate measure system.fields solution rhs

namespace SubellipticRegularityData

/-- The concrete distributional weak equation carried by a data package. -/
def weakEquation
    [MeasurableSpace E] (D : SubellipticRegularityData E) : Prop :=
  DistributionalSumOfSquaresEquation D.testDerivative D.solutionDistribution
    D.rhsDistribution D.firstFieldDerivatives D.secondFieldDerivatives

/-- The concrete function-to-distribution bridge carried by a data package. -/
def distributionBridge
    [MeasurableSpace E] (D : SubellipticRegularityData E) : Prop :=
  DistributionBridge D.domain D.measure D.solution D.rhs
    D.solutionDistribution D.rhsDistribution

/-- The concrete subelliptic estimate proposition carried by a data package. -/
def subellipticEstimate
    [MeasurableSpace E] (D : SubellipticRegularityData E) : Prop :=
  D.subellipticEstimateCertificate.Holds

end SubellipticRegularityData

/-- The hypotheses side of the normalized Stage1 statement shape. -/
def SubellipticRegularityHypotheses
    {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E]
    (D : SubellipticRegularityData E) : Prop :=
  D.weakEquation ∧ D.distributionBridge ∧ D.subellipticEstimate

/-- The regularity conclusion carried by Hörmander's theorem. -/
def SmoothRegularityConclusion
    {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E]
    (D : SubellipticRegularityData E) : Prop :=
  ContDiffOn ℝ ⊤ D.solution (D.domain : Set E)

/--
Stage1 normalized statement shape for Hörmander subelliptic regularity.

For every open domain, finite smooth vector-field system satisfying the
bracket-generating condition, weak equation, distribution bridge, and
subelliptic estimate, the distributional solution is smooth on the domain.
-/
def StatementShape
    (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E] : Prop :=
  ∀ D : SubellipticRegularityData E,
    SubellipticRegularityHypotheses D → SmoothRegularityConclusion D

/-- The statement shape unfolds to the expected implication over all data packages. -/
theorem statementShape_iff_forall_data
    (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E] :
    StatementShape E ↔
      ∀ D : SubellipticRegularityData E,
        SubellipticRegularityHypotheses D → SmoothRegularityConclusion D :=
  Iff.rfl

/-- The real Lie bracket abbreviation is definitionally the mathlib vector-field bracket. -/
theorem lieBracket_eq_mathlib (V W : RealVectorField E) :
    LieBracket V W = VectorField.lieBracket ℝ V W :=
  rfl

/-- The real vector-field Lie bracket unfolds to the Fréchet-derivative commutator formula. -/
theorem lieBracket_eq_formula (V W : RealVectorField E) :
    LieBracket V W =
      fun x => fderiv ℝ W x (V x) - fderiv ℝ V x (W x) :=
  VectorField.lieBracket_eq

/-- The Lie bracket of a vector field with itself is zero. -/
theorem lieBracket_self_zero (V : RealVectorField E) :
    LieBracket V V = 0 :=
  VectorField.lieBracket_self

/-- Smooth vector fields have a smooth Lie bracket in mathlib's vector-space API. -/
theorem contDiff_lieBracket_of_contDiff (V W : RealVectorField E)
    (hV : ContDiff ℝ ⊤ V) (hW : ContDiff ℝ ⊤ W) :
    ContDiff ℝ ⊤ (LieBracket V W) := by
  exact hV.lieBracket_vectorField hW (by simp)

/-- Every original vector field lies in the pointwise span of the selected bracket family. -/
theorem baseField_mem_pointwiseSpan
    (H : HormanderVectorFieldSystem E) (i : Fin H.fieldCount) (x : E) :
    H.fields i x ∈ PointwiseSpan H.bracketFamily x := by
  exact Submodule.subset_span
    ⟨H.fields i,
      HormanderVectorFieldSystem.baseFields_subset_bracketFamily H (Set.mem_range_self i), rfl⟩

/-- System-level restatement of the concrete finite-depth closure definition. -/
theorem bracketFamily_eq_concrete_closure
    (H : HormanderVectorFieldSystem E) :
    H.bracketFamily = LieBracketClosureUpToDepth H.fields H.bracketDepth :=
  HormanderVectorFieldSystem.bracketFamily_eq_lieBracketClosureUpToDepth H

/-- System base fields are generated Lie brackets of depth zero. -/
theorem system_baseField_generated
    (H : HormanderVectorFieldSystem E) (i : Fin H.fieldCount) :
    GeneratedLieBracket H.fields 0 (H.fields i) :=
  GeneratedLieBracket.base i

/-- The bracket-generating predicate is exactly the top-span condition. -/
theorem bracketGeneratingAt_iff_pointwiseSpan_top
    (Γ : Set (RealVectorField E)) (x : E) :
    BracketGeneratingAt Γ x ↔ PointwiseSpan Γ x = ⊤ :=
  Iff.rfl

/-- The data package exposes the bracket-generating condition at domain points. -/
theorem bracketGeneratingAt_of_data
    [MeasurableSpace E] (D : SubellipticRegularityData E)
    {x : E} (hx : x ∈ (D.domain : Set E)) :
    BracketGeneratingAt D.system.bracketFamily x :=
  D.bracketGeneratingOnDomain x hx

/-- The hypotheses side projects to the weak-equation field. -/
theorem SubellipticRegularityHypotheses.weakEquation
    [MeasurableSpace E] {D : SubellipticRegularityData E}
    (h : SubellipticRegularityHypotheses D) :
    D.weakEquation :=
  h.1

/-- The hypotheses side projects to the distribution/function bridge field. -/
theorem SubellipticRegularityHypotheses.distributionBridge
    [MeasurableSpace E] {D : SubellipticRegularityData E}
    (h : SubellipticRegularityHypotheses D) :
    D.distributionBridge :=
  h.2.1

/-- The hypotheses side projects to the abstract subelliptic-estimate field. -/
theorem SubellipticRegularityHypotheses.subellipticEstimate
    [MeasurableSpace E] {D : SubellipticRegularityData E}
    (h : SubellipticRegularityHypotheses D) :
    D.subellipticEstimate :=
  h.2.2

/-- mathlib modules checked while locating repo-local anchors for this slot. -/
def mathlibAnchorModules : List String := [
  "Mathlib.Analysis.Calculus.VectorField",
  "Mathlib.Geometry.Manifold.VectorField.LieBracket",
  "Mathlib.Geometry.Manifold.Algebra.LeftInvariantDerivation",
  "Mathlib.Analysis.Distribution.Distribution",
  "Mathlib.Analysis.Distribution.DerivNotation",
  "Mathlib.Analysis.Distribution.TestFunction",
  "Mathlib.Analysis.Distribution.SchwartzSpace.Deriv",
  "Mathlib.Analysis.FunctionalSpaces.SobolevInequality",
  "Mathlib.MeasureTheory.Function.LpSpace.Basic",
  "Mathlib.MeasureTheory.Function.LpSeminorm.Basic"
]

/-- Pinned theorem and definition names used or audited for this Stage1 slot. -/
def mathlibAnchorNames : List String := [
  "VectorField.lieBracket",
  "VectorField.lieBracket_eq",
  "VectorField.lieBracket_self",
  "ContDiff.lieBracket_vectorField",
  "VectorField.leibniz_identity_lieBracket",
  "Distribution",
  "Distribution.mapCLM",
  "LineDeriv.iteratedLineDerivOp",
  "MeasureTheory.MemLp",
  "MeasureTheory.eLpNorm",
  "MeasureTheory.eLpNorm_le_eLpNorm_fderiv",
  "MeasureTheory.eLpNorm_le_eLpNorm_fderiv_of_eq"
]

/--
Search terms that did not locate a terminal Hörmander subelliptic regularity
theorem in local mathlib.
-/
def absentTerminalSearchTerms : List String := [
  "Hörmander",
  "Hormander",
  "subelliptic",
  "sub-elliptic",
  "hypoelliptic",
  "hypo-elliptic",
  "bracket generating",
  "bracket-generating",
  "sum of squares",
  "PDE regularity",
  "pseudodifferential"
]

/-- Date of the refreshed public Lean 4 external-anchor audit for this child leaf. -/
def externalLean4AuditDate : String :=
  "2026-05-01"

/-- Public and repo-local search surfaces checked for a terminal Lean 4 proof. -/
def externalLean4AuditCheckedSurfaces : List String := [
  "Pinned repo-local mathlib source search under Formalizations/Lean/.lake/packages/mathlib/Mathlib for Hormander/Hörmander/subelliptic/hypoelliptic/bracket-generating/sum-of-squares PDE terms.",
  "Repo-local AwesomeTheorems Stage1 Lean source search for the same terminal theorem terms.",
  "LeanSearch query: Hormander subelliptic hypoelliptic bracket generating sum of squares.",
  "LeanSearch query: Hörmander theorem subelliptic regularity.",
  "LeanSearch query: hypoelliptic differential operator distribution smooth regularity.",
  "GitHub repository API searches for Hormander+Lean, subelliptic+Lean, and hypoelliptic+Lean.",
  "GitHub code-search API probes for Hormander/subelliptic/hypoelliptic with language:Lean were attempted, but unauthenticated code search was rate-limited in this environment."
]

/-- Refreshed audit result for the terminal external Lean 4 theorem search. -/
def externalLean4AuditResult : String :=
  "no terminal public Lean 4 Hormander/subelliptic/hypoelliptic theorem found in accessible audited surfaces; no external theorem was available to pin/import/check"

/--
External Lean 4 anchor audit for this slot.

This module does not import an external project proving the terminal
Hörmander subelliptic regularity theorem.  If a later audit finds such a
project, completion requires a pinned dependency, vendored proof body, or
checked wrapper in this repository's Lake closure.
-/
def externalLean4AnchorAudit : List String := [
  "No terminal Lean 4 Hormander subelliptic regularity proof is imported by this repo-local Lake closure.",
  "No external Lean 4 project, commit, module, and theorem name has been identified here as a checked terminal closure.",
  "Public LeanSearch and GitHub repository searches refreshed on 2026-05-01 found mathlib analysis anchors and unrelated results, but no importable Lean 4 terminal theorem.",
  "Unauthenticated GitHub code-search API probes were rate-limited on 2026-05-01; an authenticated code-search rerun remains a concrete audit hardening step, not evidence of an existing external proof.",
  "Any later external upstream candidate must be pinned/imported/checked or recorded as a concrete integration blocker before completion."
]

/-- M0387 machine-proof debt classification for the current Stage1 artifact. -/
def machineProofDebtClassification : String :=
  "formalization_debt: human PDE theorem known, but no repo-local Lean proof body, mathlib terminal theorem, or pinned external Lean 4 closure proves StatementShape"

/--
Repo-local integration gate for completion claims.

The slot is not completed by this statement-shape artifact.  No completed state
therefore retains `repo_local_integration_debt`; anchor-only evidence, if found
later, must be converted to pin/import/check or to an explicit blocker.
-/
def repoLocalIntegrationDebtGate : String :=
  "not_completed; no completed-state repo_local_integration_debt retained"

/--
Explicit Stage1 checklist gate for the terminal-closure child leaf.

This is metadata, not a proof of `StatementShape`: it records that the public
checklist must stay open until a local proof body, pinned mathlib wrapper, or
pinned/imported/checked external Lean 4 proof is in the repo-local validation
closure.
-/
def stage1ChecklistOpenUntilTerminalClosureGate : List String := [
  "public checklist status: open",
  "do not mark S1-M-161 completed from statement-shape, anchor-only, or audit metadata",
  "closure condition: terminal local proof body, pinned mathlib wrapper, or pinned/imported/checked external Lean 4 proof validates in the repo-local Lake closure",
  "current blocker: no such terminal proof body or pinned external closure is present in this artifact",
  "current debt: formalization_debt, not completed repo_local_integration_debt"
]

/-- Exact repo-local validation command requested for the public Stage1 backfill. -/
def repoLocalValidationCommand : String :=
  "cd Formalizations/Lean && lake env lean AwesomeTheorems/Stage1/S1_M_161.lean"

/-- Date on which the validation command and revisions were observed for this child leaf. -/
def repoLocalValidationDate : String :=
  "2026-05-01"

/-- Observed Lean toolchain from `Formalizations/Lean/lean-toolchain`. -/
def observedLeanToolchain : String :=
  "leanprover/lean4:v4.29.0"

/-- Observed Lean compiler revision from `lake env lean --version`. -/
def observedLeanCompilerRevision : String :=
  "Lean 4.29.0, commit 98dc76e3c0a9b856c9b98726b713fb04fab16740"

/-- Observed pinned mathlib revision from `lake-manifest.json` and `lakefile.lean`. -/
def observedMathlibRevision : String :=
  "8a178386ffc0f5fef0b77738bb5449d50efeea95"

/-- Repo-local validation result recorded for the public validation backfill leaf. -/
def repoLocalValidationRecord : List String := [
  "command: cd Formalizations/Lean && lake env lean AwesomeTheorems/Stage1/S1_M_161.lean",
  "result: passed on 2026-05-01",
  "Lean toolchain: leanprover/lean4:v4.29.0",
  "Lean compiler revision: 98dc76e3c0a9b856c9b98726b713fb04fab16740",
  "mathlib revision: 8a178386ffc0f5fef0b77738bb5449d50efeea95",
  "scope: statement-shape artifact only; not a terminal Hormander proof"
]

/-- Public theorem-tree packages proposed for the serialized Stage1 backfill. -/
def publicTheoremTreePackages : List String := [
  "P1_statement_normalization: normalize ambient space, open domain, vector-field system, bracket-generating hypothesis, weak-equation inputs, subelliptic estimate input, and smoothness conclusion; statement-shape wrappers checked locally",
  "P2_mathlib_object_model: align the local statement with mathlib anchors for VectorField.lieBracket, Distribution, LineDeriv, MemLp, eLpNorm, and Sobolev infrastructure; low-risk wrappers checked locally",
  "P3_bracket_generation: abstract generatedByFieldsUpToDepth Prop replaced by a concrete finite-depth iterated Lie-bracket closure object over VectorField.lieBracket; closure object, base membership, bracket construction, and depth monotonicity checked locally; domain-generation equivalence remains unchecked",
  "P4_operator_distribution_bridge: replace abstract weakEquation and distributionBridge fields by distributional vector-field derivative and sum-of-squares operator definitions over Distribution Ω ℝ ⊤; nontrivial PDE bridge leaves unchecked",
  "P5_subelliptic_estimate: abstract subellipticEstimate Prop replaced by a concrete local estimate certificate with positive gain parameter, cutoff-localized eLpNorm L2 norm, finite-probe Sobolev gain norm, and horizontal vector-field control norm; analytic estimate proof leaves unchecked",
  "P6_regularization_bootstrap: derive Sobolev gain iteration, local regularity, and smooth representative/hypoellipticity from the weak equation and estimate; nontrivial PDE proof leaves unchecked",
  "P7_repo_local_closure: close by local proof body, pinned mathlib wrapper, or pinned/imported/checked external Lean 4 proof; terminal closure unchecked"
]

/-- M0387 public leaf-status inventory; nontrivial PDE leaves remain unchecked. -/
def publicTheoremTreeLeafStatuses : List String := [
  "P1.L001 checked locally: RealVectorField, LieBracket, PointwiseSpan, BracketGeneratingAt, SubellipticRegularityData, and StatementShape normalize without placeholders",
  "P2.L001 checked locally: LieBracket unfolds to VectorField.lieBracket and the commutator formula",
  "P2.L002 checked locally: LieBracket self-zero and ContDiff.lieBracket_vectorField wrapper validate against pinned mathlib",
  "P3.L001 checked locally: GeneratedLieBracket and LieBracketClosureUpToDepth define the finite-depth iterated Lie-bracket closure object over VectorField.lieBracket",
  "P3.L002 checked locally: base membership, checked bracket construction at depth m + k + 1, depth monotonicity, and system-level bracketFamily equality validate without placeholders",
  "P3.L003 unchecked: equivalence between the concrete closure object and bracket generation on the open domain",
  "P4.L001 checked locally: DistributionalVectorFieldDerivative defines vector-field derivatives on Distribution Ω ℝ ⊤ by transposition against bundled test-function derivatives",
  "P4.L002 checked locally: DistributionalSumOfSquaresEquation replaces the abstract weakEquation field by first/second distributional field derivatives and a finite sum equality",
  "P4.L003 checked locally: DistributionBridge replaces the abstract distributionBridge field by test-function integral identities for the solution and right-hand side",
  "P4.L004 unchecked: analytic construction of the bundled variable-coefficient test-function derivative operator from smooth vector fields",
  "P4.L005 unchecked: proof that classical directional derivatives of locally integrable representatives match the distributional derivatives",
  "P5.L001 checked locally: SubellipticGainParameter, CutoffLocalizedFunction, LocalL2Norm, LocalSobolevGainModel, LocalSobolevGainNorm, LocalHorizontalSobolevNorm, and LocalSubellipticEstimate.Holds define the concrete local norm/gain estimate package without placeholders",
  "P5.L002 unchecked: compactly supported core subelliptic estimate",
  "P5.L003 unchecked: cutoff/localization transport for the estimate",
  "P6.L001 unchecked: Sobolev-gain bootstrap and iteration",
  "P6.L002 unchecked: distributional regularity to smooth representative on the domain",
  "P7.L001 unchecked: terminal local proof body or pinned/imported/checked external proof in repo-local Lake closure"
]

/-- M0387-level theorem-internal child leaves for later module splitting. -/
def theoremInternalChildLeaves : List String := [
  "S1-M-161.L01.statement_normalization: freeze universe, domain, vector-field, distribution, weak-equation, estimate, and smoothness target; <=100-step ledger after concrete APIs are selected",
  "S1-M-161.L02.mathlib_anchor_audit: maintain exact module/theorem table for vector fields, Lie brackets, distributions, Sobolev/Lp APIs, and absent terminal theorem searches",
  "S1-M-161.L03.bracket_closure_model: concrete finite-depth Lie-closure object, base membership, bracket construction, monotonicity, and system equality checked locally; remaining child leaf is the domain bracket-generation equivalence",
  "S1-M-161.L04.operator_distribution_bridge: distributional vector-field derivative, sum-of-squares weak equation, and function/distribution bridge definitions checked locally; remaining child leaves are analytic construction and bridge proofs in <=100-step units",
  "S1-M-161.L05.subelliptic_estimate_package: concrete gain parameter, cutoff-localized L2 norm, finite-probe Sobolev gain norm, horizontal vector-field norm, and local estimate predicate checked locally; remaining child leaves are the compact-support estimate proof and localization transport",
  "S1-M-161.L06.regularity_bootstrap: split weak-to-Sobolev gain, iteration, localization, and smoothness conclusion into independent <=100-step leaves",
  "S1-M-161.L07.external_dependency_gate: if an external Lean 4 proof is found, pin/import/check it or record a concrete integration blocker before any completion claim",
  "S1-M-161.L08.public_surface_sync: merge checked facts into the authorized public Stage1 surface only after validation, leaf ledgers, and status surfaces agree"
]

/-! ## Audit probes -/

#check VectorField.lieBracket
#check ContDiff.lieBracket_vectorField
#check Distribution
#check LineDeriv.iteratedLineDerivOp
#check GeneratedLieBracket
#check LieBracketClosureUpToDepth
#check baseField_mem_lieBracketClosureUpToDepth
#check lieBracket_mem_lieBracketClosureUpToDepth
#check lieBracketClosureUpToDepth_mono
#check TestFunctionVectorFieldDerivative
#check DistributionalVectorFieldDerivative
#check DistributionalSumOfSquaresEquation
#check RepresentsFunctionAsDistribution
#check DistributionBridge
#check SubellipticGainParameter
#check CutoffLocalizedFunction
#check LocalL2Norm
#check LocalSobolevGainModel
#check LocalSobolevGainNorm
#check LocalHorizontalSobolevNorm
#check LocalSubellipticEstimate
#check LocalSubellipticEstimate.Holds
#check bracketFamily_eq_concrete_closure
#check StatementShape
#check externalLean4AuditDate
#check externalLean4AuditCheckedSurfaces
#check externalLean4AuditResult
#check machineProofDebtClassification
#check repoLocalIntegrationDebtGate
#check stage1ChecklistOpenUntilTerminalClosureGate
#check repoLocalValidationCommand
#check repoLocalValidationDate
#check observedLeanToolchain
#check observedLeanCompilerRevision
#check observedMathlibRevision
#check repoLocalValidationRecord
#check publicTheoremTreePackages
#check publicTheoremTreeLeafStatuses
#check theoremInternalChildLeaves

end S1_M_161
end Stage1
end AwesomeTheorems
