import Mathlib.Data.Int.Basic
import Mathlib.Tactic

/-!
# S1-M-020 / THM-M-0389: Markov equation

This Stage1 artifact records a conservative Lean 4 statement shape for the
integer solutions of the Markov equation

`x^2 + y^2 + z^2 = 3xyz`.

The file is not a proof of Markov's classification theorem.  The local mathlib
audit did not find a terminal theorem classifying all integer Markov triples, so
the classification target is exposed as a `Prop` and accompanied only by small
checked algebraic wrappers for the equation, the seed solution, sign symmetries,
and the standard Markov mutations.
-/

namespace AwesomeTheorems
namespace Stage1
namespace S1_M_020

/-- The integer Markov equation `x^2 + y^2 + z^2 = 3xyz`. -/
def MarkovEquation (x y z : ℤ) : Prop :=
  x ^ 2 + y ^ 2 + z ^ 2 = 3 * x * y * z

/-! ## Statement-normalization targets -/

/--
Canonical integer statement predicate for the Markov equation.

`MarkovEquation` is retained as the older local name; `MarkovEqInt` is the
public-normalization name requested for the Stage1 blueprint backfill.
-/
abbrev MarkovEqInt (x y z : ℤ) : Prop :=
  MarkovEquation x y z

/--
The usual mutation/permutation closure starting from `(1, 1, 1)`.

This is a statement-shape object: later proof work must show that its positive
part is exactly the positive integer solution set.
-/
inductive GeneratedMarkovTriple : ℤ → ℤ → ℤ → Prop
  | seed : GeneratedMarkovTriple 1 1 1
  | swap_xy {x y z : ℤ} :
      GeneratedMarkovTriple x y z → GeneratedMarkovTriple y x z
  | swap_yz {x y z : ℤ} :
      GeneratedMarkovTriple x y z → GeneratedMarkovTriple x z y
  | mutate_x {x y z : ℤ} :
      GeneratedMarkovTriple x y z → GeneratedMarkovTriple (3 * y * z - x) y z
  | mutate_y {x y z : ℤ} :
      GeneratedMarkovTriple x y z → GeneratedMarkovTriple x (3 * x * z - y) z
  | mutate_z {x y z : ℤ} :
      GeneratedMarkovTriple x y z → GeneratedMarkovTriple x y (3 * x * y - z)

/--
Integer sign variants preserving the equation: either all signs are unchanged,
or exactly two signs are changed.  The zero solution is handled separately in
`StatementShape`.
-/
def EvenSignVariant (x y z a b c : ℤ) : Prop :=
  (x = a ∧ y = b ∧ z = c) ∨
  (x = a ∧ y = -b ∧ z = -c) ∨
  (x = -a ∧ y = b ∧ z = -c) ∨
  (x = -a ∧ y = -b ∧ z = c)

/--
Coordinate permutations of a triple.

This is separated from `EvenSignVariant` so the integer-lift proof tree can
track permutation closure and sign normalization as distinct leaves.
-/
def CoordinatePermutationVariant (x y z a b c : ℤ) : Prop :=
  (x = a ∧ y = b ∧ z = c) ∨
  (x = a ∧ y = c ∧ z = b) ∨
  (x = b ∧ y = a ∧ z = c) ∨
  (x = b ∧ y = c ∧ z = a) ∨
  (x = c ∧ y = a ∧ z = b) ∨
  (x = c ∧ y = b ∧ z = a)

/-- Strict positivity for an integer triple. -/
def PositiveIntTriple (x y z : ℤ) : Prop :=
  0 < x ∧ 0 < y ∧ 0 < z

/--
Positive-generation target for Markov triples.

This is the hard Vieta-descent direction: every strictly positive integer
solution should lie in the mutation/permutation closure generated by `(1,1,1)`.
It is exposed as a `Prop` only; this Stage1 artifact does not prove it.
-/
def PositiveGenerationTarget : Prop :=
  ∀ x y z : ℤ,
    MarkovEqInt x y z →
      PositiveIntTriple x y z →
        GeneratedMarkovTriple x y z

/-! ## P3-P5 positive Vieta-descent proof-tree targets -/

/-- Nondecreasing strictly-positive integer solution used by the Vieta descent branch. -/
def OrderedPositiveMarkovTriple (x y z : ℤ) : Prop :=
  MarkovEqInt x y z ∧ PositiveIntTriple x y z ∧ x ≤ y ∧ y ≤ z

/-- The third-coordinate Vieta descendant of `(x,y,z)`. -/
def VietaDescendantZ (x y z : ℤ) : ℤ :=
  3 * x * y - z

/-- Additive height used for the positive descent tree. -/
def PositiveMarkovHeight (x y z : ℤ) : ℤ :=
  x + y + z

/-- P3 leaf target: isolate the ordered `x = 1` branch. -/
def P3_x_eq_one_branch_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      x = 1 →
        (y = 1 ∧ z = 1) ∨
        (0 < VietaDescendantZ x y z ∧ VietaDescendantZ x y z < z)

/-- P3 leaf target: the third-coordinate Vieta descendant is positive. -/
def P3_descendant_positive_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      ¬ (x = 1 ∧ y = 1 ∧ z = 1) →
        0 < VietaDescendantZ x y z

/-- P3 leaf target: the third-coordinate Vieta descendant is smaller than `z`. -/
def P3_descendant_lt_top_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      ¬ (x = 1 ∧ y = 1 ∧ z = 1) →
        VietaDescendantZ x y z < z

/-- P3 checked leaf: the Vieta descendant still satisfies the Markov equation. -/
def P3_descendant_markov_target : Prop :=
  ∀ x y z : ℤ,
    MarkovEqInt x y z →
      MarkovEqInt x y (VietaDescendantZ x y z)

/-- P3 leaf target: reorder a positive descendant back into nondecreasing form. -/
def P3_descendant_reorder_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      0 < VietaDescendantZ x y z →
        ∃ a b c : ℤ,
          OrderedPositiveMarkovTriple a b c ∧
          ((a = x ∧ b = y ∧ c = VietaDescendantZ x y z) ∨
           (a = x ∧ b = VietaDescendantZ x y z ∧ c = y) ∨
           (a = VietaDescendantZ x y z ∧ b = x ∧ c = y))

/-- One ordered positive Vieta-descent step after reordering the descendant. -/
def OrderedVietaDescentStep (x y z a b c : ℤ) : Prop :=
  OrderedPositiveMarkovTriple x y z ∧
  0 < VietaDescendantZ x y z ∧
  VietaDescendantZ x y z < z ∧
  OrderedPositiveMarkovTriple a b c ∧
  ((a = x ∧ b = y ∧ c = VietaDescendantZ x y z) ∨
   (a = x ∧ b = VietaDescendantZ x y z ∧ c = y) ∨
   (a = VietaDescendantZ x y z ∧ b = x ∧ c = y))

/-- Finite ordered positive descent chain from one ordered triple to another. -/
inductive OrderedVietaDescentChain : ℤ → ℤ → ℤ → ℤ → ℤ → ℤ → Prop
  | refl {x y z : ℤ} :
      OrderedPositiveMarkovTriple x y z →
        OrderedVietaDescentChain x y z x y z
  | cons {x y z a b c u v w : ℤ} :
      OrderedVietaDescentStep x y z a b c →
        OrderedVietaDescentChain a b c u v w →
          OrderedVietaDescentChain x y z u v w

/-- P4 checked bridge target: strict top-coordinate descent lowers additive height. -/
def P4_height_decrease_bridge_target : Prop :=
  ∀ x y z : ℤ,
    VietaDescendantZ x y z < z →
      PositiveMarkovHeight x y (VietaDescendantZ x y z) <
        PositiveMarkovHeight x y z

/-- P4 leaf target: iterate ordered Vieta descent until a minimal positive solution. -/
def P4_descent_termination_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      OrderedVietaDescentChain x y z 1 1 1

/-- P4 leaf target: every minimal ordered positive solution is the seed `(1,1,1)`. -/
def P4_minimal_solution_seed_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      (∀ a b c : ℤ,
        OrderedPositiveMarkovTriple a b c →
          PositiveMarkovHeight x y z ≤ PositiveMarkovHeight a b c) →
        x = 1 ∧ y = 1 ∧ z = 1

/-- P5 checked bridge target: reverse one third-coordinate Vieta step in the generator. -/
def P5_reverse_vieta_z_generation_target : Prop :=
  ∀ x y z : ℤ,
    GeneratedMarkovTriple x y (VietaDescendantZ x y z) →
      GeneratedMarkovTriple x y z

/-- P5 leaf target: a finite descent chain reverses to generated-triple membership. -/
def P5_reverse_descent_chain_target : Prop :=
  ∀ x y z : ℤ,
    OrderedPositiveMarkovTriple x y z →
      OrderedVietaDescentChain x y z 1 1 1 →
        GeneratedMarkovTriple x y z

/-- P3-P5 target package for the hard positive Vieta-descent converse. -/
def PositiveVietaDescentPackageTarget : Prop :=
  P3_x_eq_one_branch_target ∧
  P3_descendant_positive_target ∧
  P3_descendant_lt_top_target ∧
  P3_descendant_markov_target ∧
  P3_descendant_reorder_target ∧
  P4_height_decrease_bridge_target ∧
  P4_descent_termination_target ∧
  P4_minimal_solution_seed_target ∧
  P5_reverse_vieta_z_generation_target ∧
  P5_reverse_descent_chain_target

/--
Integer-wrapper target around the positive-generation theorem.

It states the intended lift from all integer solutions to either the zero
solution or an even-sign variant of a strictly positive generated triple.
This remains a target proposition, not a completed repo-local proof.
-/
def IntegerWrapperTarget : Prop :=
  ∀ x y z : ℤ,
    MarkovEqInt x y z →
      (x = 0 ∧ y = 0 ∧ z = 0) ∨
      ∃ a b c : ℤ,
        PositiveIntTriple a b c ∧
        GeneratedMarkovTriple a b c ∧
        EvenSignVariant x y z a b c

/--
Remaining sign-normalization target for the integer lift.

The checked zero-coordinate lemmas below reduce the nonzero branch to triples
with no zero coordinate.  This target records the still-open step: every
nonzero integer solution should be an even-sign variant of a strictly positive
integer solution.
-/
def NonzeroSignLiftTarget : Prop :=
  ∀ x y z : ℤ,
    MarkovEqInt x y z →
      ¬ (x = 0 ∧ y = 0 ∧ z = 0) →
        ∃ a b c : ℤ,
          PositiveIntTriple a b c ∧
          MarkovEqInt a b c ∧
          EvenSignVariant x y z a b c

/--
Classification target for integer Markov triples.

It states that every integer solution is either `(0,0,0)` or an even-sign
variant of a mutation/permutation-generated Markov triple.  This proposition is
the Stage1 formalization boundary; this repository does not currently contain a
proof of it.
-/
def StatementShape : Prop :=
  ∀ x y z : ℤ,
    MarkovEquation x y z →
      (x = 0 ∧ y = 0 ∧ z = 0) ∨
      ∃ a b c : ℤ,
        GeneratedMarkovTriple a b c ∧ EvenSignVariant x y z a b c

/-! ## Checked local algebraic wrappers -/

/-- The zero triple is an integer solution of the Markov equation. -/
theorem zero_solution : MarkovEquation 0 0 0 := by
  norm_num [MarkovEquation]

/-- The seed triple `(1,1,1)` is an integer solution of the Markov equation. -/
theorem seed_solution : MarkovEquation 1 1 1 := by
  norm_num [MarkovEquation]

/-- Swapping the first two coordinates preserves the Markov equation. -/
theorem swap_xy_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation y x z := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- Swapping the last two coordinates preserves the Markov equation. -/
theorem swap_yz_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation x z y := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- Swapping the first and last coordinates preserves the Markov equation. -/
theorem swap_xz_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation z y x :=
  swap_xy_preserves (swap_yz_preserves (swap_xy_preserves h))

/-- Changing signs of the last two coordinates preserves the Markov equation. -/
theorem sign_yz_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation x (-y) (-z) := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- Changing signs of the first and last coordinates preserves the Markov equation. -/
theorem sign_xz_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation (-x) y (-z) := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- Changing signs of the first two coordinates preserves the Markov equation. -/
theorem sign_xy_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation (-x) (-y) z := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- The standard mutation in the first coordinate preserves the Markov equation. -/
theorem mutate_x_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation (3 * y * z - x) y z := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- The standard mutation in the second coordinate preserves the Markov equation. -/
theorem mutate_y_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation x (3 * x * z - y) z := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/-- The standard mutation in the third coordinate preserves the Markov equation. -/
theorem mutate_z_preserves {x y z : ℤ} (h : MarkovEquation x y z) :
    MarkovEquation x y (3 * x * y - z) := by
  dsimp [MarkovEquation] at h ⊢
  nlinarith [h]

/--
Every generated triple satisfies the Markov equation.

This is a reduced local theorem, not the hard converse classification.
-/
theorem generated_satisfies_markov :
    ∀ {x y z : ℤ}, GeneratedMarkovTriple x y z → MarkovEquation x y z := by
  intro x y z h
  induction h with
  | seed =>
      exact seed_solution
  | swap_xy h ih =>
      exact swap_xy_preserves ih
  | swap_yz h ih =>
      exact swap_yz_preserves ih
  | mutate_x h ih =>
      exact mutate_x_preserves ih
  | mutate_y h ih =>
      exact mutate_y_preserves ih
  | mutate_z h ih =>
      exact mutate_z_preserves ih

/-- Checked P3 bridge: the third-coordinate Vieta descendant preserves the equation. -/
theorem p3_descendant_markov_checked : P3_descendant_markov_target := by
  intro x y z h
  exact mutate_z_preserves h

/-- Checked P4 bridge: once `z' < z` is known, additive height decreases. -/
theorem p4_height_decrease_bridge_checked : P4_height_decrease_bridge_target := by
  intro x y z hlt
  dsimp [PositiveMarkovHeight]
  nlinarith

/-- Checked P5 bridge: mutation is an involution for generator membership. -/
theorem p5_reverse_vieta_z_generation_checked :
    P5_reverse_vieta_z_generation_target := by
  intro x y z h
  convert GeneratedMarkovTriple.mutate_z h using 1
  simp [VietaDescendantZ]

/-! ## Checked integer-lift leaves -/

/-- If the first coordinate is zero, a Markov solution is the zero triple. -/
theorem zero_of_left_coordinate {x y z : ℤ}
    (h : MarkovEqInt x y z) (hx : x = 0) :
    x = 0 ∧ y = 0 ∧ z = 0 := by
  subst hx
  dsimp [MarkovEqInt, MarkovEquation] at h
  have hsum : y ^ 2 + z ^ 2 = 0 := by
    nlinarith [h]
  have hy2 : y ^ 2 = 0 := by
    nlinarith [sq_nonneg y, sq_nonneg z, hsum]
  have hz2 : z ^ 2 = 0 := by
    nlinarith [sq_nonneg y, sq_nonneg z, hsum]
  exact ⟨rfl, sq_eq_zero_iff.mp hy2, sq_eq_zero_iff.mp hz2⟩

/-- A zero coordinate in any position forces a Markov solution to be zero. -/
theorem zero_of_zero_coordinate {x y z : ℤ}
    (h : MarkovEqInt x y z) (hzero : x = 0 ∨ y = 0 ∨ z = 0) :
    x = 0 ∧ y = 0 ∧ z = 0 := by
  rcases hzero with hx | hy | hz
  · exact zero_of_left_coordinate h hx
  · have hswap : MarkovEqInt y x z := swap_xy_preserves h
    rcases zero_of_left_coordinate hswap hy with ⟨hy0, hx0, hz0⟩
    exact ⟨hx0, hy0, hz0⟩
  · have hswap : MarkovEqInt z y x := swap_xz_preserves h
    rcases zero_of_left_coordinate hswap hz with ⟨hz0, hy0, hx0⟩
    exact ⟨hx0, hy0, hz0⟩

/-- A nonzero Markov solution has no zero coordinate. -/
theorem nonzero_coordinates_of_nonzero_solution {x y z : ℤ}
    (h : MarkovEqInt x y z) (hnot_zero : ¬ (x = 0 ∧ y = 0 ∧ z = 0)) :
    x ≠ 0 ∧ y ≠ 0 ∧ z ≠ 0 := by
  constructor
  · intro hx
    exact hnot_zero (zero_of_left_coordinate h hx)
  constructor
  · intro hy
    exact hnot_zero (zero_of_zero_coordinate h (Or.inr (Or.inl hy)))
  · intro hz
    exact hnot_zero (zero_of_zero_coordinate h (Or.inr (Or.inr hz)))

/-- Swapping the first and last coordinates preserves generated triples. -/
theorem generated_swap_xz {x y z : ℤ}
    (h : GeneratedMarkovTriple x y z) : GeneratedMarkovTriple z y x :=
  GeneratedMarkovTriple.swap_xy
    (GeneratedMarkovTriple.swap_yz (GeneratedMarkovTriple.swap_xy h))

/-- Generated triples are closed under all coordinate permutations. -/
theorem generated_permutation_variant {x y z a b c : ℤ}
    (hgen : GeneratedMarkovTriple a b c)
    (hperm : CoordinatePermutationVariant x y z a b c) :
    GeneratedMarkovTriple x y z := by
  rcases hperm with h | h | h | h | h | h
  · rcases h with ⟨rfl, rfl, rfl⟩
    exact hgen
  · rcases h with ⟨rfl, rfl, rfl⟩
    exact GeneratedMarkovTriple.swap_yz hgen
  · rcases h with ⟨rfl, rfl, rfl⟩
    exact GeneratedMarkovTriple.swap_xy hgen
  · rcases h with ⟨rfl, rfl, rfl⟩
    exact GeneratedMarkovTriple.swap_yz (GeneratedMarkovTriple.swap_xy hgen)
  · rcases h with ⟨rfl, rfl, rfl⟩
    exact GeneratedMarkovTriple.swap_xy (GeneratedMarkovTriple.swap_yz hgen)
  · rcases h with ⟨rfl, rfl, rfl⟩
    exact generated_swap_xz hgen

/-! ## Proof-package split -/

/-- Package leaf for the degenerate integer solution `(0,0,0)`. -/
def ZeroSolutionPackage : Prop :=
  MarkovEqInt 0 0 0

/-- Checked package leaf for the zero-coordinate branch of the integer lift. -/
def ZeroCoordinatePackage : Prop :=
  ∀ x y z : ℤ,
    MarkovEqInt x y z →
      x = 0 ∨ y = 0 ∨ z = 0 →
        x = 0 ∧ y = 0 ∧ z = 0

/-- Checked package leaf for coordinate permutations of generated triples. -/
def GeneratedPermutationPackage : Prop :=
  ∀ {x y z a b c : ℤ},
    GeneratedMarkovTriple a b c →
      CoordinatePermutationVariant x y z a b c →
        GeneratedMarkovTriple x y z

/-- Package leaf for the positive seed solution `(1,1,1)`. -/
def SeedSolutionPackage : Prop :=
  MarkovEqInt 1 1 1

/-- Checked symmetry package: coordinate swaps and even sign changes. -/
def SymmetryPackage : Prop :=
  (∀ {x y z : ℤ}, MarkovEqInt x y z → MarkovEqInt y x z) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z → MarkovEqInt x z y) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z → MarkovEqInt z y x) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z → MarkovEqInt x (-y) (-z)) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z → MarkovEqInt (-x) y (-z)) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z → MarkovEqInt (-x) (-y) z)

/-- Checked mutation package for the three standard Markov moves. -/
def MutationPackage : Prop :=
  (∀ {x y z : ℤ}, MarkovEqInt x y z →
    MarkovEqInt (3 * y * z - x) y z) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z →
    MarkovEqInt x (3 * x * z - y) z) ∧
  (∀ {x y z : ℤ}, MarkovEqInt x y z →
    MarkovEqInt x y (3 * x * y - z))

/-- Checked soundness package for generated triples. -/
def GeneratedSoundnessPackage : Prop :=
  ∀ {x y z : ℤ}, GeneratedMarkovTriple x y z → MarkovEqInt x y z

/--
The repo-local package prefix that is fully proved in this file.

It deliberately excludes the hard converse Vieta-descent package and the
all-integer classification wrapper.
-/
def CheckedLocalAlgebraPackage : Prop :=
  ZeroSolutionPackage ∧
  ZeroCoordinatePackage ∧
  SeedSolutionPackage ∧
  SymmetryPackage ∧
  MutationPackage ∧
  GeneratedSoundnessPackage ∧
  GeneratedPermutationPackage

/--
Full proof-package target for the Markov classification.

The first conjunct is the checked local algebra prefix.  The remaining conjuncts
are target propositions for future formalization work: the positive
Vieta-descent converse, the nonzero sign lift, the all-integer wrapper, and the
public statement shape.
-/
def ClassificationProofPackageTarget : Prop :=
  CheckedLocalAlgebraPackage ∧
  PositiveVietaDescentPackageTarget ∧
  PositiveGenerationTarget ∧
  NonzeroSignLiftTarget ∧
  IntegerWrapperTarget ∧
  StatementShape

/-- The zero package is locally checked. -/
theorem zero_solution_package : ZeroSolutionPackage :=
  zero_solution

/-- The zero-coordinate integer-lift package is locally checked. -/
theorem zero_coordinate_package_checked : ZeroCoordinatePackage := by
  intro x y z h hzero
  exact zero_of_zero_coordinate h hzero

/-- The seed package is locally checked. -/
theorem seed_solution_package : SeedSolutionPackage :=
  seed_solution

/-- The symmetry package is locally checked. -/
theorem symmetry_package_checked : SymmetryPackage :=
  ⟨swap_xy_preserves,
    swap_yz_preserves,
    swap_xz_preserves,
    sign_yz_preserves,
    sign_xz_preserves,
    sign_xy_preserves⟩

/-- The mutation package is locally checked. -/
theorem mutation_package_checked : MutationPackage :=
  ⟨mutate_x_preserves, mutate_y_preserves, mutate_z_preserves⟩

/-- The generated-triple soundness package is locally checked. -/
theorem generated_soundness_package_checked : GeneratedSoundnessPackage :=
  generated_satisfies_markov

/-- The generated-triple permutation package is locally checked. -/
theorem generated_permutation_package_checked : GeneratedPermutationPackage := by
  intro x y z a b c hgen hperm
  exact generated_permutation_variant hgen hperm

/-- The locally proved algebraic prefix of the proof package. -/
theorem checked_local_algebra_package : CheckedLocalAlgebraPackage :=
  ⟨zero_solution_package,
    zero_coordinate_package_checked,
    seed_solution_package,
    symmetry_package_checked,
    mutation_package_checked,
    generated_soundness_package_checked,
    generated_permutation_package_checked⟩

/--
The remaining nonzero sign lift plus positive-generation theorem imply the
integer-wrapper target.

This is the checked packaging bridge for `THM-M-0389.integer-lift`; the
nonzero sign lift itself remains an explicit formalization target.
-/
theorem integerWrapper_of_positiveGeneration_and_nonzeroSignLift
    (hpositive : PositiveGenerationTarget)
    (hsign : NonzeroSignLiftTarget) : IntegerWrapperTarget := by
  intro x y z hmark
  by_cases hzero : x = 0 ∧ y = 0 ∧ z = 0
  · exact Or.inl hzero
  · rcases hsign x y z hmark hzero with
      ⟨a, b, c, hpos, hmark_pos, hsign_variant⟩
    exact Or.inr ⟨a, b, c, hpos, hpositive a b c hmark_pos hpos, hsign_variant⟩

/--
The integer-wrapper target implies the public `StatementShape`.

This records the final packaging step without proving the wrapper itself.
-/
theorem statementShape_of_integerWrapperTarget
    (h : IntegerWrapperTarget) : StatementShape := by
  intro x y z hx
  rcases h x y z hx with hzero | hgen
  · exact Or.inl hzero
  · rcases hgen with ⟨a, b, c, _hpos, hgenerated, hsign⟩
    exact Or.inr ⟨a, b, c, hgenerated, hsign⟩

/-! ## Audit constants retained for Stage1 repair bookkeeping -/

/-- Pinned mathlib revision used for the local Stage1 audit. -/
def pinnedMathlibRevision : String :=
  "8a178386ffc0f5fef0b77738bb5449d50efeea95"

/-- mathlib modules checked while locating repo-local anchors for this slot. -/
def mathlibAnchorModules : List String := [
  "Mathlib.Data.Int.Basic",
  "Mathlib.NumberTheory.Pell",
  "Mathlib.NumberTheory.PythagoreanTriples",
  "Mathlib.NumberTheory.Dioph",
  "Mathlib.NumberTheory.Height.Basic",
  "Mathlib.NumberTheory.Height.Northcott",
  "Mathlib.NumberTheory.NumberField.ClassNumber",
  "Mathlib.NumberTheory.ClassNumber.Finite"
]

/--
Result of the pinned local `NumberTheory` Markov/Markoff audit.

The command
`rg -n "Markov|Markoff|markov|markoff"
Formalizations/Lean/.lake/packages/mathlib/Mathlib/NumberTheory
Formalizations/Lean/.lake/packages/flt-regular/FltRegular`
returned no matches, so no terminal mathlib theorem for the integer Markov
equation classification was found in the pinned local NumberTheory sources.
-/
def mathlibNumberTheoryMarkovSearchResult : String :=
  "negative:NumberTheory-and-flt-regular-Markov-Markoff-search"

/-- Reusable pinned mathlib infrastructure identified by the audit. -/
def mathlibReusableInfrastructure : List (String × String) := [
  ("Mathlib.NumberTheory.Pell",
    "Pell.Solution₁, Pell.exists_of_not_isSquare, " ++
    "Pell.IsFundamental.eq_zpow_or_neg_zpow, " ++
    "Pell.pos_generator_iff_fundamental"),
  ("Mathlib.NumberTheory.PythagoreanTriples",
    "PythagoreanTriple, PythagoreanTriple.normalize, " ++
    "PythagoreanTriple.coprime_classification, " ++
    "PythagoreanTriple.classification"),
  ("Mathlib.NumberTheory.Dioph",
    "pell_dioph and Diophantine-set infrastructure"),
  ("Mathlib.NumberTheory.Height.*",
    "Height.Basic, Height.Northcott, Height.NumberField, " ++
    "Height.Projectivization"),
  ("Mathlib.NumberTheory.NumberField.ClassNumber",
    "number-field class-number infrastructure"),
  ("Mathlib.NumberTheory.ClassNumber.*",
    "finite and admissible absolute-value class-number infrastructure")
]

/-- Pinned theorem or definition names used by this local artifact. -/
def repoLocalAnchorNames : List String := [
  "S1_M_020.MarkovEquation",
  "S1_M_020.MarkovEqInt",
  "S1_M_020.GeneratedMarkovTriple",
  "S1_M_020.CoordinatePermutationVariant",
  "S1_M_020.PositiveGenerationTarget",
  "S1_M_020.PositiveVietaDescentPackageTarget",
  "S1_M_020.OrderedVietaDescentStep",
  "S1_M_020.OrderedVietaDescentChain",
  "S1_M_020.p3_descendant_markov_checked",
  "S1_M_020.p4_height_decrease_bridge_checked",
  "S1_M_020.p5_reverse_vieta_z_generation_checked",
  "S1_M_020.zero_of_zero_coordinate",
  "S1_M_020.nonzero_coordinates_of_nonzero_solution",
  "S1_M_020.generated_permutation_variant",
  "S1_M_020.NonzeroSignLiftTarget",
  "S1_M_020.IntegerWrapperTarget",
  "S1_M_020.StatementShape",
  "S1_M_020.CheckedLocalAlgebraPackage",
  "S1_M_020.ClassificationProofPackageTarget",
  "S1_M_020.integerWrapper_of_positiveGeneration_and_nonzeroSignLift",
  "S1_M_020.statementShape_of_integerWrapperTarget",
  "S1_M_020.generated_satisfies_markov"
]

/-- Canonical proof-package leaves for public blueprint backfill. -/
def proofPackageLeafNames : List String := [
  "statement.MarkovEqInt",
  "statement.GeneratedMarkovTriple",
  "statement.EvenSignVariant",
  "statement.CoordinatePermutationVariant",
  "checked.zero_solution",
  "checked.zero_coordinate_package",
  "checked.seed_solution",
  "checked.symmetry_package",
  "checked.mutation_package",
  "checked.generated_soundness",
  "checked.generated_permutation",
  "target.P3.x_eq_one_branch",
  "target.P3.descendant_positive",
  "target.P3.descendant_lt_top",
  "checked.P3.descendant_markov",
  "target.P3.descendant_reorder",
  "checked.P4.height_decrease_bridge",
  "target.P4.descent_termination",
  "target.P4.minimal_solution_seed",
  "checked.P5.reverse_vieta_z_generation",
  "target.P5.reverse_descent_chain",
  "target.nonzero_sign_lift",
  "checked.integer_wrapper_bridge",
  "target.integer_wrapper",
  "target.classification_statement"
]

/-- Current package statuses for the Markov equation Stage1 slot. -/
def proofPackageStatusTable : List (String × String) := [
  ("zero_solution", "local_proof_body"),
  ("zero_coordinate_package", "local_proof_body"),
  ("seed_solution", "local_proof_body"),
  ("symmetry_package", "local_proof_body"),
  ("mutation_package", "local_proof_body"),
  ("generated_soundness", "local_proof_body"),
  ("generated_permutation", "local_proof_body"),
  ("P3.x_eq_one_branch", "formalization_debt"),
  ("P3.descendant_positive", "formalization_debt"),
  ("P3.descendant_lt_top", "formalization_debt"),
  ("P3.descendant_markov", "local_proof_body"),
  ("P3.descendant_reorder", "formalization_debt"),
  ("P4.height_decrease_bridge", "local_proof_body"),
  ("P4.descent_termination", "formalization_debt"),
  ("P4.minimal_solution_seed", "formalization_debt"),
  ("P5.reverse_vieta_z_generation", "local_proof_body"),
  ("P5.reverse_descent_chain", "formalization_debt"),
  ("positive_generation_target", "formalization_debt"),
  ("nonzero_sign_lift", "formalization_debt"),
  ("integer_wrapper_bridge", "local_proof_body"),
  ("integer_wrapper", "formalization_debt"),
  ("classification_statement", "formalization_debt")
]

/--
Search terms used in the pinned local mathlib tree for the anchor audit.
-/
def mathlibAuditSearchTerms : List String := [
  "pinned mathlib revision 8a178386ffc0f5fef0b77738bb5449d50efeea95",
  "Markov|Markoff|markov|markoff in Mathlib/NumberTheory",
  "Markov equation",
  "Markov triples",
  "x^2 + y^2 + z^2 = 3xyz",
  "GeneratedMarkovTriple",
  "integer Markov triple",
  "Mathlib.NumberTheory.Pell",
  "Mathlib.NumberTheory.PythagoreanTriples",
  "Mathlib.NumberTheory.Dioph",
  "Mathlib.NumberTheory.Height",
  "Mathlib.NumberTheory.ClassNumber"
]

/--
Machine proof debt classification for this Stage1 slot.
-/
def machineProofDebtClassification : String :=
  "formalization_debt"

/--
Repo-local integration-debt gate for this repair pass.

No external Lean 4 Markov-equation classification proof was pinned/imported into
the repository validation closure during this repair, so this artifact is not a
completed wrapper and carries no completed-state `repo_local_integration_debt`.
-/
def repoLocalIntegrationDebtGate : String :=
  "not completed; no completed state retains repo_local_integration_debt"

/-! ## C007 validation gate -/

/-- File-level validation status for the `THM-M-0389.validation` child task. -/
inductive LocalValidationStatus where
  | passed
  | notRun
  | blocked
  deriving DecidableEq, Repr

/-- Required C007 repo-local validation command. -/
def c007ValidationCommand : String :=
  "cd Formalizations/Lean && lake env lean AwesomeTheorems/Stage1/S1_M_020.lean"

/-- Scope validated by the C007 command. -/
def c007ValidationScope : String :=
  "statement-shape artifact, checked local algebra package, namespace wrappers, and audit constants"

/--
C007 validation result recorded after running `c007ValidationCommand` in this
repository environment.
-/
def c007ValidationStatus : LocalValidationStatus :=
  LocalValidationStatus.passed

/-- Absolute local validation date for the C007 pass. -/
def c007ValidationDate : String :=
  "2026-05-01"

/--
C007 remains a file-level validation gate, not a completed proof of the Markov
classification theorem.
-/
def c007TheoremCompletionClaim : Bool :=
  false

/-- Checked C007 validation-status anchor. -/
theorem c007ValidationStatus_eq_passed :
    c007ValidationStatus = LocalValidationStatus.passed := rfl

/-- Checked C007 non-completion anchor. -/
theorem c007TheoremCompletionClaim_eq_false :
    c007TheoremCompletionClaim = false := rfl

#check MarkovEquation
#check MarkovEqInt
#check GeneratedMarkovTriple
#check EvenSignVariant
#check CoordinatePermutationVariant
#check PositiveIntTriple
#check PositiveGenerationTarget
#check OrderedPositiveMarkovTriple
#check VietaDescendantZ
#check PositiveMarkovHeight
#check P3_x_eq_one_branch_target
#check P3_descendant_positive_target
#check P3_descendant_lt_top_target
#check P3_descendant_markov_target
#check P3_descendant_reorder_target
#check OrderedVietaDescentStep
#check OrderedVietaDescentChain
#check P4_height_decrease_bridge_target
#check P4_descent_termination_target
#check P4_minimal_solution_seed_target
#check P5_reverse_vieta_z_generation_target
#check P5_reverse_descent_chain_target
#check PositiveVietaDescentPackageTarget
#check p3_descendant_markov_checked
#check p4_height_decrease_bridge_checked
#check p5_reverse_vieta_z_generation_checked
#check zero_of_left_coordinate
#check zero_of_zero_coordinate
#check nonzero_coordinates_of_nonzero_solution
#check generated_swap_xz
#check generated_permutation_variant
#check NonzeroSignLiftTarget
#check IntegerWrapperTarget
#check StatementShape
#check ZeroSolutionPackage
#check ZeroCoordinatePackage
#check SeedSolutionPackage
#check SymmetryPackage
#check MutationPackage
#check GeneratedSoundnessPackage
#check GeneratedPermutationPackage
#check CheckedLocalAlgebraPackage
#check ClassificationProofPackageTarget
#check zero_coordinate_package_checked
#check generated_permutation_package_checked
#check checked_local_algebra_package
#check integerWrapper_of_positiveGeneration_and_nonzeroSignLift
#check statementShape_of_integerWrapperTarget
#check pinnedMathlibRevision
#check mathlibAnchorModules
#check mathlibNumberTheoryMarkovSearchResult
#check mathlibReusableInfrastructure
#check proofPackageLeafNames
#check proofPackageStatusTable
#check generated_satisfies_markov
#check LocalValidationStatus
#check c007ValidationCommand
#check c007ValidationScope
#check c007ValidationStatus
#check c007ValidationDate
#check c007TheoremCompletionClaim
#check c007ValidationStatus_eq_passed
#check c007TheoremCompletionClaim_eq_false

end S1_M_020
end Stage1

/-!
## Repo-local namespace surface

This namespace is the local THM-M-0389 surface requested by the Stage1 repair
queue.  It intentionally reuses the checked Stage1 artifact above and does not
claim the hard converse classification theorem.
-/

namespace NumberTheory
namespace THM_M_0389

abbrev MarkovEquation (x y z : ℤ) : Prop :=
  Stage1.S1_M_020.MarkovEquation x y z

abbrev MarkovEqInt (x y z : ℤ) : Prop :=
  Stage1.S1_M_020.MarkovEqInt x y z

abbrev GeneratedMarkovTriple (x y z : ℤ) : Prop :=
  Stage1.S1_M_020.GeneratedMarkovTriple x y z

abbrev EvenSignVariant (x y z a b c : ℤ) : Prop :=
  Stage1.S1_M_020.EvenSignVariant x y z a b c

abbrev CoordinatePermutationVariant (x y z a b c : ℤ) : Prop :=
  Stage1.S1_M_020.CoordinatePermutationVariant x y z a b c

abbrev PositiveIntTriple (x y z : ℤ) : Prop :=
  Stage1.S1_M_020.PositiveIntTriple x y z

abbrev PositiveGenerationTarget : Prop :=
  Stage1.S1_M_020.PositiveGenerationTarget

abbrev OrderedPositiveMarkovTriple (x y z : ℤ) : Prop :=
  Stage1.S1_M_020.OrderedPositiveMarkovTriple x y z

abbrev VietaDescendantZ (x y z : ℤ) : ℤ :=
  Stage1.S1_M_020.VietaDescendantZ x y z

abbrev PositiveMarkovHeight (x y z : ℤ) : ℤ :=
  Stage1.S1_M_020.PositiveMarkovHeight x y z

abbrev PositiveVietaDescentPackageTarget : Prop :=
  Stage1.S1_M_020.PositiveVietaDescentPackageTarget

abbrev OrderedVietaDescentStep (x y z a b c : ℤ) : Prop :=
  Stage1.S1_M_020.OrderedVietaDescentStep x y z a b c

abbrev OrderedVietaDescentChain (x y z a b c : ℤ) : Prop :=
  Stage1.S1_M_020.OrderedVietaDescentChain x y z a b c

abbrev NonzeroSignLiftTarget : Prop :=
  Stage1.S1_M_020.NonzeroSignLiftTarget

abbrev IntegerWrapperTarget : Prop :=
  Stage1.S1_M_020.IntegerWrapperTarget

abbrev StatementShape : Prop :=
  Stage1.S1_M_020.StatementShape

abbrev CheckedLocalAlgebraPackage : Prop :=
  Stage1.S1_M_020.CheckedLocalAlgebraPackage

abbrev ClassificationProofPackageTarget : Prop :=
  Stage1.S1_M_020.ClassificationProofPackageTarget

theorem zero_solution : MarkovEqInt 0 0 0 :=
  Stage1.S1_M_020.zero_solution

theorem seed_solution : MarkovEqInt 1 1 1 :=
  Stage1.S1_M_020.seed_solution

theorem swap_xy_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt y x z :=
  Stage1.S1_M_020.swap_xy_preserves h

theorem swap_yz_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt x z y :=
  Stage1.S1_M_020.swap_yz_preserves h

theorem swap_xz_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt z y x :=
  Stage1.S1_M_020.swap_xz_preserves h

theorem sign_yz_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt x (-y) (-z) :=
  Stage1.S1_M_020.sign_yz_preserves h

theorem sign_xz_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt (-x) y (-z) :=
  Stage1.S1_M_020.sign_xz_preserves h

theorem sign_xy_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt (-x) (-y) z :=
  Stage1.S1_M_020.sign_xy_preserves h

theorem mutate_x_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt (3 * y * z - x) y z :=
  Stage1.S1_M_020.mutate_x_preserves h

theorem mutate_y_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt x (3 * x * z - y) z :=
  Stage1.S1_M_020.mutate_y_preserves h

theorem mutate_z_preserves {x y z : ℤ} (h : MarkovEqInt x y z) :
    MarkovEqInt x y (3 * x * y - z) :=
  Stage1.S1_M_020.mutate_z_preserves h

theorem generated_satisfies_markov :
    ∀ {x y z : ℤ}, GeneratedMarkovTriple x y z → MarkovEqInt x y z :=
  Stage1.S1_M_020.generated_satisfies_markov

theorem zero_of_zero_coordinate {x y z : ℤ}
    (h : MarkovEqInt x y z) (hzero : x = 0 ∨ y = 0 ∨ z = 0) :
    x = 0 ∧ y = 0 ∧ z = 0 :=
  Stage1.S1_M_020.zero_of_zero_coordinate h hzero

theorem nonzero_coordinates_of_nonzero_solution {x y z : ℤ}
    (h : MarkovEqInt x y z) (hnot_zero : ¬ (x = 0 ∧ y = 0 ∧ z = 0)) :
    x ≠ 0 ∧ y ≠ 0 ∧ z ≠ 0 :=
  Stage1.S1_M_020.nonzero_coordinates_of_nonzero_solution h hnot_zero

theorem generated_permutation_variant {x y z a b c : ℤ}
    (hgen : GeneratedMarkovTriple a b c)
    (hperm : CoordinatePermutationVariant x y z a b c) :
    GeneratedMarkovTriple x y z :=
  Stage1.S1_M_020.generated_permutation_variant hgen hperm

theorem p3_descendant_markov_checked :
    Stage1.S1_M_020.P3_descendant_markov_target :=
  Stage1.S1_M_020.p3_descendant_markov_checked

theorem p4_height_decrease_bridge_checked :
    Stage1.S1_M_020.P4_height_decrease_bridge_target :=
  Stage1.S1_M_020.p4_height_decrease_bridge_checked

theorem p5_reverse_vieta_z_generation_checked :
    Stage1.S1_M_020.P5_reverse_vieta_z_generation_target :=
  Stage1.S1_M_020.p5_reverse_vieta_z_generation_checked

theorem checked_local_algebra_package : CheckedLocalAlgebraPackage :=
  Stage1.S1_M_020.checked_local_algebra_package

theorem integerWrapper_of_positiveGeneration_and_nonzeroSignLift
    (hpositive : PositiveGenerationTarget)
    (hsign : NonzeroSignLiftTarget) : IntegerWrapperTarget :=
  Stage1.S1_M_020.integerWrapper_of_positiveGeneration_and_nonzeroSignLift hpositive hsign

theorem statementShape_of_integerWrapperTarget
    (h : IntegerWrapperTarget) : StatementShape :=
  Stage1.S1_M_020.statementShape_of_integerWrapperTarget h

def machineProofDebtClassification : String :=
  Stage1.S1_M_020.machineProofDebtClassification

def repoLocalIntegrationDebtGate : String :=
  Stage1.S1_M_020.repoLocalIntegrationDebtGate

abbrev LocalValidationStatus :=
  Stage1.S1_M_020.LocalValidationStatus

def c007ValidationCommand : String :=
  Stage1.S1_M_020.c007ValidationCommand

def c007ValidationScope : String :=
  Stage1.S1_M_020.c007ValidationScope

def c007ValidationStatus : LocalValidationStatus :=
  Stage1.S1_M_020.c007ValidationStatus

def c007ValidationDate : String :=
  Stage1.S1_M_020.c007ValidationDate

def c007TheoremCompletionClaim : Bool :=
  Stage1.S1_M_020.c007TheoremCompletionClaim

theorem c007ValidationStatus_eq_passed :
    c007ValidationStatus = Stage1.S1_M_020.LocalValidationStatus.passed :=
  Stage1.S1_M_020.c007ValidationStatus_eq_passed

theorem c007TheoremCompletionClaim_eq_false :
    c007TheoremCompletionClaim = false :=
  Stage1.S1_M_020.c007TheoremCompletionClaim_eq_false

#check MarkovEqInt
#check GeneratedMarkovTriple
#check CoordinatePermutationVariant
#check PositiveGenerationTarget
#check OrderedPositiveMarkovTriple
#check VietaDescendantZ
#check PositiveMarkovHeight
#check PositiveVietaDescentPackageTarget
#check OrderedVietaDescentStep
#check OrderedVietaDescentChain
#check p3_descendant_markov_checked
#check p4_height_decrease_bridge_checked
#check p5_reverse_vieta_z_generation_checked
#check zero_of_zero_coordinate
#check nonzero_coordinates_of_nonzero_solution
#check generated_permutation_variant
#check NonzeroSignLiftTarget
#check IntegerWrapperTarget
#check StatementShape
#check checked_local_algebra_package
#check integerWrapper_of_positiveGeneration_and_nonzeroSignLift
#check statementShape_of_integerWrapperTarget
#check LocalValidationStatus
#check c007ValidationCommand
#check c007ValidationScope
#check c007ValidationStatus
#check c007ValidationDate
#check c007TheoremCompletionClaim
#check c007ValidationStatus_eq_passed
#check c007TheoremCompletionClaim_eq_false

end THM_M_0389
end NumberTheory
end AwesomeTheorems
