import Mathlib.Analysis.Calculus.VectorField
import Mathlib.Analysis.Distribution.Distribution
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# THM-M-1259: Hormander's sum-of-squares theorem

This file freezes and elaborates the statement boundary.  It does not assert the theorem and
contains no proof placeholder.  `hormanderTarget` is the proposition to be proved in later phases.
-/

noncomputable section

open MeasureTheory
open scoped Distributions

namespace Stage1Instances.THM_M_1259

variable {n r : Nat}

abbrev Euclidean (n : Nat) := Fin n -> Real

abbrev RealVectorField (n : Nat) := Euclidean n -> Euclidean n

abbrev TestFunction (Omega : TopologicalSpace.Opens (Euclidean n)) :=
  𝓓(Omega, Real)

abbrev ScalarDistribution (Omega : TopologicalSpace.Opens (Euclidean n)) :=
  Distribution Omega Real ⊤

/-- Coordinate presentation of a real vector field. -/
abbrev Coefficients (n : Nat) := Fin n -> Euclidean n -> Real

def asVectorField (a : Coefficients n) : RealVectorField n :=
  fun x i => a i x

/-- Classical action `X f`, written in coordinates on `Real^n`. -/
def vectorFieldApply (a : Coefficients n) (f : Euclidean n -> Real) (x : Euclidean n) : Real :=
  fderiv Real f x (asVectorField a x)

/-- Coordinate divergence of a vector field. -/
def divergence (a : Coefficients n) (x : Euclidean n) : Real :=
  ∑ i : Fin n, fderiv Real (a i) x (Pi.single i 1)

/-- Formal transpose `X* phi = -X phi - (div X) phi`, bundled as a test-function map. -/
structure FormalAdjoint
    (Omega : TopologicalSpace.Opens (Euclidean n)) (a : Coefficients n) where
  toTestFunction : TestFunction Omega -> TestFunction Omega
  apply_eq : forall (phi : TestFunction Omega) (x : Euclidean n),
    toTestFunction phi x =
      -(vectorFieldApply a (phi : Euclidean n -> Real) x + divergence a x * phi x)

/-- The formal transpose of `sum_j X_j^2 + X_0 + c`, on test functions. -/
structure SumOfSquaresFormalAdjoint
    (Omega : TopologicalSpace.Opens (Euclidean n))
    (X0 : Coefficients n) (X : Fin r -> Coefficients n) (c : Euclidean n -> Real) where
  fieldAdjoint : forall j, FormalAdjoint Omega (X j)
  driftAdjoint : FormalAdjoint Omega X0
  toTestFunction : TestFunction Omega -> TestFunction Omega
  apply_eq : forall (phi : TestFunction Omega) (x : Euclidean n),
    toTestFunction phi x =
      (∑ j : Fin r,
        FormalAdjoint.toTestFunction (fieldAdjoint j)
          (FormalAdjoint.toTestFunction (fieldAdjoint j) phi) x) +
      driftAdjoint.toTestFunction phi x + c x * phi x

/-- `PT` is the distributional image of `T` under the sum-of-squares operator. -/
def IsDistributionalImage
    {Omega : TopologicalSpace.Opens (Euclidean n)}
    {X0 : Coefficients n} {X : Fin r -> Coefficients n} {c : Euclidean n -> Real}
    (A : SumOfSquaresFormalAdjoint Omega X0 X c)
    (T PT : ScalarDistribution Omega) : Prop :=
  forall phi : TestFunction Omega, PT phi = T (A.toTestFunction phi)

/-- A distribution is regular with a smooth density on its open domain. -/
def IsSmoothDistribution
    {Omega : TopologicalSpace.Opens (Euclidean n)}
    (mu : Measure (Euclidean n)) (T : ScalarDistribution Omega) : Prop :=
  exists f : Euclidean n -> Real,
    ContDiffOn Real ⊤ f (Omega : Set (Euclidean n)) /\
      forall phi : TestFunction Omega, T phi = ∫ x, phi x * f x ∂mu

/-- Hypoellipticity of the represented operator on one arbitrary open domain. -/
def IsHypoelliptic
    {Omega : TopologicalSpace.Opens (Euclidean n)}
    {X0 : Coefficients n} {X : Fin r -> Coefficients n} {c : Euclidean n -> Real}
    (mu : Measure (Euclidean n)) (A : SumOfSquaresFormalAdjoint Omega X0 X c) : Prop :=
  forall T PT : ScalarDistribution Omega,
    IsDistributionalImage A T PT -> IsSmoothDistribution mu PT -> IsSmoothDistribution mu T

/-- The Lie-bracket family generated by the drift and square fields. -/
inductive GeneratedBracket (X0 : Coefficients n) (X : Fin r -> Coefficients n) :
    RealVectorField n -> Prop where
  | drift : GeneratedBracket X0 X (asVectorField X0)
  | square (j : Fin r) : GeneratedBracket X0 X (asVectorField (X j))
  | bracket {V W : RealVectorField n} :
      GeneratedBracket X0 X V -> GeneratedBracket X0 X W ->
        GeneratedBracket X0 X (VectorField.lieBracket Real V W)

/-- Hormander's full-rank bracket condition at every point of the domain. -/
def BracketGenerating
    (Omega : TopologicalSpace.Opens (Euclidean n))
    (X0 : Coefficients n) (X : Fin r -> Coefficients n) : Prop :=
  forall x : Euclidean n, x ∈ (Omega : Set (Euclidean n)) ->
    Submodule.span Real
      ((fun V : RealVectorField n => V x) '' {V | GeneratedBracket X0 X V}) = ⊤

/-- Smoothness of every coordinate coefficient on the domain. -/
def SmoothCoefficients
    (Omega : TopologicalSpace.Opens (Euclidean n)) (a : Coefficients n) : Prop :=
  forall i, ContDiffOn Real ⊤ (a i) (Omega : Set (Euclidean n))

/--
Exact Lean target for the 1967 sum-of-squares theorem: if the Lie algebra generated by
`X_0, X_1, ..., X_r` has full rank everywhere, then
`sum_j X_j^2 + X_0 + c` is hypoelliptic.
-/
def hormanderTarget : Prop :=
  forall (n r : Nat) (Omega : TopologicalSpace.Opens (Euclidean n))
      (X0 : Coefficients n) (X : Fin r -> Coefficients n) (c : Euclidean n -> Real)
      (mu : Measure (Euclidean n)) (A : SumOfSquaresFormalAdjoint Omega X0 X c),
    SmoothCoefficients Omega X0 ->
    (forall j, SmoothCoefficients Omega (X j)) ->
    ContDiffOn Real ⊤ c (Omega : Set (Euclidean n)) ->
    BracketGenerating Omega X0 X ->
    IsHypoelliptic mu A

#check hormanderTarget
#check @hormanderTarget

/-- The exact distribution-level analytic core obtained by expanding `IsHypoelliptic`. -/
def ExpandedHypoellipticCore : Prop :=
  forall (n r : Nat) (Omega : TopologicalSpace.Opens (Euclidean n))
      (X0 : Coefficients n) (X : Fin r -> Coefficients n) (c : Euclidean n -> Real)
      (mu : Measure (Euclidean n)) (A : SumOfSquaresFormalAdjoint Omega X0 X c),
    SmoothCoefficients Omega X0 ->
    (forall j, SmoothCoefficients Omega (X j)) ->
    ContDiffOn Real ⊤ c (Omega : Set (Euclidean n)) ->
    BracketGenerating Omega X0 X ->
    forall T PT : ScalarDistribution Omega,
      IsDistributionalImage A T PT ->
      IsSmoothDistribution mu PT ->
      IsSmoothDistribution mu T

/-- Checked composition certificate from the expanded analytic core to the canonical root. -/
theorem expandedCore_composes_hormanderTarget
    (core : ExpandedHypoellipticCore) : hormanderTarget := by
  intro n r Omega X0 X c mu A hX0 hX hc hbracket T PT himage hsmooth
  exact core n r Omega X0 X c mu A hX0 hX hc hbracket T PT himage hsmooth

#check ExpandedHypoellipticCore
#check expandedCore_composes_hormanderTarget

end Stage1Instances.THM_M_1259
