import Mathlib.AlgebraicTopology.SimplicialComplex.Basic
import Mathlib.Data.Finsupp.Basic
import Mathlib.Data.Finset.Sort

/-!
The canonical statement uses Hatcher's ordered, unreduced integral simplicial chains.
An `n`-simplex is a face with `n + 1` vertices, and its orientation is the increasing
order supplied by the vertex order.  This file freezes the target; it does not prove it.
-/

namespace Stage1Instances.THM_M_0541

open Finset

universe u

variable {V : Type u} [LinearOrder V]

/-- The ordered `n`-simplices of an abstract simplicial complex. -/
def Simplex (K : AbstractSimplicialComplex V) (n : Nat) :=
  {s : Finset V // s ∈ K ∧ s.card = n + 1}

/-- Delete the `i`th vertex from an ordered simplex. -/
def face {K : AbstractSimplicialComplex V} {n : Nat}
    (σ : Simplex K (n + 1)) (i : Fin (n + 2)) : Simplex K n := by
  let v := σ.1.orderEmbOfFin σ.2.2 i
  refine ⟨σ.1.erase v, ?_, ?_⟩
  · exact (K.isRelLowerSet_faces σ.2.1).2 (erase_subset _ _) (card_pos.mp (by
      dsimp [v]
      rw [card_erase_of_mem (σ.1.orderEmbOfFin_mem σ.2.2 i), σ.2.2]
      omega))
  · rw [card_erase_of_mem (σ.1.orderEmbOfFin_mem σ.2.2 i), σ.2.2]
    omega

/-- Integral simplicial chains, freely generated by ordered simplices. -/
abbrev Chains (K : AbstractSimplicialComplex V) (n : Nat) := Simplex K n →₀ ℤ

/-- The alternating-boundary formula on every basis simplex. -/
def HasAlternatingBoundary (K : AbstractSimplicialComplex V)
    (d : (n : Nat) → Chains K (n + 1) →+ Chains K n) : Prop :=
  ∀ (n : Nat) (σ : Simplex K (n + 1)),
    d n (Finsupp.single σ 1) =
      ∑ i : Fin (n + 2), Finsupp.single (face σ i) ((-1 : ℤ) ^ (i : Nat))

/-- Exact canonical target: the alternating boundary exists and squares to zero. -/
def CanonicalTarget (K : AbstractSimplicialComplex V) : Prop :=
  ∃ d : (n : Nat) → Chains K (n + 1) →+ Chains K n,
    HasAlternatingBoundary K d ∧
      ∀ (n : Nat) (c : Chains K (n + 2)), d n (d (n + 1) c) = 0

def StatementShape : Prop :=
  ∀ (V : Type u) [LinearOrder V] (K : AbstractSimplicialComplex V), CanonicalTarget K

-- Structural mutations compared by `check_statement.py`.
def mutationRemovedVertexOrder : Prop :=
  ∀ (V : Type u) (_K : AbstractSimplicialComplex V), Nonempty (LinearOrder V)

def mutationChangedCoefficientDomain : Prop :=
  ∀ (V : Type u) [LinearOrder V] (K : AbstractSimplicialComplex V),
    ∃ _d : (n : Nat) → Simplex K (n + 1) →₀ ℚ →+ Simplex K n →₀ ℚ, True

def mutationChangedBinderScope : Prop :=
  ∃ V : Type u, ∃ _ : LinearOrder V,
    ∀ K : AbstractSimplicialComplex V, CanonicalTarget K

def mutationBoundaryDegreeZero : Prop :=
  ∀ (V : Type u) [LinearOrder V] (K : AbstractSimplicialComplex V),
    ∃ d : (n : Nat) → Chains K (n + 1) →+ Chains K n,
      HasAlternatingBoundary K d ∧
        ∀ c : Chains K 1, d 0 c = 0

end Stage1Instances.THM_M_0541

set_option pp.explicit true in
#print Stage1Instances.THM_M_0541.StatementShape
