import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.InnerProductSpace.l2Space

/-!
# THM-M-1272: classical Fountain theorem statement

This module freezes a Hilbert-space specialization of the classical Fountain
theorem. It defines and tests the proposition only; it does not prove it.
-/

noncomputable section

open Filter Set
open scoped Topology

namespace Stage1Instances.THM_M_1272

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- The finite-dimensional core generated by the first `k` directions. -/
def finiteCore (e : ℕ → E) (k : ℕ) : Submodule ℝ E :=
  Submodule.span ℝ (e '' Set.Iio k)

/-- The closed orthogonal tail complementary to the first `k` directions. -/
def orthogonalTail (e : ℕ → E) (k : ℕ) : Submodule ℝ E :=
  (finiteCore e k)ᗮ

/-- A real functional has a critical point where its Frechet derivative is zero. -/
def IsCriticalPoint (Phi : E → ℝ) (x : E) : Prop :=
  fderiv ℝ Phi x = 0

/-- The (global) Palais-Smale condition used by the selected classical variant. -/
def PalaisSmale (Phi : E → ℝ) : Prop :=
  ∀ u : ℕ → E,
    Bornology.IsBounded (Set.range (Phi ∘ u)) →
      Tendsto (fun n ↦ ‖fderiv ℝ Phi (u n)‖) atTop (nhds 0) →
        ∃ x : E, ∃ σ : ℕ → ℕ,
          StrictMono σ ∧ Tendsto (u ∘ σ) atTop (nhds x)

/-- Fountain geometry for an orthonormal total sequence. The lower barriers on
tail spheres tend to infinity and the functional is nonpositive on the
corresponding larger finite-core spheres. -/
def HasFountainGeometry (Phi : E → ℝ) (e : ℕ → E) : Prop :=
  ∃ r rho b : ℕ → ℝ,
    (∀ k, 0 < r k ∧ r k < rho k) ∧
      (∀ k x, x ∈ orthogonalTail e k → ‖x‖ = r k → b k ≤ Phi x) ∧
        Tendsto b atTop atTop ∧
          (∀ k x, x ∈ finiteCore e k → ‖x‖ = rho k → Phi x ≤ 0)

/-- The exact rev-5.6 target: the classical Fountain theorem in a separable
real Hilbert-space presentation with a specified orthonormal total sequence. -/
def FountainTheoremTarget : Prop :=
  ∀ (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
      (e : ℕ → E) (Phi : E → ℝ),
    Orthonormal ℝ e →
      (Submodule.span ℝ (Set.range e)).topologicalClosure = ⊤ →
        ContDiff ℝ 1 Phi →
          (∀ x, Phi (-x) = Phi x) →
            PalaisSmale Phi →
              HasFountainGeometry Phi e →
                ∃ u : ℕ → E,
                  (∀ n, IsCriticalPoint Phi (u n)) ∧
                    Tendsto (Phi ∘ u) atTop atTop

-- Structural mutations are separately elaborated by `check_statement.py`.
def mutationRemovedEvenness : Prop :=
  ∀ (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
      (e : ℕ → E) (Phi : E → ℝ),
    Orthonormal ℝ e →
      (Submodule.span ℝ (Set.range e)).topologicalClosure = ⊤ →
        ContDiff ℝ 1 Phi → PalaisSmale Phi → HasFountainGeometry Phi e →
          ∃ u : ℕ → E, (∀ n, IsCriticalPoint Phi (u n)) ∧
            Tendsto (Phi ∘ u) atTop atTop

def mutationRemovedPalaisSmale : Prop :=
  ∀ (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
      (e : ℕ → E) (Phi : E → ℝ),
    Orthonormal ℝ e →
      (Submodule.span ℝ (Set.range e)).topologicalClosure = ⊤ →
        ContDiff ℝ 1 Phi → (∀ x, Phi (-x) = Phi x) →
          HasFountainGeometry Phi e →
            ∃ u : ℕ → E, (∀ n, IsCriticalPoint Phi (u n)) ∧
              Tendsto (Phi ∘ u) atTop atTop

def mutationFiniteDimensionalConclusion : Prop :=
  ∀ (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
      (e : ℕ → E) (Phi : E → ℝ),
    Orthonormal ℝ e →
      (Submodule.span ℝ (Set.range e)).topologicalClosure = ⊤ →
        ContDiff ℝ 1 Phi → (∀ x, Phi (-x) = Phi x) →
          PalaisSmale Phi → HasFountainGeometry Phi e →
            ∃ x : E, IsCriticalPoint Phi x

def mutationBoundedCriticalValues : Prop :=
  ∀ (E : Type u) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
      (e : ℕ → E) (Phi : E → ℝ),
    Orthonormal ℝ e →
      (Submodule.span ℝ (Set.range e)).topologicalClosure = ⊤ →
        ContDiff ℝ 1 Phi → (∀ x, Phi (-x) = Phi x) →
          PalaisSmale Phi → HasFountainGeometry Phi e →
            ∃ u : ℕ → E, (∀ n, IsCriticalPoint Phi (u n)) ∧
              Bornology.IsBounded (Set.range (Phi ∘ u))

/-- The selected conclusion implies that critical values are unbounded above. -/
theorem tendsto_critical_values_unbounded
    {Phi : E → ℝ} {u : ℕ → E}
    (hcritical : ∀ n, IsCriticalPoint Phi (u n))
    (hvalue : Tendsto (Phi ∘ u) atTop atTop) :
    ∀ A : ℝ, ∃ x : E, IsCriticalPoint Phi x ∧ A ≤ Phi x := by
  intro A
  obtain ⟨n, hn⟩ := (hvalue.eventually (eventually_ge_atTop A)).exists
  exact ⟨u n, hcritical n, hn⟩

end Stage1Instances.THM_M_1272

set_option pp.explicit true in
#print Stage1Instances.THM_M_1272.FountainTheoremTarget
