import Mathlib.AlgebraicGeometry.Morphisms.Proper
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# THM-M-0120: Mori cone theorem statement boundary

This module freezes the characteristic-zero relative klt-pair formulation chosen
at intake. Mathlib does not yet define numerical curve classes, klt pairs, or
contractions of extremal rays, so `ConeTheoremData` exposes those notions as
typed primitives. No field asserts the cone decomposition, local finiteness,
rational generation, or existence of a contraction.
-/

noncomputable section

open CategoryTheory

namespace Stage1Instances.THMM0120

universe u uK uN uC

/-- Typed vocabulary for a projective relative Q-factorial klt pair. The
propositional fields are hypotheses on the input pair, not theorem outputs. -/
structure ConeTheoremData where
  k : Type uK
  [baseField : Field k]
  [baseFieldAlgebraicallyClosed : IsAlgClosed k]
  [baseFieldCharacteristicZero : CharZero k]
  X : AlgebraicGeometry.Scheme.{u}
  S : AlgebraicGeometry.Scheme.{u}
  f : X ⟶ S
  definedOverBaseField : Prop
  projective : Prop
  normal : Prop
  qFactorial : Prop
  klt : Prop
  relativeDimension : Nat
  N1 : Type uN
  [n1NormedAddCommGroup : NormedAddCommGroup N1]
  [n1NormedSpace : NormedSpace Real N1]
  [n1FiniteDimensional : FiniteDimensional Real N1]
  moriCone : Set N1
  moriConeClosed : IsClosed moriCone
  canonicalPairing : N1 →ₗ[Real] Real
  RationalCurve : Type uC
  curveClass : RationalCurve → N1
  antiCanonicalDegree : RationalCurve → Real
  antiCanonicalDegree_spec : ∀ C, antiCanonicalDegree C = -canonicalPairing (curveClass C)
  isContracted : ∀ {Y : AlgebraicGeometry.Scheme.{u}}, (X ⟶ Y) → RationalCurve → Prop

attribute [instance] ConeTheoremData.n1NormedAddCommGroup
  ConeTheoremData.n1NormedSpace ConeTheoremData.n1FiniteDimensional
  ConeTheoremData.baseField ConeTheoremData.baseFieldAlgebraicallyClosed
  ConeTheoremData.baseFieldCharacteristicZero

namespace ConeTheoremData

/-- A ray is generated by nonnegative real multiples of one nonzero numerical
curve class. -/
def IsGeneratedRay (D : ConeTheoremData) (R : Set D.N1) : Prop :=
  ∃ C : D.RationalCurve, D.curveClass C ≠ 0 ∧
    R = {z | ∃ a : Real, 0 ≤ a ∧ z = a • D.curveClass C}

/-- An extremal ray of the effective cone, expressed by the defining
two-summand condition. -/
def IsExtremalRay (D : ConeTheoremData) (R : Set D.N1) : Prop :=
  R ⊆ D.moriCone ∧ D.IsGeneratedRay R ∧
    ∀ x ∈ D.moriCone, ∀ y ∈ D.moriCone, x + y ∈ R → x ∈ R ∧ y ∈ R

/-- The `(K_X + Delta)`-nonnegative part of the relative effective cone. -/
def NonnegativePart (D : ConeTheoremData) : Set D.N1 :=
  {z | z ∈ D.moriCone ∧ 0 ≤ D.canonicalPairing z}

/-- Membership in the Minkowski sum of the nonnegative part and the cone
generated by a family of rays. The list gives the required finite support. -/
def InRayDecomposition (D : ConeTheoremData) {ι : Type}
    (ray : ι → Set D.N1) (z : D.N1) : Prop :=
  ∃ z0 ∈ D.NonnegativePart, ∃ terms : List (ι × D.N1),
    (∀ term ∈ terms, term.2 ∈ ray term.1) ∧ z = z0 + (terms.map Prod.snd).sum

/-- A morphism contracts exactly the rational curves whose numerical classes
belong to `R`, and is universal among morphisms with that property. -/
def IsContractionOf (D : ConeTheoremData) (R : Set D.N1)
    (Y : AlgebraicGeometry.Scheme.{u}) (g : D.X ⟶ Y) : Prop :=
  (∀ C : D.RationalCurve, D.isContracted g C ↔ D.curveClass C ∈ R) ∧
    ∀ (Z : AlgebraicGeometry.Scheme.{u}) (h : D.X ⟶ Z),
      (∀ C : D.RationalCurve, D.curveClass C ∈ R → D.isContracted h C) →
        ∃! q : Y ⟶ Z, g ≫ q = h

/-- Full output package: countably many negative extremal rays, rational-curve
generators with the standard length bound, decomposition, local finiteness away
from the nonnegative wall, and the contraction of every listed ray. -/
def Conclusion (D : ConeTheoremData) : Prop :=
  ∃ (ι : Type) (_ : Countable ι) (ray : ι → Set D.N1),
    (∀ i, D.IsExtremalRay (ray i) ∧
      (∀ z ∈ ray i, z ≠ 0 → D.canonicalPairing z < 0) ∧
      ∃ C : D.RationalCurve,
        D.curveClass C ∈ ray i ∧ D.curveClass C ≠ 0 ∧
        0 < D.antiCanonicalDegree C ∧
        D.antiCanonicalDegree C ≤ 2 * D.relativeDimension) ∧
    (∀ z, z ∈ D.moriCone ↔ D.InRayDecomposition ray z) ∧
    (∀ ε : Real, 0 < ε →
      {i | ∃ z ∈ ray i, ‖z‖ = 1 ∧ D.canonicalPairing z ≤ -ε}.Finite) ∧
    ∀ i, ∃ (Y : AlgebraicGeometry.Scheme.{u}) (g : D.X ⟶ Y),
      D.IsContractionOf (ray i) Y g

end ConeTheoremData

/-- Exact rev-5.6 target: the relative cone-and-contraction theorem over an
algebraically closed characteristic-zero field, represented by its induced
geometric hypotheses on the pair. -/
def MoriConeTheoremTarget : Prop :=
  ∀ D : ConeTheoremData.{u, uK, uN, uC},
    AlgebraicGeometry.IsProper D.f →
      D.definedOverBaseField → D.projective → D.normal → D.qFactorial → D.klt → D.Conclusion

/-- Checked definitional expansion of the frozen target. -/
theorem moriConeTheoremTarget_iff_expanded :
    MoriConeTheoremTarget.{u, uK, uN, uC} ↔
      ∀ D : ConeTheoremData.{u, uK, uN, uC},
        AlgebraicGeometry.IsProper D.f →
          D.definedOverBaseField → D.projective → D.normal → D.qFactorial → D.klt →
            D.Conclusion :=
  Iff.rfl

-- Separately elaborated structural mutations; none is granted equivalence.
def MutationRemovedKlt : Prop :=
  ∀ D : ConeTheoremData.{u, uK, uN, uC},
    AlgebraicGeometry.IsProper D.f →
      D.definedOverBaseField → D.projective → D.normal → D.qFactorial → D.Conclusion

def MutationAbsoluteBase : Prop :=
  ∀ D : ConeTheoremData.{u, uK, uN, uC},
    D.definedOverBaseField → D.projective → D.normal → D.qFactorial → D.klt → D.Conclusion

def MutationNoContractions : Prop :=
  ∀ D : ConeTheoremData.{u, uK, uN, uC},
    AlgebraicGeometry.IsProper D.f → D.definedOverBaseField →
      D.projective → D.normal → D.qFactorial → D.klt →
      ∃ (ι : Type) (_ : Countable ι) (ray : ι → Set D.N1),
        ∀ i, D.IsExtremalRay (ray i)

end Stage1Instances.THMM0120

set_option pp.universes true in
set_option pp.explicit true in
#print Stage1Instances.THMM0120.MoriConeTheoremTarget
