#!/usr/bin/env python3
"""Build the frozen THM-M-1258 obligation registry and typed graph bundle."""

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ITEM = "S56-M-1258-OBLIGATION_TREE"
THEOREM = "THM-M-1258"


def sha256(path):
    return hashlib.sha256((HERE / path).read_bytes()).hexdigest()


def fingerprint(text):
    return "planned:v1:sha256:" + hashlib.sha256(text.encode()).hexdigest()


rows = [
    ("M1258-ROOT", "root", "The exact condition-valued declaration on Omega, X0, and X.", "@Stage1Instances.THM_M_1258.hormanderCondition", True, "required", "required", "critical"),
    ("M1258-S-DOMAIN", "definition", "Fix n, r, the open subset Omega of Real^n, the drift X0, and the r square fields X.", "n r : Nat; Omega : Opens (Fin n -> Real); X0 : Coefficients n; X : Fin r -> Coefficients n", True, "required", "required", "high"),
    ("M1258-S-GENERATED", "definition", "Generate the smallest family containing X0 and every X j and closed under binary Lie brackets.", "GeneratedBracket X0 X V", True, "required", "required", "critical"),
    ("M1258-N-POINTWISE", "normalization", "Expose the condition as a pointwise full-span obligation for every x in Omega.", "forall x, x in Omega -> span Real ((fun V => V x) '' {V | GeneratedBracket X0 X V}) = top", True, "required", "required", "critical"),
    ("M1258-L-SPAN", "core_lemma", "For fixed supplied fields, establish the full-span equality at an arbitrary point of Omega.", "x in Omega -> span Real ((fun V => V x) '' {V | GeneratedBracket X0 X V}) = top", True, "required", "required", "critical"),
    ("M1258-B-EMPTY", "branch", "The condition holds on the empty open domain because there is no point in it.", "hormanderCondition (bottom : Opens (Euclidean n)) X0 X", False, "not_applicable", "required", "low"),
    ("M1258-B-ZERODIM", "branch", "In dimension zero every submodule of Real^0 equals top, so the span condition is automatic.", "hormanderCondition (n := 0) Omega X0 X", False, "not_applicable", "required", "normal"),
    ("M1258-X-APIS", "certificate", "Bind the Lie-bracket and submodule-span APIs to the pinned mathlib provenance audit.", "VectorField.lieBracket; Submodule.span", True, "informational", "not_applicable", "high"),
    ("M1258-W-FOLLOWUP", "workflow_gate", "Require a concrete field family or an explicit span premise before any later proof receipt can claim an inhabitant.", "PROOF -> VALIDATION -> RELEASE after OBLIGATION_TREE", True, "informational", "not_applicable", "critical"),
]

obligations = []
nodes = []
for oid, kind, human, formal, relevant, machine, human_source, risk in rows:
    overlay = machine == "informational"
    obligations.append({
        "obligation_id": oid,
        "statement_fingerprint": fingerprint(formal),
        "kind": kind,
        "root_relevant": relevant,
        "machine_eligibility": machine,
        "human_source_eligibility": human_source,
        "readable_eligibility": "required",
        "risk_class": risk,
        "exclusion_reason": "assurance_overlay_no_distinct_proof_credit" if overlay else ("boundary_case_not_generic_root_premise" if not relevant else None),
        "terminal_proof_body_id": None,
    })
    output = {
        "M1258-ROOT": "The canonical condition predicate, without asserting it for arbitrary fields.",
        "M1258-S-DOMAIN": "The exact ordered binder context and its admitted degenerate cases.",
        "M1258-S-GENERATED": "All and only finite bracket expressions generated by the supplied fields.",
        "M1258-N-POINTWISE": "A universally quantified pointwise span goal equivalent by unfolding to the root.",
        "M1258-L-SPAN": "The span equality for an arbitrary x and membership proof hx.",
        "M1258-B-EMPTY": "A checked empty-domain boundary theorem.",
        "M1258-B-ZERODIM": "A checked zero-dimensional boundary theorem.",
        "M1258-X-APIS": "Pinned nonterminal API provenance with no root proof credit.",
        "M1258-W-FOLLOWUP": "A fail-closed ordering and input boundary for later phases.",
    }[oid]
    outgoing = "canonical theorem decision" if oid == "M1258-ROOT" else "M1258-ROOT"
    nodes.append({
        "node_id": "THM-M-1258-" + oid.removeprefix("M1258-"),
        "obligation_id": oid,
        "kind": kind,
        "human_statement": human,
        "formal_target": formal,
        "output": output,
        "human_debt": "H2",
        "machine_debt": "M4",
        "readability_debt": "R4",
        "evidence_ids": [],
        "source_crosswalk_id": "anchor-audit-root-boundary" if human_source == "required" else "not-applicable",
        "provenance_id": "M1258-A-MATHLIB-LIE-BRACKET+M1258-A-MATHLIB-SPAN" if oid == "M1258-X-APIS" else "none",
        "foundation_profile": "lean4-dependent-type-theory; classical-policy-audit-pending",
        "tcb_profile": "lean-4.29.0; mathlib-8a178386ffc0f5fef0b77738bb5449d50efeea95; transitive-trust-audit-pending",
        "computation_record": "none",
        "step_budget": 2,
        "semantic_step_ledger": [
            {"premises": "the exact context named in formal_target", "inference": human, "output": output, "outgoing_use": outgoing},
            {"premises": "node output and its declared typed edge", "inference": "validate the exact handoff without adding an undeclared field hypothesis", "output": "typed handoff of " + oid, "outgoing_use": outgoing},
        ],
        "public_readable_target": "Stage1_Instances/THM-M-1258/obligation-tree.md#" + oid.lower(),
        "validation_spec_id": "VAL-" + oid,
        "status_boundary": "Architecture only; no generic proof that arbitrary fields satisfy the condition is claimed.",
        "task_ids": [ITEM, "S56-M-1258-PROOF"],
        "owned_sources": ["Stage1_Instances/THM-M-1258"],
        "owner": "THM-M-1258 proof implementer",
        "reviewer": "independent Stage1 integration reviewer",
        "validity": "frozen-2026-07-12; review_due=before-proof-acceptance; invalidate_on=statement,registry,edge,source,toolchain change; revocation=none",
    })

projection = [{key: row[key] for key in row} for row in obligations]
denominator = hashlib.sha256(json.dumps(projection, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
ids = [row[0] for row in rows]
registry = {
    "schema_version": "stage1-obligation-registry/1.0",
    "item_id": ITEM,
    "theorem_id": THEOREM,
    "registry_version": 1,
    "frozen_at": "2026-07-12T00:00:00+08:00",
    "freeze_basis": "The exact condition-valued statement and immutable anchor audit, before proof-phase closure observation.",
    "frozen_against_statement_sha256": sha256("Statement.lean"),
    "frozen_against_anchor_audit_sha256": sha256("anchor-audit.json"),
    "root_obligation_id": "M1258-ROOT",
    "denominator_sha256": denominator,
    "frozen_denominators": {
        "inventory": ids,
        "required_machine": [row[0] for row in rows if row[5] == "required"],
        "required_human_source": [row[0] for row in rows if row[6] == "required"],
        "required_readable": ids,
        "informational_overlays": ["M1258-X-APIS", "M1258-W-FOLLOWUP"],
    },
    "delta_policy": "Any correction, split, merge, exclusion, or eligibility change requires a new version and an append-only old/new ID delta.",
    "obligations": obligations,
}

edge_counter = 0
graphs = {name: [] for name in ("proof", "refinement", "provenance", "evidence", "trust", "documentation", "workflow")}


def edge(graph, source, target, kind, reciprocal=None):
    global edge_counter
    edge_counter += 1
    record = {"edge_id": f"E{edge_counter:02d}", "from": source, "to": target, "type": kind}
    if reciprocal:
        record["reciprocal_edge_id"] = reciprocal
    graphs[graph].append(record)
    return record["edge_id"]


e1 = edge("proof", "M1258-ROOT", "M1258-N-POINTWISE", "proof_requires", "E02")
edge("proof", "M1258-N-POINTWISE", "M1258-ROOT", "composes", e1)
e3 = edge("proof", "M1258-N-POINTWISE", "M1258-L-SPAN", "proof_requires", "E04")
edge("proof", "M1258-L-SPAN", "M1258-N-POINTWISE", "composes", e3)
for target in ("M1258-S-DOMAIN", "M1258-S-GENERATED", "M1258-N-POINTWISE", "M1258-B-EMPTY", "M1258-B-ZERODIM"):
    edge("refinement", "M1258-ROOT", target, "logical_decomposition" if target == "M1258-N-POINTWISE" else "expository_decomposition")
edge("provenance", "M1258-X-APIS", "M1258-S-GENERATED", "provenance_of")
edge("provenance", "M1258-X-APIS", "M1258-L-SPAN", "provenance_of")
edge("evidence", "M1258-X-APIS", "M1258-ROOT", "evidence_for")
edge("trust", "M1258-ROOT", "M1258-X-APIS", "trusts")
for target in ids:
    if target != "M1258-W-FOLLOWUP":
        edge("documentation", target, "M1258-W-FOLLOWUP", "documents")
edge("workflow", "M1258-W-FOLLOWUP", "M1258-ROOT", "workflow_depends_on")

indexed = {}
for name, entries in graphs.items():
    indexed[name] = {
        "edges": entries,
        "out": {oid: [e["edge_id"] for e in entries if e["from"] == oid] for oid in ids},
        "in": {oid: [e["edge_id"] for e in entries if e["to"] == oid] for oid in ids},
    }

bundle = {
    "schema_version": "stage1-typed-graphs/1.0",
    "item_id": ITEM,
    "theorem_id": THEOREM,
    "registry_denominator_sha256": denominator,
    "nodes": nodes,
    "graphs": indexed,
    "closure_metrics_observed": False,
    "root_cut_set": ["M1258-L-SPAN"],
    "closure_boundary": {
        "root_closed": False,
        "theorem_complete": False,
        "reason": "The frozen target is a predicate. An inhabitant requires concrete fields plus a span proof; arbitrary fields do not satisfy it.",
    },
}

for name, value in (("obligation-registry.json", registry), ("typed-graphs.json", bundle)):
    (HERE / name).write_text(json.dumps(value, indent=2) + "\n")
print(f"wrote {len(obligations)} obligations and {edge_counter} typed edges; denominator={denominator}")
