#!/usr/bin/env python3
"""Build and independently replay the candidate-only mathlib v5.6 reserve.

This script never writes a release, registry, Current_Release pointer, or a
PutnamBench artifact.  It converts the fully replayed 2,566-row mathlib source
artifact into a compact 1,066-row reserve ledger and an authority-sealed
inventory.  With no flag it compares the generated bytes to the two checked
outputs; ``--write`` atomically materializes those outputs.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import unicodedata
from typing import Any, Iterable, Mapping, Sequence


SCHEMA = "awesome-theorems/mathlib-reserve-candidate/5.6"
INVENTORY_SCHEMA = "awesome-theorems/mathlib-reserve-inventory/5.6"
SOURCE_SCHEMA = "awesome-theorems/mathlib-theorem-source/1.0"
SOURCE_COMMIT = "8a178386ffc0f5fef0b77738bb5449d50efeea95"

FULL_ROWS = 2_566
PARENT_SOURCE_ROWS = 1_500
RESERVE_ROWS = 1_066
FULL_SOURCE_SHA256 = "7075e0bb151182ae4ba01cd34945657969be4bc60f7ee4ae6a62fc518f5386c3"
PARENT_SOURCE_SHA256 = "236b9f6ac192eaf87215663bfd7fadb80c439b452049cef1747ea804c458637a"
PARENT_CATALOG_SHA256 = "9d6dc79b1cbdee401f2f022ee027557a04331fa9605dc7f443fdc09a62b029b4"
PARENT_MANIFEST_SHA256 = "773253c2afad3a91c1b14cc9b5f60b51ec9b7e258d1619f0168dd23c9c4b0a43"
V5_4_CURATION_SHA256 = "0057a36999422726d6d490dbf59eca69824bc29a02f5117f9a02ebdd601dd386"
EXTRACTOR_SHA256 = "0e26af2b6740abf4626f3cf43d84fb8f7e1f1a6104096e71f1f9b1f2c33189af"

ALLOWED_SIGNAL_KINDS = {
    "mathlib_1000_theorems",
    "mathlib_module_main_result",
}
SHA_RE = re.compile(r"[0-9a-f]{64}")

# Independently observed after the first live extraction.  These are hard
# invariants, not merely fields copied from the generated inventory.
EXPECTED_COUNTS: dict[str, Any] = {
    "full_selected_source_rows": 2_566,
    "runtime_thmInfo_sorry_free_screened": 2_575,
    "metadata_quality_excluded_runtime_thmInfo": 9,
    "full_literal_declaration_kinds": {"lemma": 489, "theorem": 2_077},
    "full_source_identity_duplicate_losers": 5,
    "full_unique_formal_proposition_identities": 2_561,
    "preserved_parent_source_rows": 1_500,
    "reserve_candidate_rows": 1_066,
    "reserve_kernel_checked_sorry_free": 1_066,
    "reserve_literal_declaration_kinds": {"lemma": 224, "theorem": 842},
    "reserve_with_declaration_docstring": 371,
    "reserve_importance_signal_rows": {"mathlib_module_main_result": 1_066},
    "reserve_parent_identity_conflict_rows": 0,
    "reserve_source_identity_duplicate_rows": 1,
    "reserve_unique_any_literal_kind": 1_065,
    "reserve_mechanically_eligible_literal_theorems": 841,
    "reserve_by_disposition": {
        "literal_lemma_candidate_only_under_current_quota_policy": 224,
        "mechanically_eligible_literal_theorem_unique": 841,
        "source_exact_identity_duplicate_candidate_only": 1,
    },
    "legacy_5_4_residual_literal_theorems": 231,
    "legacy_5_4_residual_parent_5_5_conflicts": 0,
    "legacy_5_4_residual_currently_mechanically_eligible": 231,
    "combined_next_batch_mechanical_theorem_candidates": 1_072,
    "documented_unadmitted_unique_runtime_thmInfo": 1_561,
    "documented_unadmitted_unique_literal_theorems": 1_072,
    "documented_unadmitted_unique_literal_lemmas": 489,
    "current_release_mathlib_theorems": 1_000,
    "possible_mathlib_release_inventory_after_combined_batch": 2_072,
    "all_2_566_selected_rows_are_runtime_thmInfo": True,
}

EXPECTED_ROOT_COUNTS = {
    "Algebra": 76,
    "AlgebraicGeometry": 19,
    "AlgebraicTopology": 1,
    "Analysis": 163,
    "CategoryTheory": 10,
    "Combinatorics": 22,
    "Computability": 8,
    "Data": 35,
    "Dynamics": 5,
    "FieldTheory": 32,
    "Geometry": 32,
    "GroupTheory": 33,
    "LinearAlgebra": 62,
    "Logic": 2,
    "MeasureTheory": 82,
    "ModelTheory": 11,
    "NumberTheory": 37,
    "Order": 39,
    "Probability": 35,
    "RingTheory": 201,
    "SetTheory": 7,
    "Topology": 154,
}

EXPECTED_ELIGIBLE_ROOT_COUNTS = {
    "Algebra": 59,
    "AlgebraicGeometry": 3,
    "AlgebraicTopology": 1,
    "Analysis": 144,
    "CategoryTheory": 10,
    "Combinatorics": 11,
    "Computability": 8,
    "Data": 30,
    "Dynamics": 5,
    "FieldTheory": 29,
    "Geometry": 13,
    "GroupTheory": 31,
    "LinearAlgebra": 48,
    "Logic": 1,
    "MeasureTheory": 66,
    "ModelTheory": 11,
    "NumberTheory": 28,
    "Order": 39,
    "Probability": 21,
    "RingTheory": 151,
    "SetTheory": 7,
    "Topology": 125,
}


class InventoryError(RuntimeError):
    """A source, identity, count, or output invariant failed."""


def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / ".git").exists():
            return candidate
    raise InventoryError("cannot find repository root")


HERE = Path(__file__).resolve().parent
REPO = find_repo_root(HERE)
FULL_SOURCE = HERE / "mathlib-verified-theorems-8a178386-full.json"
PARENT_SOURCE = REPO / "Docs/catalog/v5/sources/mathlib-theorems-8a178386.json"
PARENT_CATALOG = REPO / "Docs/catalog/v5/releases/5.5/Claim_Catalog.json"
PARENT_MANIFEST = REPO / "Docs/catalog/v5/releases/5.5/Release_Manifest.json"
V5_4_CURATION = REPO / "Docs/catalog/v5/curation/Mathlib_Theorem_Curation_v5_4.json"
EXTRACTOR = REPO / "Docs/tools/extract_mathlib_theorems_v5.py"
LEDGER = HERE / "Mathlib_Reserve_Candidates_v5_6.jsonl"
INVENTORY = HERE / "Mathlib_Reserve_Inventory_v5_6.json"


def canonical(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as error:
        raise InventoryError(f"value is not canonical JSON: {error}") from error


def pretty(value: Any) -> bytes:
    try:
        return (
            json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False)
            + "\n"
        ).encode("utf-8")
    except (TypeError, ValueError) as error:
        raise InventoryError(f"value is not JSON serializable: {error}") from error


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def hash_without(value: Mapping[str, Any], *fields: str) -> str:
    omitted = set(fields)
    return sha(canonical({key: item for key, item in value.items() if key not in omitted}))


def set_digest(values: Iterable[str]) -> str:
    return sha(canonical(sorted(set(values))))


def reject_constant(value: str) -> None:
    raise InventoryError(f"non-finite JSON number is forbidden: {value}")


def unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    output: dict[str, Any] = {}
    for key, value in pairs:
        if key in output:
            raise InventoryError(f"duplicate JSON key: {key!r}")
        output[key] = value
    return output


def load_json(path: Path, expected_sha: str) -> tuple[dict[str, Any], bytes]:
    try:
        payload = path.read_bytes()
    except OSError as error:
        raise InventoryError(f"cannot read {path}: {error}") from error
    observed = sha(payload)
    if observed != expected_sha:
        raise InventoryError(f"{path} sha256={observed}, expected {expected_sha}")
    try:
        value = json.loads(
            payload.decode("utf-8"),
            object_pairs_hook=unique_object,
            parse_constant=reject_constant,
        )
    except (UnicodeError, json.JSONDecodeError) as error:
        raise InventoryError(f"invalid JSON in {path}: {error}") from error
    if not isinstance(value, dict):
        raise InventoryError(f"{path} must contain one object")
    return value, payload


def require(condition: bool, message: str) -> None:
    if not condition:
        raise InventoryError(message)


def normalize_type(value: str) -> str:
    return " ".join(value.split())


def normalized_type_sha(value: str) -> str:
    return sha(normalize_type(value).encode("utf-8"))


def normalize_name(value: str) -> str:
    return unicodedata.normalize("NFKC", value).casefold().strip()


def normalized_name_sha(value: str) -> str:
    return sha(normalize_name(value).encode("utf-8"))


def module_root(row: Mapping[str, Any]) -> str:
    source = row.get("source")
    require(isinstance(source, dict), "source row lacks source object")
    module = source.get("module")
    require(isinstance(module, str), "source row lacks source.module")
    pieces = module.split(".")
    require(
        len(pieces) >= 2 and pieces[0] == "Mathlib" and bool(pieces[1]),
        f"invalid mathlib module {module!r}",
    )
    return pieces[1]


def signal_kinds(row: Mapping[str, Any]) -> tuple[str, ...]:
    signals = row.get("importance_signals")
    require(isinstance(signals, list) and bool(signals), "source row has no importance signal")
    kinds: set[str] = set()
    for signal in signals:
        require(isinstance(signal, dict), "importance signal is not an object")
        kind = signal.get("kind")
        require(kind in ALLOWED_SIGNAL_KINDS, f"unsupported importance signal {kind!r}")
        kinds.add(str(kind))
    return tuple(sorted(kinds))


def validate_source_document(document: Mapping[str, Any], rows_expected: int, label: str) -> list[dict[str, Any]]:
    require(document.get("schema_version") == SOURCE_SCHEMA, f"{label} schema drifted")
    body = dict(document)
    declared_self_digest = body.pop("content_digest_before_self_field", None)
    require(
        declared_self_digest == sha(pretty(body)),
        f"{label} content_digest_before_self_field is stale",
    )
    snapshot = document.get("source_snapshot")
    require(isinstance(snapshot, dict), f"{label} source_snapshot missing")
    require(snapshot.get("commit") == SOURCE_COMMIT, f"{label} commit drifted")
    require(snapshot.get("license") == "Apache-2.0", f"{label} license drifted")
    require(snapshot.get("module_cache_complete") is True, f"{label} module cache incomplete")
    require(
        snapshot.get("available_source_modules")
        == snapshot.get("available_ilean_modules")
        == snapshot.get("available_olean_modules")
        == 7_871,
        f"{label} module cache census drifted",
    )
    rows = document.get("records")
    require(
        isinstance(rows, list)
        and len(rows) == rows_expected
        and all(isinstance(row, dict) for row in rows),
        f"{label} must have exactly {rows_expected} object rows",
    )
    seen_ids: set[str] = set()
    seen_names: set[str] = set()
    for index, row in enumerate(rows, 1):
        source_id = row.get("source_record_id")
        declaration = row.get("declaration")
        formal_type = row.get("formal_type")
        require(isinstance(source_id, str) and bool(source_id), f"{label}[{index}] source id missing")
        require(source_id not in seen_ids, f"{label} duplicates source id {source_id}")
        seen_ids.add(source_id)
        require(row.get("selection_rank") == index, f"{label} ranks are not dense 1..N")
        require(isinstance(declaration, str) and bool(declaration), f"{label}[{index}] declaration missing")
        normalized_declaration = normalize_name(declaration)
        require(normalized_declaration not in seen_names, f"{label} duplicates declaration {declaration}")
        seen_names.add(normalized_declaration)
        kind = row.get("declaration_kind")
        require(kind in {"theorem", "lemma"}, f"{label}[{index}] literal kind invalid")
        require(
            row.get("source_syntax_kind") == kind and row.get("raw_category") == kind,
            f"{label}[{index}] literal kind fields disagree",
        )
        require(isinstance(formal_type, str) and bool(formal_type), f"{label}[{index}] type missing")
        require(row.get("formal_type_sha256") == sha(formal_type.encode("utf-8")), f"{label}[{index}] type hash stale")
        require(row.get("formal_proof_state") == "kernel_checked_sorry_free", f"{label}[{index}] proof state drifted")
        proof = row.get("proof_evidence")
        require(isinstance(proof, dict), f"{label}[{index}] proof evidence missing")
        require(proof.get("uses_sorry") is False, f"{label}[{index}] permits sorry")
        require(
            proof.get("verification")
            == "lean_checked_environment_thmInfo_and_collectAxioms_without_sorryAx",
            f"{label}[{index}] verification mode drifted",
        )
        axioms = proof.get("batch_axiom_dependency_union")
        require(isinstance(axioms, list) and "sorryAx" not in axioms, f"{label}[{index}] has sorryAx")
        status = row.get("material_status")
        require(
            isinstance(status, dict)
            and status.get("status") == "proved_formal"
            and status.get("as_of_commit") == SOURCE_COMMIT,
            f"{label}[{index}] material status drifted",
        )
        rights = row.get("rights")
        require(isinstance(rights, dict) and rights.get("source_license") == "Apache-2.0", f"{label}[{index}] rights drifted")
        signal_kinds(row)
        module_root(row)
    counts = document.get("counts")
    require(isinstance(counts, dict), f"{label} counts missing")
    require(counts.get("selected_total") == rows_expected, f"{label} selected_total drifted")
    return rows


def formal_identity(row: Mapping[str, Any]) -> tuple[str | None, str | None, str | None]:
    formal = row.get("formal_statement")
    formal = formal if isinstance(formal, dict) else {}
    digest = formal.get("formal_type_sha256") or formal.get("declaration_type_sha256") or row.get("formal_type_sha256")
    text = formal.get("formal_type") or formal.get("declaration_type") or row.get("formal_type")
    name = (
        formal.get("declaration")
        or formal.get("qualified_declaration")
        or formal.get("declaration_name")
        or row.get("qualified_name")
    )
    exact = digest if isinstance(digest, str) and SHA_RE.fullmatch(digest) else None
    normalized_type = normalized_type_sha(text) if isinstance(text, str) and text else None
    normalized_name = normalized_name_sha(name) if isinstance(name, str) and name else None
    return exact, normalized_type, normalized_name


def parent_indexes(rows: Sequence[Mapping[str, Any]]) -> tuple[dict[str, list[str]], dict[str, list[str]], dict[str, list[str]]]:
    indexes: tuple[dict[str, list[str]], dict[str, list[str]], dict[str, list[str]]] = (
        defaultdict(list),
        defaultdict(list),
        defaultdict(list),
    )
    for row in rows:
        variant = row.get("variant_id")
        require(isinstance(variant, str) and bool(variant), "parent row lacks variant_id")
        for index, key in zip(indexes, formal_identity(row), strict=True):
            if key is not None:
                index[key].append(variant)
    return indexes


def source_identity(row: Mapping[str, Any]) -> tuple[str, str, str]:
    formal_type = str(row["formal_type"])
    declaration = str(row["declaration"])
    return (
        str(row["formal_type_sha256"]),
        normalized_type_sha(formal_type),
        normalized_name_sha(declaration),
    )


def duplicate_winner_rank(row: Mapping[str, Any]) -> tuple[int, int, str]:
    return (
        0 if "mathlib_1000_theorems" in signal_kinds(row) else 1,
        int(row["selection_rank"]),
        str(row["source_record_id"]),
    )


def build() -> tuple[list[dict[str, Any]], dict[str, Any]]:
    full, full_payload = load_json(FULL_SOURCE, FULL_SOURCE_SHA256)
    parent_source, parent_source_payload = load_json(PARENT_SOURCE, PARENT_SOURCE_SHA256)
    catalog, catalog_payload = load_json(PARENT_CATALOG, PARENT_CATALOG_SHA256)
    manifest, manifest_payload = load_json(PARENT_MANIFEST, PARENT_MANIFEST_SHA256)
    curation, curation_payload = load_json(V5_4_CURATION, V5_4_CURATION_SHA256)
    require(sha_file(EXTRACTOR) == EXTRACTOR_SHA256, "mathlib extractor drifted")

    full_rows = validate_source_document(full, FULL_ROWS, "full source")
    prefix_rows = validate_source_document(parent_source, PARENT_SOURCE_ROWS, "parent source")
    require(full_rows[:PARENT_SOURCE_ROWS] == prefix_rows, "full source does not preserve the exact 1,500-row parent prefix")
    for document, label in ((full, "full source"), (parent_source, "parent source")):
        thousand_plus = document.get("optional_thousand_plus_snapshot")
        require(isinstance(thousand_plus, dict), f"{label} omits the pinned 1000+ snapshot")
        require(
            thousand_plus.get("commit") == "8e04b97dd24adc6e931be78a884da7e935bc8780"
            and thousand_plus.get("license") == "Unlicense"
            and thousand_plus.get("records_loaded") == 1_200,
            f"{label} 1000+ snapshot drifted",
        )
    full_counts = full.get("counts")
    require(isinstance(full_counts, dict), "full source counts missing")
    require(
        full_counts.get("lean_verified_theorem_candidates") == FULL_ROWS
        and full_counts.get("source_screened_candidates") == 2_575
        and full_counts.get("runtime_rejected") == 9
        and full_counts.get("verified_reserve_after_selection") == 0
        and full_counts.get("selected_baseline") == 1_000
        and full_counts.get("selected_dynamic_expansion") == 1_566,
        "full source extraction counts drifted",
    )

    require(manifest.get("release") == "5.5", "parent manifest is not release 5.5")
    catalog_rows = catalog.get("records")
    require(
        isinstance(catalog_rows, list)
        and len(catalog_rows) == 4_525
        and all(isinstance(row, dict) for row in catalog_rows),
        "parent catalog denominator drifted",
    )
    parent_exact, parent_types, parent_names = parent_indexes(catalog_rows)

    # Resolve exact-identity duplicates over all literal theorem rows, using the
    # same winner order as the 5.3 curation.  Literal lemmas remain valid Lean
    # theorems but do not compete for the current release theorem quota.
    source_duplicates: dict[str, dict[str, str]] = {}
    seen_types: dict[str, str] = {}
    seen_names: dict[str, str] = {}
    for row in sorted(
        (item for item in full_rows if item["declaration_kind"] == "theorem"),
        key=duplicate_winner_rank,
    ):
        source_id = str(row["source_record_id"])
        _, norm_type, norm_name = source_identity(row)
        if norm_type in seen_types:
            source_duplicates[source_id] = {
                "source_record_id": seen_types[norm_type],
                "method": "unicode_whitespace_normalized_formal_type",
            }
            continue
        if norm_name in seen_names:
            source_duplicates[source_id] = {
                "source_record_id": seen_names[norm_name],
                "method": "unicode_nfkc_casefolded_declaration_name",
            }
            continue
        seen_types[norm_type] = source_id
        seen_names[norm_name] = source_id
    full_kind_counts = Counter(str(row["declaration_kind"]) for row in full_rows)
    full_exact_types = {str(row["formal_type_sha256"]) for row in full_rows}
    full_normalized_types = {
        normalized_type_sha(str(row["formal_type"])) for row in full_rows
    }
    require(
        len(full_exact_types) == len(full_normalized_types) == 2_561,
        "full-source exact and normalized formal-type identity counts drifted",
    )

    reserve = full_rows[PARENT_SOURCE_ROWS:]
    require(len(reserve) == RESERVE_ROWS, "reserve denominator drifted")
    candidates: list[dict[str, Any]] = []
    for candidate_index, row in enumerate(reserve, 1):
        exact, norm_type, norm_name = source_identity(row)
        parent_conflicts = {
            "exact_formal_type_variant_ids": sorted(parent_exact.get(exact, [])),
            "normalized_formal_type_variant_ids": sorted(parent_types.get(norm_type, [])),
            "normalized_declaration_name_variant_ids": sorted(parent_names.get(norm_name, [])),
        }
        parent_conflict = any(parent_conflicts.values())
        source_duplicate = source_duplicates.get(str(row["source_record_id"]))
        literal_theorem = row["declaration_kind"] == "theorem"
        mechanically_unique = not parent_conflict and source_duplicate is None
        mechanically_eligible = literal_theorem and mechanically_unique
        if mechanically_eligible:
            disposition = "mechanically_eligible_literal_theorem_unique"
        elif not literal_theorem:
            disposition = "literal_lemma_candidate_only_under_current_quota_policy"
        elif parent_conflict:
            disposition = "parent_exact_identity_conflict_candidate_only"
        else:
            disposition = "source_exact_identity_duplicate_candidate_only"
        kinds = signal_kinds(row)
        candidate: dict[str, Any] = {
            "schema_version": SCHEMA,
            "candidate_index": candidate_index,
            "candidate_key": f"mathlib-reserve-v5.6:{row['source_record_id']}",
            "source_index_zero_based": int(row["selection_rank"]) - 1,
            "selection_rank": row["selection_rank"],
            "source_record_id": row["source_record_id"],
            "source_record_sha256": sha(canonical(row)),
            "declaration": row["declaration"],
            "declaration_kind": row["declaration_kind"],
            "source_syntax_kind": row["source_syntax_kind"],
            "formal_type_sha256": exact,
            "normalized_formal_type_sha256": norm_type,
            "normalized_declaration_name_sha256": norm_name,
            "formal_proof_state": row["formal_proof_state"],
            "module": row["source"]["module"],
            "module_root": module_root(row),
            "importance_signal_kinds": list(kinds),
            "has_declaration_docstring": row.get("declaration_docstring") is not None,
            "truth_gate": "kernel_checked_thmInfo_collectAxioms_without_sorryAx_at_pinned_commit",
            "quality_gate": "mathlib_module_main_result_or_docs_1000_signal",
            "identity_review": {
                "parent_5_5": parent_conflicts,
                "source_duplicate_of": source_duplicate,
                "methods": [
                    "exact formal_type_sha256",
                    "Unicode-whitespace normalized formal type",
                    "Unicode NFKC-casefolded full declaration name",
                ],
            },
            "mechanically_unique_under_three_gates": mechanically_unique,
            "mechanically_eligible_for_release_curation": mechanically_eligible,
            "disposition": disposition,
            "candidate_only": True,
            "grants_catalog_entry": False,
            "grants_theorem_credit": False,
            "row_sha256": None,
        }
        candidate["row_sha256"] = hash_without(candidate, "row_sha256")
        candidates.append(candidate)

    # Re-audit the 231 unselected viable literal theorems left by 5.4 against
    # the current 5.5 parent, so the combined next-batch number is not assumed.
    dispositions = curation.get("candidate_dispositions")
    require(isinstance(dispositions, list), "5.4 curation rows missing")
    legacy_ids = {
        str(row["source_record_id"])
        for row in dispositions
        if isinstance(row, dict) and row.get("disposition") == "eligible_not_selected_after_5_4"
    }
    require(len(legacy_ids) == 231, "5.4 residual theorem denominator drifted")
    prefix_by_id = {str(row["source_record_id"]): row for row in prefix_rows}
    legacy_parent_conflicts = 0
    for source_id in sorted(legacy_ids):
        row = prefix_by_id.get(source_id)
        require(row is not None and row.get("declaration_kind") == "theorem", f"legacy residual {source_id} missing")
        exact, norm_type, norm_name = source_identity(row)
        # A residual is absent as a source record from the parent; any hit here
        # is a genuine cross-record identity collision in the current catalog.
        if parent_exact.get(exact) or parent_types.get(norm_type) or parent_names.get(norm_name):
            legacy_parent_conflicts += 1

    disposition_counts = Counter(str(row["disposition"]) for row in candidates)
    kind_counts = Counter(str(row["declaration_kind"]) for row in candidates)
    roots = Counter(str(row["module_root"]) for row in candidates)
    eligible_roots = Counter(
        str(row["module_root"])
        for row in candidates
        if row["mechanically_eligible_for_release_curation"] is True
    )
    signal_counts = Counter(
        kind
        for row in candidates
        for kind in set(row["importance_signal_kinds"])
    )
    parent_conflict_rows = sum(
        any(row["identity_review"]["parent_5_5"][field] for field in row["identity_review"]["parent_5_5"])
        for row in candidates
    )
    source_duplicate_rows = sum(row["identity_review"]["source_duplicate_of"] is not None for row in candidates)
    eligible = sum(row["mechanically_eligible_for_release_curation"] is True for row in candidates)
    unique_any_kind = sum(row["mechanically_unique_under_three_gates"] is True for row in candidates)
    declaration_docstrings = sum(row["has_declaration_docstring"] is True for row in candidates)
    legacy_current = len(legacy_ids) - legacy_parent_conflicts

    counts: dict[str, Any] = {
        "full_selected_source_rows": FULL_ROWS,
        "runtime_thmInfo_sorry_free_screened": 2_575,
        "metadata_quality_excluded_runtime_thmInfo": 9,
        "full_literal_declaration_kinds": dict(sorted(full_kind_counts.items())),
        "full_source_identity_duplicate_losers": len(source_duplicates),
        "full_unique_formal_proposition_identities": len(full_normalized_types),
        "preserved_parent_source_rows": PARENT_SOURCE_ROWS,
        "reserve_candidate_rows": RESERVE_ROWS,
        "reserve_kernel_checked_sorry_free": RESERVE_ROWS,
        "reserve_literal_declaration_kinds": dict(sorted(kind_counts.items())),
        "reserve_with_declaration_docstring": declaration_docstrings,
        "reserve_importance_signal_rows": dict(sorted(signal_counts.items())),
        "reserve_parent_identity_conflict_rows": parent_conflict_rows,
        "reserve_source_identity_duplicate_rows": source_duplicate_rows,
        "reserve_unique_any_literal_kind": unique_any_kind,
        "reserve_mechanically_eligible_literal_theorems": eligible,
        "reserve_by_disposition": dict(sorted(disposition_counts.items())),
        "legacy_5_4_residual_literal_theorems": len(legacy_ids),
        "legacy_5_4_residual_parent_5_5_conflicts": legacy_parent_conflicts,
        "legacy_5_4_residual_currently_mechanically_eligible": legacy_current,
        "combined_next_batch_mechanical_theorem_candidates": legacy_current + eligible,
        "documented_unadmitted_unique_runtime_thmInfo": legacy_current + eligible + 489,
        "documented_unadmitted_unique_literal_theorems": legacy_current + eligible,
        "documented_unadmitted_unique_literal_lemmas": 489,
        "current_release_mathlib_theorems": 1_000,
        "possible_mathlib_release_inventory_after_combined_batch": 1_000 + legacy_current + eligible,
        "all_2_566_selected_rows_are_runtime_thmInfo": True,
    }
    for key, expected in EXPECTED_COUNTS.items():
        require(counts.get(key) == expected, f"hard count {key}={counts.get(key)!r}, expected {expected!r}")
    require(dict(sorted(roots.items())) == EXPECTED_ROOT_COUNTS, "reserve module-root counts drifted")
    require(
        dict(sorted(eligible_roots.items())) == EXPECTED_ELIGIBLE_ROOT_COUNTS,
        "eligible reserve module-root counts drifted",
    )

    ledger_bytes = b"".join(canonical(row) + b"\n" for row in candidates)
    runtime_rejections = full.get("runtime_rejections")
    require(
        isinstance(runtime_rejections, list)
        and len(runtime_rejections) == 9
        and all(
            isinstance(row, dict)
            and row.get("runtime_kind") == "theorem"
            and row.get("uses_sorry") == "False"
            and row.get("reason") == "no_declaration_or_module_main_docstring"
            for row in runtime_rejections
        ),
        "the nine metadata-quality exclusions no longer share the proved runtime boundary",
    )
    inventory: dict[str, Any] = {
        "schema_version": INVENTORY_SCHEMA,
        "artifact": INVENTORY.name,
        "as_of": "2026-08-10",
        "candidate_only": True,
        "release_mutation_authorized_or_performed": False,
        "counts": counts,
        "module_root_counts": {
            "all_reserve": dict(sorted(roots.items())),
            "mechanically_eligible_literal_theorems": dict(sorted(eligible_roots.items())),
        },
        "inputs": {
            "full_source": binding(FULL_SOURCE, full_payload),
            "parent_1500_source": binding(PARENT_SOURCE, parent_source_payload),
            "parent_5_5_catalog": binding(PARENT_CATALOG, catalog_payload),
            "parent_5_5_manifest": binding(PARENT_MANIFEST, manifest_payload),
            "v5_4_mathlib_curation": binding(V5_4_CURATION, curation_payload),
            "extractor": binding(EXTRACTOR, EXTRACTOR.read_bytes()),
        },
        "output": {
            "path": LEDGER.relative_to(REPO).as_posix(),
            "sha256": sha(ledger_bytes),
            "size_bytes": len(ledger_bytes),
            "rows": len(candidates),
            "row_sha256_set_sha256": set_digest(str(row["row_sha256"]) for row in candidates),
            "source_record_id_set_sha256": set_digest(str(row["source_record_id"]) for row in candidates),
            "formal_type_sha256_set_sha256": set_digest(str(row["formal_type_sha256"]) for row in candidates),
        },
        "truth_and_quality_boundary": {
            "formal_truth": (
                "All 1,066 reserve rows are Lean ConstantInfo.thmInfo declarations in the pinned "
                "compiled environment, and collectAxioms reports no sorryAx. They are valid formal "
                "theorem propositions regardless of whether the source command says theorem or lemma."
            ),
            "release_quota_policy": (
                "The current 5.3/5.4 admission policy grants theorem quota only to literal `theorem` "
                "source commands; literal `lemma` rows remain candidate-only unless that policy is changed."
            ),
            "importance": (
                "Every reserve row is named by a mathlib module-doc Main results/theorems/statements "
                "bullet. This is source-level importance curation, not independent per-row landmark review."
            ),
            "individualized_prose": (
                "Rows without a declaration docstring reuse the exact module Main-result bullet, which may "
                "describe several declarations. The exact formal type remains individualized and authoritative."
            ),
            "identity": (
                "Exact formal-type hash, whitespace-normalized formal type, and NFKC-casefolded full "
                "declaration name are exact-identity gates only; they do not prove broader semantic equivalence."
            ),
            "release_credit": (
                "No row in this package allocates an ID, mutates a release, or grants theorem credit. "
                "Admission still requires release-specific allocation, parent-prefix conservation, and acceptance."
            ),
            "metadata_deficient_truth_rows": (
                "Nine additional source-screened declarations were runtime thmInfo with uses_sorry=False "
                "but are not in the 2,566-row artifact because they lack both a declaration docstring and "
                "a module Main-result description. They are listed below but are not counted as directly "
                "materialized release candidates until a dedicated per-row extractor seals their full payloads."
            ),
        },
        "metadata_quality_exclusions": [
            {
                "declaration": row["declaration"],
                "runtime_kind": row["runtime_kind"],
                "uses_sorry": False,
                "reason": row["reason"],
                "grants_catalog_entry": False,
                "grants_theorem_credit": False,
            }
            for row in runtime_rejections
        ],
        "putnam_one_hop_interface": {
            "mathlib_candidate_join_keys": [
                "declaration",
                "formal_type_sha256",
                "display_label",
                "importance_signals[].external_id (Wikidata, when present)",
                "source.module",
                "proof_evidence.olean_sha256",
                "source_snapshot.commit",
            ],
            "required_putnam_side_fields": [
                "problem_name",
                "formal_language",
                "formal_environment_commit",
                "theorem_type_direct_constant_names",
                "solution_body_direct_constant_names",
                "authoritatively_named_theorem_labels_from_solution",
                "wikidata_ids_from_authoritative_cross_references",
                "direct_reference_extractor_sha256",
            ],
            "creditable_candidate_edges": {
                "statement_uses_mathlib_constant": "exact direct constant in the elaborated Putnam theorem type",
                "proof_uses_mathlib_theorem": "exact direct constant in an available elaborated solution/proof body",
                "named_theorem_crosswalk": (
                    "normalized named-theorem label from an authoritative solution plus exact Wikidata or "
                    "mathlib declaration corroboration; remains review-required until the target statement matches"
                ),
            },
            "non_edges": [
                "module import alone",
                "transitive dependency without a direct constant reference",
                "topic/tag overlap",
                "normalized label alone without an authoritative named-theorem occurrence",
                "name or embedding similarity without direct elaborated reference",
            ],
            "commit_boundary": (
                "PutnamBench and this asset may pin different mathlib commits. Join by declaration name only as "
                "a candidate, then replay the declaration and compare elaborated types in both environments."
            ),
        },
        "replay": {
            "thousand_plus_required_commit": "8e04b97dd24adc6e931be78a884da7e935bc8780",
            "full_source_argv_template": [
                "python3",
                "Docs/tools/extract_mathlib_theorems_v5.py",
                "--output",
                "Docs/catalog/v5/curation/mathlib_reserve_v5_6/mathlib-verified-theorems-8a178386-full.json",
                "--thousand-plus-root",
                "<clean-1000-plus-checkout-at-required-commit>",
                "--baseline-count",
                "1000",
                "--dynamic-count",
                "1566",
                "--jobs",
                "4",
                "--check",
            ],
            "inventory_command": (
                "python3 Docs/catalog/v5/curation/mathlib_reserve_v5_6/"
                "build_mathlib_reserve_inventory_v5_6.py"
            ),
        },
        "authority_sha256": None,
    }
    inventory["authority_sha256"] = hash_without(inventory, "authority_sha256")
    return candidates, inventory


def binding(path: Path, payload: bytes) -> dict[str, Any]:
    return {
        "path": path.relative_to(REPO).as_posix(),
        "sha256": sha(payload),
        "size_bytes": len(payload),
    }


def atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="wb", prefix=path.name + ".", suffix=".tmp", dir=path.parent, delete=False
    ) as stream:
        temporary = Path(stream.name)
        stream.write(payload)
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def compare(path: Path, expected: bytes) -> None:
    try:
        observed = path.read_bytes()
    except OSError as error:
        raise InventoryError(f"cannot read generated output {path}: {error}") from error
    require(
        observed == expected,
        f"generated output drift: {path} sha256={sha(observed)}, expected {sha(expected)}",
    )


def git_text(root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(root), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise InventoryError(
            f"git {' '.join(args)} failed for {root}: {completed.stderr.strip()}"
        )
    return completed.stdout.strip()


def live_replay(thousand_plus_root: Path) -> str:
    root = thousand_plus_root.resolve()
    require(root.is_dir(), f"1000+ checkout does not exist: {root}")
    require(
        git_text(root, "rev-parse", "HEAD") == "8e04b97dd24adc6e931be78a884da7e935bc8780",
        "1000+ live-replay checkout has the wrong commit",
    )
    require(not git_text(root, "status", "--porcelain"), "1000+ live-replay checkout is dirty")
    command = [
        sys.executable,
        str(EXTRACTOR),
        "--output",
        str(FULL_SOURCE),
        "--thousand-plus-root",
        str(root),
        "--baseline-count",
        "1000",
        "--dynamic-count",
        "1566",
        "--jobs",
        "4",
        "--check",
    ]
    completed = subprocess.run(
        command,
        cwd=REPO,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise InventoryError(
            "live mathlib extraction replay failed:\n"
            + completed.stdout
            + completed.stderr
        )
    return completed.stdout.strip()


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="atomically write candidate outputs")
    parser.add_argument(
        "--live-replay",
        action="store_true",
        help="rerun Lean extraction and byte-compare the 2,566-row source before checking",
    )
    parser.add_argument(
        "--thousand-plus-root",
        type=Path,
        help="clean 1000+ checkout at the required commit (required with --live-replay)",
    )
    args = parser.parse_args(argv)
    if args.live_replay and args.thousand_plus_root is None:
        parser.error("--live-replay requires --thousand-plus-root")
    if args.thousand_plus_root is not None and not args.live_replay:
        parser.error("--thousand-plus-root is only valid with --live-replay")
    return args


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        replay_result = live_replay(args.thousand_plus_root) if args.live_replay else None
        candidates, inventory = build()
        ledger_payload = b"".join(canonical(row) + b"\n" for row in candidates)
        inventory_payload = pretty(inventory)
        if args.write:
            atomic_write(LEDGER, ledger_payload)
            atomic_write(INVENTORY, inventory_payload)
            action = "wrote"
        else:
            compare(LEDGER, ledger_payload)
            compare(INVENTORY, inventory_payload)
            action = "checked"
        counts = inventory["counts"]
        print(
            f"PASS {action} mathlib reserve v5.6 "
            f"full={counts['full_selected_source_rows']} "
            f"reserve={counts['reserve_candidate_rows']} "
            f"eligible={counts['reserve_mechanically_eligible_literal_theorems']} "
            f"combined={counts['combined_next_batch_mechanical_theorem_candidates']} "
            f"authority={inventory['authority_sha256']}"
        )
        if replay_result is not None:
            print("PASS live source replay: " + replay_result)
        return 0
    except InventoryError as error:
        print(f"FAIL mathlib reserve v5.6: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
